### ISSUE TITLE
attributeFields should support `only` (being the opposite of `exclude`)

### ISSUE THREAD

**Issue by mickhansen** [mickhansen/graphql-sequelize#1]

**Comment by brad-decker** [comment]
@mickhansen I would :+1: providing both options - Its pretty nice to have the exclude option if there's only one field you want to define yourself.

**Comment by mickhansen** [comment]
@brad-decker We already have `exclude`, this issue is to add `include` also, not to remove `exclude` (i realize the wording might be ambigious though).

**Comment by Aweary** [comment]
Just so I'm clear, you mean to have `include` be an option where, when provided, `graphql-sequelize` only looks at those fields, but when it's not provided, it defaults to the current behavior of parsing all the fields (minus any `excludes`), correct?

**Comment by mickhansen** [comment]
@Aweary Correct. `include` might not be descriptive enough, perhaps `only`?

**Comment by Aweary** [comment]
Yeah my first thought would be that `include` would be including *additional* fields or something. `only` seems semantically correct.

**Comment by mickhansen** [comment]
Yeah that is definitely one way to read it, it's definitely too ambigious then :)
