### ISSUE TITLE
Couldnt find anything that works with graphql-relay

### ISSUE THREAD

**Issue by MattMcFarland** [mickhansen/graphql-sequelize#107]
Your library seems to work with graphql but not graphql-relay, at least not with the examples I saw.

I was able to write up something pretty light weight that works well with graphql-relay, out of the box.

I could not figure out how to use your library, I kept getting errors whenever I tried to use it with `graphql-relay` `connectionArgs`, and `connectionFromArray`, etc.  `resolver` does not seem to work.

So after spending a couple hours hitting a wall I figured I'd just make something.

```javascript
**
 * Returns a promise that will resolve into an array by using the Model class
 * static findAll method.
 */
export const getModelsByClass = (model) => {
  return model.findAll();
};


/**
 * Returns a new promise containing a new array with only consumable data.
 */
export const getArrayData = (models) => {
  return new Promise((resolve, reject) => {
    try {
      resolve(resolveArrayData(models));
    } catch (error) {
      reject(error);
    }
  });
};

/**
 * Returns a promise that will resolve into a relay-compatible array of the
 * given Model Class.
 */
export const getArrayByClass = (model) => {
  return new Promise((resolve, reject) => {
    try {
      resolve(getArrayData(getModelsByClass(model)));
    } catch (error) {
      reject(error);
    }
  });
};


/**
 * Returns an array of Models by using the Model class static findAll method.
 */
export const resolveModelsByClass = async (model) => {
  return await model.findAll();
};


/**
 * Returns a new array containing only consumable data from a model array.
 * @param models Array<Model>
 * @returns Array<Object>
 */
export const resolveArrayData = (models) => {
  let array = models.map(model => {
    return Object.assign({}, {
        type: model.type
      }, {
        ...model.dataValues
      }
    );
  });
  return [].concat(...array);
};


/**
 * Returns a new array containing only consumable data from a model Class.
 * @param model
 * @returns Array<Object>
 */
export const resolveArrayByClass = async (model) => {

  let models = await resolveModelsByClass(model);
  return resolveArrayData(models);

};
```

You can now use `connectionArgs` `nodeConnections` etc

```javascript
      people: {
        decription: 'People',
        type: personConnection,
        args: connectionArgs,
        resolve: (root, args) =>
          connectionFromPromisedArray(resolveArrayByClass(Person), args)
      },
```

I even have some unit test that prove it:

[Imgur](http://i.imgur.com/j9uU0Oj.png)

I have a separate repo here, https://github.com/MattMcFarland/sequelize-relay - it does not work with mutations yet, at least its not set up to.  I am thinking it might be worth it to maybe modify graphql-sequelize instead

**Comment by mickhansen** [comment]
I use this library extensively with relay connections.

Have you looked at: https://github.com/mickhansen/graphql-sequelize/blob/master/docs/relay.md and https://github.com/mickhansen/graphql-sequelize/blob/master/test/integration/relay/connection.test.js?

**Comment by MattMcFarland** [comment]
No I havent.  I still want to use this library,  seems like youve already solved the problems I am facing.  I'm just having trouble implementing.  Thanks for sharing, I'll check out those links

**Comment by MattMcFarland** [comment]
Correct me if I'm wrong, but this library seems to create the node/connectors for you right?  Does it do so by modifying the SQL queries?  It might be a performance incentive to use this.  

From my perspective, I started with sequelize, then graphql, then combined graphql and sequelize without this library, as implementation was followed by a tutorial not mentioning this.

I then implement graphql-relay, and get that working, but to get graphql-relay to work with sequelize was a challenge.  

Now I'm kindof mulling back and fourth over whether or not to use this library.

**Comment by mickhansen** [comment]
You can choose to use this library to help you with connectors.
It provides effective ordered pagination via cursors and prefetching of connections where it makes sense.
