### ISSUE TITLE
Create a changelog.md

### ISSUE THREAD

**Issue by brad-decker** [mickhansen/graphql-sequelize#113]
Would be helpful on deciding to approve pull requests on our projects that are upgrading this module.

**Comment by mickhansen** [comment]
I attempt to track stuff with releases: https://github.com/mickhansen/graphql-sequelize/releases
But if a changelog helps i can start doing that.

**Comment by mickhansen** [comment]
Although i do notice that i haven't announced the more important stuff like proper Relay pagination support and stuff.

**Comment by brad-decker** [comment]
Sorry thats my ignorance there. :) thanks.
