### ISSUE TITLE
Support for aggregation functions and grouping

### ISSUE THREAD

**Issue by joewood** [mickhansen/graphql-sequelize#114]
I would like to add some special case `GraphQLObjectType`s that include aggregate functions and group by.  The original sequelize query that I'm trying to model in GraphQL is something like this:

``` javascript
   Customers.findAll({
        attributes: ["Name",[Sequelize.fn('COUNT',Sequelize.col("[Orders].[OrderId]")),"OrderCount"]],
        include:[{ association:customerOrders,attributes:[]}],
        group:["Name"]
);
```

I _could_ pull down the all the child entities and do the count on the server-side, but that is wasteful and impractical if there are 1000s of rows. So, in graph-sequelize there are 2 or 3 problems with modeling special case entities that include aggregate functions:
- No way to extend the `attributeFields` to include aggregate functions. 
- No way to stipulate a group clause in the options
- There are some assumptions in the code that the attribute list will always include the joined fields for the association. The empty array above removes them, but that seems to break the GraphQL sequelize resolver for associations.

Any thoughts, or am I doing this the wrong way?

**Comment by mickhansen** [comment]
Not sure we can come up with a design that accurately handles all the cases of aggregations.
The aggregations i have in my code are custom implementations, did not see a pattern that i could make generic.

**Comment by joewood** [comment]
OK, thanks - so I'm better off doing a raw query from GraphQL? That's fine - just checking I wasn't missing anything really.

**Comment by mickhansen** [comment]
@joewood or using Model.aggregate possibly

**Comment by joewood** [comment]
Ah, it seems I was missing something. Thanks.

**Comment by joewood** [comment]
One suggestion that would be really great to add to the library would be a special `resolver` function that performs an aggregation function on the linked association. This would mean modifying the resolver factory function to include the details of the `.aggregate` function. And also modify `generateIncludes` to integrate this into the generated SQL.  So it would be used something like this:
```javascript
let customerType = new GraphQLObjectType({
    name:"Customer",
    fields: () => _.extend(attributeFrields(customerTable), {
        orderCount: {
            type: GraphQLInt,
            resolve: aggregateResolver(customerTable.associations.orders,"count")
        }
    });
```
The generated SQL would have to group by all the fields outside of the aggregate association.

**Comment by mickhansen** [comment]
@joewood Mixing aggregations and includes can be tricky. With window functions you can do the most basic ones though.

**Comment by abelosorio** [comment]
Any news about this? I need to use aggregations but I can't found any documentation of that...

**Comment by lauraannwilliams** [comment]
@abelosorio I'm looking myself - I've found this: https://github.com/blueflag/graphql-aggregate but I'm still mid-evaluation

**Comment by abelosorio** [comment]
@lauraannwilliams could be useful. I'm using raw queries by now, but it's not a great solution. There is another way else to use aggregation in GraphQL?

**Comment by SirWojtek** [comment]
Hello @abelosorio, I think I figure out the pattern to get `COUNT`:
```
const modelType = new GraphQLObjectType({
  name: 'Model',
  fields: attributeFields(models.Model)
});
const modelWithCountType = new GraphQlObjectType({
  name: 'ModelWithCount',
  fields: {
    models: { type: new GraphQLList(modelType) },
    count: { type: GraphQLInt }
  }
});

const query = {
  type: modelWithCountType,
  args: { // some query arguments },
  resolve: resolver(models.Model, {
    list: true,  // NOTE: we return list of Models but using ModelWithCountType
    after: (models) => ({ models, count: models.length })
  }),
}
```
To summarize that: you need to create a GraphQL wrapper and manipulate a little with returned results. I hope it helps :)
