### ISSUE TITLE
How to support querying for null?

### ISSUE THREAD

**Issue by joewood** [mickhansen/graphql-sequelize#116]
GraphQL doesn't have a `null` literal, it relies on the defaultValue for the args input field. 
Is there a recommended literal value in graphql-sequelize that is used to interpret as null by the `resolver` function? What's the best way to support querying for null?

**Comment by mickhansen** [comment]
I haven't run into this problem yet so there's no official solution from the library.
Open to ideas :)

**Comment by joewood** [comment]
Right now I'm using special Boolean arguments, then hooking them up in the `before` callback.
I think when GraphQL will support null literals soon: https://github.com/facebook/graphql/pull/83. So, I assume GraphQL-Serialize will pass those nulls on to the `where` structure.

**Comment by legomind** [comment]
looks like null literals are part of the relay spec now.

**Comment by mickhansen** [comment]
@legomind Indeed
