### ISSUE TITLE
newEdge mutation helper

### ISSUE THREAD

**Issue by mickhansen** [mickhansen/graphql-sequelize#118]
When doing a mutation that results in an edge it would be great to have a sequelize helper to do the heavy lifting in terms of formatting it to the connection.

**Comment by mickhansen** [comment]
Also looking for any best practices on how to update relay connections after a mutation (how to deal with cursor value which currently also includes an order by value).

**Comment by mickhansen** [comment]
No real solutions to the cursor on mutation issue.

References:
http://stackoverflow.com/questions/32613879/should-the-opaque-cursors-in-connections-be-stable-across-different-field-args/32615799#32615799
https://github.com/facebook/relay/issues/293

**Comment by MattMcFarland** [comment]
Awesome!

On Wed, Jan 20, 2016 at 3:16 PM, Mick Hansen <notifications@github.com>
wrote:

> No real solutions to the cursor on mutation issue.
>
> References:
>
> http://stackoverflow.com/questions/32613879/should-the-opaque-cursors-in-connections-be-stable-across-different-field-args/32615799#32615799
> facebook/relay#293 <https://github.com/facebook/relay/issues/293>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mickhansen/graphql-sequelize/issues/118#issuecomment-173347375>
> .
>



-- 

Matt McFarland

Software Engineer | @docodemore <https://twitter.com/docodemore> | LinkedIn
<http://www.linkedin.com/pub/matthew-mcfarland/6a/b9a/135/en> | Mobile:
513.638.8685 | Office: 937.865.6800 xt: 125010

**Comment by mickhansen** [comment]
Simple resolveEdge helper added in `0.18.0` : https://github.com/mickhansen/graphql-sequelize/releases/tag/v0.18.0
