### ISSUE TITLE
Support latest graphql-js

### ISSUE THREAD

**Issue by amccloud** [mickhansen/graphql-sequelize#12]
I believe AST.selectionSet has been removed or renamed.

**Comment by mickhansen** [comment]
Thanks, i will look into it :)

**Comment by amccloud** [comment]
I've looked into this a bit more. The resolve function signature changed in 0.3.0.

> Field resolve functions now have a new API: resolve(value, args, info), where info is an object which contains the same information which used to be separate arguments, and includes more useful stuff! https://github.com/graphql/graphql-js/releases/tag/v0.3.0

I've done this in the meantime:

```javascript
let photoResolver = resolver(Photo);
//...
resolve: (value, args, {rootValue, fieldASTs, parentType}) => {
  return photoResolver(value, args, rootValue, fieldASTs, parentType);
}
//...
```

**Comment by mickhansen** [comment]
Ah okay so they mixed root, field and type into one field, should be a pretty trivial fix. Changing https://github.com/mickhansen/graphql-sequelize/blob/master/src/resolver.js#L31 to `source, args, {root, ast, type}` should work i think.

I'll see if i can't get a fix in today.

Thanks for using this lib @amccloud :)

**Comment by mickhansen** [comment]
Hmm, quite a few changes in how the AST is passed around now, working on a fix.

**Comment by mickhansen** [comment]
Should now work in `graphql-sequelize@0.6.0` do make sure to thoroughly test it though.
`fieldASTs` is now an array with a single element instead of the single element so i'm doing a naive fix with `fieldASTs[0]` but all my tests pass (but it's not the most comprehensive test suite in the world).
