### ISSUE TITLE
Map known String attributes in typeMapper

### ISSUE THREAD

**Issue by bringking** [mickhansen/graphql-sequelize#126]
I want to get your thoughts on mapping some column types, that sequelize doesn't have a concrete type for. 

For example, on my project we are running into string column types in our models for things like -

'longblob'
'char(72)'

With things like 'longblob', we can exclude that value, but it would be nice to supply a custom typeMapper for things like 'char' that tells graphql-sequelize to make it a string type. Something like -

```js
let autoMapped = attributeFields(Models.SomeLegacyThingWithChar,{
  typeMap:{
    'char(72)': GraphQLString,
    'longblob': GraphQLString
  }
});
```
I can work on this, if you think it is a useful addition.

**Comment by bringking** [comment]
hmm actually looking at the current sequelize source, longblog and char are supported concrete types. Might be useful to still provide a way to override type mapping though

**Comment by mickhansen** [comment]
For it to make sense it would probably be best if you could inject types at a higher level.
In the example you provided the user might aswell exclude htose two types and define them seperately.

**Comment by bringking** [comment]
Right, I think that makes sense

**Comment by mickhansen** [comment]
So maybe something like:

```js
import {typeMapper} from 'graphql-sequelize';
typeMapper.map([
  ['longblob', GraphQLString],
  [DataTypes.JSONB, GraphQLObjectType]
])
```
