### ISSUE TITLE
Add support for the rest of sequelizeTypes

### ISSUE THREAD

**Issue by Aweary** [mickhansen/graphql-sequelize#13]
We've run into an error where the `getAttributes` method fails if any of our attributes are `ENUM` or `JSONB`, for example.

`typeMapper` doesn't seem to check for those types. Do you think it'd be much work to get those supported as well? I'd be happy to give it a crack myself.

**Comment by mickhansen** [comment]
It's really just figuring out what they should map to i suppose.
I wanted to do JSONB but the closests is `GraphQLObjectType` and that needs a subset of fields, so you'd really look to define subfields for the JSONB which Sequelize doesn't support atm (but we've talked about doing sub schemas), we did something similar for VIRTUAL to support `returnType` to make VIRTUAL work with GraphQL.

ENUM should probably just map to a GraphQLString? That should be a trivial fix.

**Comment by Aweary** [comment]
I'll have to think about `JSONB` but `ENUM` should probably map to the `GraphQLEnumType`

**Comment by mickhansen** [comment]
Oh yeah if there's an GraphQLEnumType definitely map to that.

**Comment by Aweary** [comment]
I can get a pull request in to add `GraphQLEnumType` support (which, on that note, would you mind if we refactored it to use a `switch` statement? Seems like it'd be more readable than so many `if/else` statements)

As for `JSONB` I'm not seeing any real way to do it unless Sequelize supports sub-schemas. The fields have to come from some where. One options that might work is adding a field to the `options` parameter that can define field values, like:

```js
const fields = {
  data: {
    name: GraphQLString,
    id: GraphQLInt
  }
}

attributeFields(Model, { fields: { data: fields }}
```js

But I don't know, there doesn't seem to be any advantage using that over just using `exclude` and defining the properties yourself and merge with `_.assign`

**Comment by Aweary** [comment]
@mickhansen does sequelize support a way to get the `type` of an `ARRAY`'s elements? So if I declare:
```js
  type: ARRAY(STRING)
```
I want to be able to parse that out into
```js
 type: GraphQLList(GraphQLString)
```

Which means we need to be able to get the element type for the `ARRAY`. I didn't see any fields on the `Model.rawAttributes` object indicating this property was accessible.

**Comment by Aweary** [comment]
https://github.com/mickhansen/graphql-sequelize/pull/15 adds support for `ARRAY` and `ENUM`, though `JSONB` is still not supported yet.

**Comment by mickhansen** [comment]
@Aweary Sequelize doesn't support sub schemas at the moment.

**Comment by mickhansen** [comment]
JSONB will have to be solved with exclude + custom type at the moment
