### ISSUE TITLE
Support for connections

### ISSUE THREAD

**Issue by Jakedavies** [mickhansen/graphql-sequelize#14]
## I have the following connection setup on the user object, 

```
miners: {
      type: minerConnection,
      description: 'A users miners',
      args: connectionArgs,
      resolve:  (_, args) => resolver(models.Miner, args),
    },
```

this gives the the following error

```
Server request for query `AppHomeRoute` failed for the following reasons:

1. Cannot return null for non-nullable field MinerConnection.pageInfo.
   de{id,name},cursor},pageInfo{hasNextPage,hasPreviousPage}},i
                       
```

Is this designed to work with the :first and :find and :limit args that are needed for the graphql edge connection spec?

**Comment by mickhansen** [comment]
No official connection support at the moment, i want to look into soon now that Relay has been officially released.

I haven't gone through the spec much, i've mostly just implemented a working prototype that can resolve simply graphql query lookups - So there's probably a lot of the spec it doesn't cover yet :/

**Comment by Jakedavies** [comment]
I may look into implementing it and submitting a PR. Where would you add such code that adds additional data to the resolvers output?

**Comment by mickhansen** [comment]
@Jakedavies Unsure, if you could start by shortly summarizing what type of output we need to produce etc, give me a short rundown of the spec we could probably come up with a design.

**Comment by mickhansen** [comment]
But you should probably look at `resolver.js`

**Comment by mickhansen** [comment]
@Jakedavies FYI @brad-decker is doing work on it here: https://github.com/mickhansen/graphql-sequelize/pull/18.

**Comment by Jakedavies** [comment]
Cool looks good. Will try it out asap.
