### ISSUE TITLE
Nested hasMany List types, args don't work properly

### ISSUE THREAD

**Issue by bringking** [mickhansen/graphql-sequelize#152]
When you have nested relationships of a List type, the limit, order and offset args don't work. It seems order isn't applied, and limit creates an incorrect SQL query

Given a GraphQL Query like this-

``` js
{
  group(group_id: 5017) {
    deleted
    group_activity_logs(limit:10,offset:4) {
      log_date
    }
  }
}

```

results in a SQL query like this -

```
Executing (default): SELECT `group_activity_log`.* FROM ((SELECT `log_date`, `group_activity_log_id`,
`group_id` FROM `group_activity_log` AS `group_activity_log` WHERE `group_activity_log`.`group_id` = 
5017 LIMIT '10')) AS `group_activity_log`;
```

**Comment by mickhansen** [comment]
That query is the results of our include.separate code, not sure if there's an issue with order and that. It's likely a sequelize prbolem in this case.

You might want to look at implementing connections, they have pretty good support from this lib now.

**Comment by bringking** [comment]
Hmm I haven't heard about connections. Are they a relay feature or something in graphql?

**Comment by mickhansen** [comment]
It's part of the relay spec for graphql, but the entire pattern works well overall i think

**Comment by janlarsson** [comment]
Dont know if this is sequelize or not. But with nested "hasMany" there is a problem. If I set limit:1 then the first user gets repeated the total number of user times in the result. If I just add offset:0 it works fine. 

I think it works fine with a connection.

I'm new to sequelize and graphql so appolgies if I missed something obvious I should have known. At least there is an easy way around this.

{
  viewer {
    mmk {
    authproviders {
      users(limit:2, offset:0) {
        name
      }
    }
    }
  }
}
