### ISSUE TITLE
[enhancement] - Mutations

### ISSUE THREAD

**Issue by bringking** [mickhansen/graphql-sequelize#157]
Would it be useful to have a helper for generating standard mutations on Models? e.g. ```byId``` mutation for updating single records by primaryKey or ```byWhere``` to bulk update records

**Comment by mickhansen** [comment]
My mutations have all been as domain specific as possible so far so haven't quite seen usecases for a generic set of helpers here, but i welcome use cases / input for writing helpers.

**Comment by bringking** [comment]
I am closing this, I tend to agree that mutations are more case specific.
