### ISSUE TITLE
Serializing Dates - ISO vs. toString()

### ISSUE THREAD

**Issue by joewood** [mickhansen/graphql-sequelize#166]
I've always thought that ISO-8601 date format was preferred over the human readable format returned by toString(): http://stackoverflow.com/questions/10286204/the-right-json-date-format

Is there any way to change the default behavior so that Sequelize Date datatypes are converted toISODate()? Right now I'm using post processing in the resolver `after` field.

**Comment by mickhansen** [comment]
It would definitely by ideal that we convert to ISO instead since it's more easily `new Date()`'able. However currently the parsing is handled by graphqlstring, i'm not sure if there's a way to add a resolver for all types.

**Comment by joewood** [comment]
I worked out a way of doing using a custom Scalar type and the typemapper. This is a bit rough and ready, but if I define a custom scalar type like this:

```javascript    
function fromISODate(value) { 
    try {
        if (!value) return null;
        return new Date(value);
    }
    catch(e) {
        return null;
    }
 } 
 
 function toISODate(d) {
     if (!d) return null;
     if ((d instanceof Date)) {
        return d.toISOString(); 
     }
     return d;
 }
 
const GraphQLDate = new GraphQLScalarType({ 
   name: 'Date', 
   description: 'A special custom Scalar type for Dates that converts to a ISO formatted string ', 
   serialize: toISODate, 
   parseValue: fromISODate, 
   parseLiteral(ast) { 
       return new Date(ast.value); 
   }
});
```

Then I can use it through the typemapper like this:
    
```javascript
typeMapper.mapType( (typ)=>{
    if (typ instanceof Sequelize.DATEONLY) {
        return GraphQLDate;
    }
    return null;
})
```

It probably needs a few more checks, looking at the GraphQL scalar type definitions, but it seems to work OK so far.

**Comment by mickhansen** [comment]
@joewood Looks good, would love to see a PR
