### ISSUE TITLE
Custom id resolver

### ISSUE THREAD

**Issue by legomind** [mickhansen/graphql-sequelize#171]
`typeResolver ` provides a way to map from a model type to a graphQL type, but as far as I can see there is no way to resolve an id for an entity that is not a sequelize model.

Perhaps something like this?

```javascript
nodeTypeMapper.mapTypes({
  [User.name]: UserType,
  Viewer: ViewerType,
})

nodeTypeMapper.mapIdFetchers({
  Viewer: id => GetViewer(id),
})
```

**Comment by mickhansen** [comment]
Currently it just defaults to the passed type: https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L45

Which is not great in a few cases, had this problem myself that i had to work around.
Supplying your own node resolvers would probably be a good idea, also for models to provide ACL.

**Comment by mickhansen** [comment]
```js
nodeTypeMapper.mapTypes({
  [User.name]: UserType,
  'Viewer': {
    type: ViewerType,
    reslve: (id) => GetViewer(id)
   }
})
```

Might also be an option

**Comment by legomind** [comment]
I like that a lot.

Im willing to work on a PR, if we can nail down a direction.

**Comment by bringking** [comment]
I like the idea of just allowing a function similar to what @mickhansen has-

```
nodeTypeMapper.mapTypes({
  [User.name]: UserType,
  'Viewer': ()=> ViewType
})
```
For flexibility in any mapper. However, in the case of the `idFetcher`, the explicit creation of a another mapping like `mapIdFetchers` makes sense since they are used in different ways and the idFetcher functions will have to be functions that accept the `globalId` as a param.

**Comment by mickhansen** [comment]
@bringking They are actually only ever used for node lookups, so they are sort of tightly related.

**Comment by bringking** [comment]
Right, that makes sense. So based on how it is used in the relay `nodeConnections` function, I think @mickhansen's syntax would be good. In the lib, the `typeResolver` could use the defined `type` field, and the the `idFetcher` could use the resolve function.

**Comment by mickhansen** [comment]
The only problem is that the typeResolver simply gets whatever idFetcher returned and if say idFetcher returns something that's not necessarily a sequelize instance we can't use Model.name.

So in idFetcher we will likely have to append the type somehow (use a prop or whatever).

**Comment by legomind** [comment]
Where do we need/use `Model.name` from `idFetcher`'s output? Isn't the immediate output (inner function) of `idFetcher` passed directly into and used by the output of `nodeDefinitions`? [See here](https://github.com/mickhansen/graphql-sequelize/blob/ef3f21085a857e79888a535bebf02cf3bb44bdb4/src/relay.js#L69-L74)

Couldn't it be as simple as this?

```js
export function idFetcher(sequelize, nodeTypeMapper) {
  return globalId => {
    const {type, id} = fromGlobalId(globalId);
    const map = nodeTypeMapper[type];
    if (map && typeof map.resolve === 'function') {
      return map.resolve(globalId);
    }

    const model = sequelize.models.find(model => model === type);
    return model
      ? model.findById(id)
      : null;
  };
}

export function typeResolver(nodeTypeMapper) {
  return obj => {
    const name = obj.Model
               ? obj.Model.options.name.singular
               : obj.name;

    const map = nodeTypeMapper[name];
    return map && map.type
      ? map.type
      : null;
  };
}
```

**Comment by mickhansen** [comment]
@legomind No, if you have a custom non-sequelize type that code would not work. `typeof` returns the javascript type which will likely just be Object.

**Comment by legomind** [comment]
Ok what about an explicit type from instance mapping function?

Syntax:
```js
nodeTypeMapper.mapTypes({
 //No need to specify sequelize models here
  Viewer: {
    type: ViewerType,
    resolve: (id) => GetViewer(id),
   }
})

nodeTypeMapper.setTypeMapper(obj => obj.myCustomTest ? 'Viewer' : null)
//Returning a falsey value here will cause the default behavior of looking for a sequelize
//model 
```

Implimentation:
```js
class NodeTypeMapper {
  constructor() {
    this.map = { };
  }

  mapTypes( types ) {
    this.map = {
      ...this.map,
      types,
    };
  }

  typeFromInstance(obj) {
    return this.customTypeFromInstance
             ? this.customTypeFromInstance(obj)
             : null
             || obj.Model
                 ? obj.Model.options.name.singular
                 : obj.name;
  }

  setTypeMapper(mapper) {
    if (typeof mapper !== 'function') {
      throw new Error('argumnent mapper of NodeTypeMapper.setTypeMapper() must be a function');
    }

    this.customTypeFromInstance = mapper;
  }

  getFromType(type) {
    return this.map[type];
  }

  getFromInstance(obj) {
    return this.getFromType(this.typeFromInstance(obj));
  }
}
```

**Comment by mickhansen** [comment]
Or we could simply add a hidden prop to the item after resolving from id to help the user.

**Comment by legomind** [comment]
@mickhansen I assume by 'hidden prop' you mean attaching a prop to the prototype of the returned object?

**Comment by mickhansen** [comment]
@legomind Just the returned object, not the prototype.

**Comment by legomind** [comment]
@mickhansen what are your thoughts on #179?
