### ISSUE TITLE
Support For Mutations

### ISSUE THREAD

**Issue by brad-decker** [mickhansen/graphql-sequelize#19]
Need to add support for mutations to the resolver, or build a new resolver for mutations. I plan on working on this feature, but if you have any input on the best way to achieve this @mickhansen I'm open to ideas.

**Comment by mickhansen** [comment]
I was looking to get started on this soon aswell (although soon is whenever i feel like playing around with it).

Mutations should probably get their own resolvers, i haven't looked to much at how they are integrated in graphql but i believe they get their own section right?

**Comment by brad-decker** [comment]
@mickhansen we have a solution started on a branch of our fork. It uses two different mutation Resolvers and has a few helper functions.

**Comment by xpepermint** [comment]
+1 for this. Btw... how do we handle (form) validations?

**Comment by mickhansen** [comment]
@xpepermint sequelize validations would still work. And i assume that mutations will be typed so you can atleast ensure correct types and non-null if needed.

**Comment by xpepermint** [comment]
@mickhansen that's good. I think that the validation part will be tricky. My forms usually depend on server-side validation error messages. I show each error message directly under form's field after validating a form (e.g. is required, is not an email). It seems to me that GraphQL expects the `human validation` part (error messages for a user) to be handled by the client itself and not to rely on the server response content, which is probably better anyway. I think that the server-side errors are meant for developers only. In case of an email validation we won't get a nice structured error message but just a text message (a sentence) explaining what went wrong. Just some thoughts ... Am I correct?

**Comment by mickhansen** [comment]
@xpepermint well that's really up to you, the sequelize validation output is a structure containing the rule that failed, on what value, etc.

**Comment by brad-decker** [comment]
I'll run some tests on graphql error messages for validations and let you know what results we get. There is an errors object returned on all GraphQL errors, so hopefully that'll contain some information. if it doesn't by default we could look into integrating the error handling portion more closely with sequelize.

**Comment by xpepermint** [comment]
@brad-decker that's great!

**Comment by xpepermint** [comment]
This debate https://github.com/graphql/graphql-js/issues/179 could help us here.

**Comment by brad-decker** [comment]
Thanks @xpepermint - will definitely use this as resource when we dive more into mutation support.

**Comment by brad-decker** [comment]
We're currently trying to figure out what is the right amount of auto generation when it comes to mutation support. Too much magic and its not clear how things are working and there's too much of an opportunity for random errors. 

We're also trying to add support for graphql-relay mutations with client ids so that users will have the option to support their own custom mutations or use the mutateAndGetPayload feature of graphql-relay-js mutations

**Comment by mickhansen** [comment]
Would love to see any preliminary api designs you have @brad-decker.
I was thinking perhaps just offer mutation helpers, so users define mutation skeletons but can implement helpers for CRUD stuff if need be.

**Comment by xpepermint** [comment]
https://github.com/graphql/express-graphql/issues/12

**Comment by xpepermint** [comment]
Btw, I started with this https://github.com/xpepermint/graphql-type-factory.

**Comment by mickhansen** [comment]
@brad-decker Any progress here? Getting started on mutations myself and would love to hear what experiences you might have had - Not sure it makes sense to provide that much help from this library since most mutations have a bit of logic (unless we're talking straight up create association or model instance from supplied values).

**Comment by mmahalwy** [comment]
Any update on this? @rpellerin created an awesome lib: https://github.com/rpellerin/graphql-sequelize-schema-generator
