### ISSUE TITLE
Resolving “IS A” relationship with graphql-sequelize

### ISSUE THREAD

**Issue by alexandrejunges** [mickhansen/graphql-sequelize#209]
Hi,

I'm having some troubles to resolve a "IS A" relationship, and I'd like to check if anyone could help me.
I posted a question on Stackoverflow, where I described the whole scenario: http://stackoverflow.com/questions/36441286/resolve-is-a-relationship-with-graphql-sequelize

Thanks

**Comment by mickhansen** [comment]
All association calls return an association reference that you can use as the argument of graphql-sequelize's resolver, have you given that a go?

**Comment by mickhansen** [comment]
Also to clarify, belongsTo is not a "IS A" relationship (atleast i do not believe so), it's simply a 1:1 with the foreign key on the source.

**Comment by alexandrejunges** [comment]
Thanks for the help @mickhansen. 
I looked into my models and found the `associations` property.  Using this property I was able to resolve the field and return the user related to the patient.

My resolve ended up something like this:
```
import * as models from '../path/models'

let patientType = new GraphQLObjectType({
    name: 'Patient',
    fields: {
        id: { type: new GraphQLNonNull(GraphQLInt) },
        bloodType: { type: GraphQLString },
        user: {
            type: new GraphQLNonNull(userType),
            resolve: resolver(models.default.Patient.associations.User)
        }
    }
});
```

Related to the kind of relationship, `belongsTo` is not always a "IS A" relationship, but the way I'm doing it is, because the foreign key is also the table's primary key.

I'd also like to congratulate for this great project :smile:

**Comment by mickhansen** [comment]
Associations are also added in `associations` by default, that's correct.

However you could also simply have done `models.default.Patient.User = models.default.Patient.belongsTo(odels.default.User);`, any association call returns a reference you can store just about anyware.

**Comment by mickhansen** [comment]
And thanks for the praise :)
