### ISSUE TITLE
first/last, before/after support

### ISSUE THREAD

**Issue by mickhansen** [mickhansen/graphql-sequelize#21]
It would be great to support the Relay connection args out of the box for users.
`first`/`last` would simply require the user to select what field to order on.

`before`/`after` is a little more tricky, we can't simply do a comparison on ID since the order might be on something that doesn't align with the ID.

We might need to do something like `[field] > (SELECT [field] FROM [table] WHERE id = [after] LIMIT 1)` which might kill performance slightly.

/cc @brad-decker

**Comment by brad-decker** [comment]
graphql/graphql-relay-js package actually supports this with their default result parsing feature. I really think that trying to add native postgres query support for this would just result in a slower operation then what is being done already. Added tests for all the mentioned arguments to show it working.

**Comment by mickhansen** [comment]
Haven't looked at the relay code yet, but i assume it does filtering after the values have been loaded from the database?
So in the case where you have 500 tasks, it will load all 500 and then take N of that? Then it might be good to actually filter in SQL instead.

**Comment by brad-decker** [comment]
yeah, the filtering is done on the result level - not prior to the data being queried. We'd have to do a deeper integration which we will most definitely want to implement at some point for application speed. Before After also uses a cursor for record parsing so we'd need to really look into how that cursor is generated and apply that our code. 

This will be an optimization level feature for our project so it might be a bit before we get to it.

**Comment by mickhansen** [comment]
I'll likely need it for my project since querying the entire range would be very expensive.
Not sure when i'll switch to Relay queries though since i'm using GraphQL with Angular atm.

**Comment by mickhansen** [comment]
https://github.com/graphql/graphql-relay-js/issues/20

**Comment by mickhansen** [comment]
So there's some talk about constructing your own cursors and storing data in them.
For example if paging by say createdAt, each cursor could hold that items createdAt value to easily filter without having to do a subquery lookup.

**Comment by mickhansen** [comment]
We'll probably need custom logic for all this, and won't be able to use `graphql-relay`'s connectionFromArray like we currently do (https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L38).

/cc @Aweary @brad-decker

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/commit/bc9683feeabc88e6150d6c707730e586075b9d42
