### ISSUE TITLE
update to graphql-js@0.5

### ISSUE THREAD

**Issue by jonathanewerner** [mickhansen/graphql-sequelize#211]
graphql-js@0.5 has changed the params of the resolve fns -- [info is now 4th, context is now 3rd](https://github.com/graphql/graphql-js/releases). The resolver will have to be updated in order to be compatible with this breaking change.

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/pull/205

**Comment by mickhansen** [comment]
Looks like graphql-relay finally got around to updating to graphql, so i'll finish the PR :)

**Comment by mickhansen** [comment]
Or no, they haven't released a new version, so still waiting on them.

**Comment by jonathanewerner** [comment]
! cool, missed that. thanks for the pointer!
btw: we don't use relay and it's a bit weird that is still is a required dependency. But i guess there is no better way to do this, is it?

**Comment by mickhansen** [comment]
Yeah it's not ideal, but haven't found a way to solve it.
With moving to npm3 in the future we can make both graphql and graphql-relay peer dependencies probably.

**Comment by jonathanewerner** [comment]
npm would still warn when i don't install graphql-relay though, right? I don't now if there's a way to specify "optional peerDependencies" ?

**Comment by mickhansen** [comment]
Hmm, good question, i don't know if it warns or errors.

**Comment by satya164** [comment]
@mickhansen NPM 2 errors, NPM 3 warns.

**Comment by mickhansen** [comment]
Thanks @satya164, sounds like the way to go moving forward.

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/releases/tag/v1.0.0

**Comment by jonathanewerner** [comment]
:+1: Congrats!
