### ISSUE TITLE
Make graphql-sequelize installable from repository through npm

### ISSUE THREAD

**Issue by brad-decker** [mickhansen/graphql-sequelize#217]
Would love to see this package installable from github so i can test out features from forks/etc that aren't ready for release. In the past i've had to include the lib folder into my forks to use them immediately for whatever project i'm working on. I'd love to avoid this as i know its a headache for package maintainers, etc. 

Any thoughts?

**Comment by mickhansen** [comment]
No idea how to handle this, maybe we can look at other projects using ES6

**Comment by bringking** [comment]
@brad-decker @mickhansen Kent Dodds talks about this [here](https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564#.7jvk9q7ts). TLDR - some ideas are having separate branches or tags where you commit build artifacts, or possibly even another repository. Also, @brad-decker have you checked out running `npm link`? I used that in the past to link any resolution of `graphql-sequelize` to my local version and not the version on NPM

**Comment by brad-decker** [comment]
@bringking the problem with that approach is that with Heroku everytime you deploy the entire disk is wiped and reinstalled from npm. I suppose it would be theoretically possible to create a script to download from github, build then install it and then use npm link to achieve what you're talking about but it would be difficult at best.

**Comment by brad-decker** [comment]
If only there were a way to instruct npm to build the lib folder after install that'd be key, but my attempts to do this were folly due to different versions of babel, etc.

**Comment by bringking** [comment]
@brad-decker you can do that using the `postinstall` npm method, however the problem with that is you are requiring all the downstream users to build the library on their local machines. However, for a branch you could just 

* add `babel-cli` as a dev dependency
* add a postinstall task to `npm run build`

That should do what you need..

**Comment by brad-decker** [comment]
I like that better than adding the lib folder to the fork/branch, but it still creates a hurdle to jump when said fork or branch is ready to be merged and you have to remove those dependencies. You're then forced to halt further development until your fork is merged into the main code base in order to prevent heroku from rebuilding your packages. If there is some way to add the functionality to the main package without automatically building it for every user, but make it available if they want to, that'd be superb.

maybe using something like this package testdouble/scripty to control logic of whether it should be built or not. It just adds more dependencies to the package that are only required for a small subset of users.

**Comment by mickhansen** [comment]
A branch with a postinstall script could be doable.

**Comment by brad-decker** [comment]
Any work towards this effort is kind of moot and would be overwritten by ES modules directives currently being worked on. I am fine with closing this issue.
