### ISSUE TITLE
scope in sequelizeConnection

### ISSUE THREAD

**Issue by adamdilek** [mickhansen/graphql-sequelize#221]
How can I use scopes in sequelizeConnection ?

``` js
before: (options, args) => {
      const opt = options;
      opt.scope = false; // or opt.scope = 'onlyActive'
      return opt;
}
```

Thanks.

**Comment by mickhansen** [comment]
Not possible at the moment unless you use a scoped `target`

**Comment by RichAyotte** [comment]
Would patching the resolver helper to do something like the following be acceptable:

```js
resolver(SequelizeModel, {
  scopes: []
})
```

**Comment by mickhansen** [comment]
@RichAyotte Could work, but i think the original poster likely wanted to determine scope based on input

**Comment by RichAyotte** [comment]
We could make it a more dynamic with a function.

```js
resolver(SequelizeModel, {
  scope: (options, args, context) => {
    const s = []
    if (options.onlyActive) {
      s.push('onlyActive')
    }
    return s
  }
})
```

```js
return model.scope(...options.scope(options, args, context))[list ? 'findAll' : 'findOne'](findOptions);
```

**Comment by mickhansen** [comment]
@RichAyotte Having `target` be dynamic would solve that usecase aswell as a few others i think :)
