### ISSUE TITLE
[Bug] EnumType duplicated

### ISSUE THREAD

**Issue by Beingbook** [mickhansen/graphql-sequelize#223]
In converting `Sequelize.ENUM` to  `GraphQLEnumType`
When I called twice same model with EnumType, graphql spits schema duplicated.

**Comment by Glavin001** [comment]
Could you provide an [MCVE](http://stackoverflow.com/help/mcve) ? Thanks.

The applicable code is https://github.com/mickhansen/graphql-sequelize/blob/4826e076f052b4667e6c7a640b319503f6a66bf1/src/attributeFields.js#L27 and may be a simple fix.

**Comment by Glavin001** [comment]
I am also experiencing this issue. I will see what I can do to fix it.

**Comment by Glavin001** [comment]
I've added a failing unit test to show the existence of this error:

```
  1) attributeFields should not create multiple enum types with same name:
     Error: Schema must contain unique named types but contains multiple types named "0.09031097055412829enumEnumType".
```

I'm working on a fix now. I think it will end up being that the fields are cached given an optional argument to `attributeFields`.

```javascript
var cache = {};
// First use: Will store in cache
attributeFields(Model, {cache: cache});
// Second use: Will retrieve from cache
attributeFields(Model, {cache: cache});
// No error message
```

This could also be automatic such that the caching is global for graphql-sequelize. Thus, the `cache` option would not be required. The disadvantage is that the `attributeFields` function would not have side effects, the cache.

@mickhansen, what are your thoughts on this?

**Comment by mickhansen** [comment]
@Glavin001 Under what circumstances does this happen in a real world case?

**Comment by mickhansen** [comment]
Ah if you reuse a model multiple places that has an Enum type.

**Comment by Glavin001** [comment]
I apologize that the example in my unit test was rather impractical, however at least it demonstrates the error message.

I think in my case it has to do with using `attributeFields` in multiple places for generating GraphQL Schema dynamically ( #262, #263 ), which is working fairly well with the exception of ENUM types.

**Comment by Glavin001** [comment]
Pull request submitted: https://github.com/mickhansen/graphql-sequelize/pull/272
