### ISSUE TITLE
MySQL hasNextPage returns null

### ISSUE THREAD

**Issue by adamdilek** [mickhansen/graphql-sequelize#226]
In MySQL hasNextPage returns null

I was this
https://github.com/mickhansen/graphql-sequelize/blob/4641eb60d062082304d8ac38c87df76d082d5c66/src/relay.js#L225

How is working `full_count` in MySQL ?

**Comment by mickhansen** [comment]
mysql have no window functions so full_count is not available.
If you can investigate a good fix it'd be welcome, graphql-sequelize is postgres-first generally though (since that's what i use)
