### ISSUE TITLE
attributeFields should transform comment into description

### ISSUE THREAD

**Issue by ofbeaton** [mickhansen/graphql-sequelize#229]
It would be nice if the `attributeFields()` function turned my `comment` on my sequalize models into `description` fields on my graphql schema object types. 

I realize this would not always be desirable, so it could be an option like `comments: true` perhaps? I suppose `false` until you can introduce `true` as a BC.

Apologies if this is already handled somehow and I missed it in the documentation.

**Comment by mickhansen** [comment]
I don't use comments at all, so not implemented and i don't plan to do it personally.
I'd welcome a PR, although it could be considered leaking.

**Comment by ofbeaton** [comment]
The base example https://github.com/mickhansen/graphql-sequelize#examples shows you using `description` on every single field, but https://github.com/mickhansen/graphql-sequelize#field-helpers no longer has them.

I realize this is a "quick and dirty" helper function, but even if you took a custom `description` property we could set on the model, it would allow us to at least preserve the description of the fields which I see as a common use case.

Right now it seems like the helper is not useful if I want descriptions on my fields.

**Comment by mickhansen** [comment]
The field helpers have never had them, the example is just an example graphql setup.
I'm open to the idea, just not sure how to approach it the best way :)

**Comment by ofbeaton** [comment]
Ah yes, english is a bit silly. I meant that the field-helper did not have `description` on the fields, so that was lost information if using the helper compared to the graphql example given.

**Idea #1: Comment field**
My first though was to re-use the `comment` field on the model, as sequelize supports them. It seems that if you are assuming the column names should stay the same by default, perhaps the comments could become descriptions without too much worry. As you say this could potentially be a security issue if they were not meant to be exposed, given currently the comments are ignored.  There could be a option to toggle this behaviour, false by default.

```
var Model = sequelize.define('User', {
  email: {
    comment: 'the primary email address',
    type: Sequelize.STRING,
  }
};

attributeFields(Model);

/*
{
  email: {
    description: 'the primary email address',
    type: GraphQLString
  }
}
*/
```

**Idea #2: description property on model fields**
Have a custom property not supported by sequelize lifted up. `description` would do. I actually made this mistake at first, definiting it on my model then scratching my head why it wasn't being show in graphiql. Of course definiting it on my Model is different than on my type. The danger here is that sequelize may make use of it in the future, or will decide that they would rather raise some kind of error. They currently do not. There could be a option to toggle this behaviour, true by default.

```
var Model = sequelize.define('User', {
  email: {
    description: 'the primary email address', /* sequelize appears to ignore this field without complaint */
    type: Sequelize.STRING,
  }
};

attributeFields(Model);

/*
{
  email: {
    description: 'the primary email address',
    type: GraphQLString
  }
}
*/
```

**Idea #3: Use options**
Just like we can use `map` to rename fields from the model to the type, we could use a `description` object to define description. I do think this is a bit different in spirit however, since we are not transforming information here, but decorating it. This is my least favourite.

```
var Model = sequelize.define('User', {
  email: {
    type: Sequelize.STRING,
  }
};

attributeFields(Model, {
  descriptions: {
    'email': 'the primary email address'
  }
});

/*
{
  email: {
    description: 'the primary email address',
    type: GraphQLString
  }
}
*/
```

In the end the question that I have to ask myself is at what point is the helper doing so much at this point that it isn't worth using, and I should instead just be specifying my fields by hand. Pretty much every example of a graphql type out there includes at minimum the field name, the field type and the field description. Including your very own example you provide. 

So I feel confidant saying that this would be good functionality for the field helper to provide.

What are you thoughts on the best way to go about this? I am sure you are also aware of more ideas for how this could be implemented.

**Comment by mickhansen** [comment]
I like all 3 options, with #1 having a `commentToDescription: true` or whatever

**Comment by Glavin001** [comment]
Any progress on this? This should be fairly straightforward to implement by making a few changes to https://github.com/mickhansen/graphql-sequelize/blob/master/src/attributeFields.js  
Idea #1 makes sense since it reuses the existing practice of `comment` field on the Sequelize models.

I am open to submitting some Pull Requests to this project as I plan to be using it over the next couple weeks. Let me know if someone is already tackling this issue. Thanks.

**Comment by mickhansen** [comment]
@Glavin001 As i mentioned i have no plans to implement this, but i'd likely merge a PR providing #1

**Comment by Glavin001** [comment]
> As i mentioned i have no plans to implement this

No problem, I don't expect you to. Thanks for starting this project! Now it's time for your users to contribute back 😉 .

> i'd likely merge a PR 

See #260. Hope that looks good to you.

**Comment by ofbeaton** [comment]
Thank you for making the pull request @Glavin001, I never got to doing the code and submitting it, but I'm delighted you managed to put it together so quickly! Hopefully it gets merged in soon.

**Comment by ofbeaton** [comment]
I just noticed the PR did not update the documentation. Given that the graphql shown in readme shows comments, it would go a long way if the graphql-sequelize also generated those same comments. It would make it consistent.
