### ISSUE TITLE
How do I use GraphQl params to implement custom logic

### ISSUE THREAD

**Issue by Ajar-Ajar** [mickhansen/graphql-sequelize#238]
Hi all, just starting my experiments, I've defined a GraphQL query that accepts args. 
I need to use these args to implement custom logic.     
For example - I want to get all users that logged in in the last xx days:
without using graphql-sequelize you are able to implement the actual query...
how do you get the same flexibility with the resolver?

 ```
users: {
      type: new GraphQLList(House),
      args:{
              days: {type:GraphQLInt}
      },
      resolve: resolver(models.User)
/*
     //without using graphql-sequelize you are able to implement the actual query...
      //how do you get the same flexibility
        resolve(root,args){
		return models.User.findAll({raw:true,where:lastLogin< now - args.days})...
	}
 */
}
```

**Comment by mickhansen** [comment]
```
resolve: resolver(models.User, {
  before: function(options, args, context) {
    
    return options;
  }
})
```

https://github.com/mickhansen/graphql-sequelize/blob/master/src/resolver.js#L104

**Comment by Ajar-Ajar** [comment]
Dear Mick,
I know that function gives you the entry point for configuring the query options before it's executed.
Still - can you please give me an obvious example to something like - get all users over the age of 18...
I know it's trivial for you, But I can't see how to set it...
Cheers :)

**Comment by Ajar-Ajar** [comment]
something like this?
```
resolve: resolver(models.House_schedule, {
	          before: (options, args, context) => {
		      return Object.assign(options,{where:age{ $gte:18}})
	          }
             })
```

**Comment by mickhansen** [comment]
Something like that :)
