### ISSUE TITLE
Support GraphQL fragments

### ISSUE THREAD

**Issue by Aweary** [mickhansen/graphql-sequelize#24]
Currently `graphql-sequelize` will fail if a query contains a fragment. For example: 

```js
query RootQueryType { post(id: 1) { title, ...contentFrag }} fragment contentFrag on Post { content }
```

Will initially fail with an error:

```js

TypeError: Cannot read property 'reduce' of undefined
    at selections.reduce.fields (/Users/[redacted]/API/node_modules/graphql-sequelize/lib/simplifyAST.js:44:53)
    at Array.reduce (native)
    at simplyAST (/Users/[redacted]/node_modules/graphql-sequelize/lib/simplifyAST.js:30:21)
    at resolver (/Users/[redacted]/node_modules/graphql-sequelize/lib/resolver.js:63:50)
    at resolveField (/Users/[redacted]/node_modules/graphql/execution/execute.js:399:18)
```

Because:

```js
  simpleAST.fields[key].args = selection.arguments.reduce(function (args, arg) {
      args[arg.name.value] = arg.value.value;
      return args;
    }, {});
```

Assumes that a field will have an arguments property, while `fragmentSpread` will not.

**Comment by Aweary** [comment]
If we fix (AKA avoid) that issue by defaulting `selection.arguments` to an empty array

```js
selection.arguments = selection.arguments || [];
```

We get a new error: 

```js
TypeError: Cannot read property 'resolve' of undefined
    at /Users/[redacted]node_modules/graphql-sequelize/lib/generateIncludes.js:40:45
```

Because:

```js
includeResolver = type._fields[name].resolve
```

assumes that the the `name` will be in the `type._fields` object, which is not true for fragments. If we *ignore* those by breaking the `forEach` loop

```js
if (!type._fields[name]) return;
```
`graphql` returns the error `"Cannot return null for non-nullable field Post.content."`.

It makes sense that it'd return that error since we're ignoring it and not providing a resolver, so we just need to work on properly identifying when a fragment is being used and how we can find the field its referencing and associate that with the proper resolver.

@mickhansen we're trying to work on this on our end, but any input would be helpful

**Comment by mickhansen** [comment]
Hmm yeah we might have to update the simpleAST parser to check for fragments first and then insert them when needed.

**Comment by Aweary** [comment]
@brad-decker is working on something. The `info` argument for the `resolve` function contains details on any included fragments.

**Comment by mickhansen** [comment]
`v0.10.0`
