### ISSUE TITLE
Passing defaultAttributes to relay connection

### ISSUE THREAD

**Issue by ekosz** [mickhansen/graphql-sequelize#241]
Is there a way to do this at the moment? Here's what code I'm thinking of:

``` js
export default () => relay.sequelizeConnection({
  name: 'activityComments',
  nodeType: ActivityCommentType,
  target: db.BaseActivity.Comments,
  connectionFields: {
    total: {
      type: GraphQLInt,
      resolve: ({ source }) => source.countComments(),
    },
  },
  defaultAttributes: ['entityId'], // <-- Is there a way of doing this?
});
```

**Comment by mickhansen** [comment]
Why would this be required exactly? It resolves a nodeType where you can control the attributes

**Comment by mickhansen** [comment]
I generally don't use attribute filtering because it constantly kept blowing up in my face.
Nothing is supported atm, it's something we could look at.

**Comment by ekosz** [comment]
@mickhansen Oh, is there a way to turn off attribute filtering globally? I'd also be down to just to that.

**Comment by ekosz** [comment]
Nevermind, found it! `resolver.filterAttributes = false`
