### ISSUE TITLE
Resolver Loses Variable Value

### ISSUE THREAD

**Issue by timscott** [mickhansen/graphql-sequelize#250]
GaphQL query:

``` graphql
query($id: String!, $statusChangesFrom: String) {
  driver(id: $id) {          
    id  
    firstName  
    lastName  
    statusChanges(from: $statusChangesFrom) {
      id  
      changeAt  
    }      
  }
}
```

Variables:

``` json
{
  "id": "8b2bbb20-1df9-11e6-9ad1-dd78b5a1c3ad",
  "statusChangesFrom": "05/31/2016"
}
```

Using the `graphql-sequelize` resolver:

``` javascript
resolve: resolver(User.StatusChanges, {
  before: (options, args) => {
    if (args.from) { 
      //We never get here because args.from is { "from": undefined }.
    }
  }
})
```

With custom resolver:

``` javascript
resolve: (user, args) => {
  if (args.from) {
    //We do get here because args.from is  "05/31/2016"
  }
})
```

Bug?

**Comment by mickhansen** [comment]
relay variables usually work just fine when i'm using them with graphql-sequelize, however only a few varaibles actually become variables in the query (most are just injected directly into the query).

PR with test welcome, but we pass args as it to you, so i doubt it's a bug in this project

**Comment by timscott** [comment]
The example above is the actual code, which proves to me that the resolver does not (in this case) pass values. For now, I've solved it by using my own resolver (as shown in OP). I spent a couple of hours debugging trying to see where the value is being dropped, without luck. When I find time I will make make a failing test and try to solve it make a PR. Thanks.

**Comment by manhhailua** [comment]
I got the same issue! Is this bug?
