### ISSUE TITLE
Incorrectly quoted table name in relay connection

### ISSUE THREAD

**Issue by ekosz** [mickhansen/graphql-sequelize#253]
I have a sequal model that looks like:

```js
export default (sequelize, DataTypes) => sequelize.define('Comment', {
  ...attrs,
}, {
  classMethods: {
    associate: models => {
      const { User } = models;

      Comment.User =
        Comment.belongsTo(User, { foreignKey: 'user_id', as: 'user' });
    },
  },
  schema: 'entity',  // <-- Its in its own schema
  tableName: 'checkin_answer_comments',
});
```

When I run a GraphQL query that looks like:

```
query {
  question(id:1) {
    answers {
      edges {
        node {
          comments(first:1) {
            commenter: user {
              id
            }
          }
        }
      }
    }
  }
}
```

Its generates the sql (*formatted by me*):

```sql
SELECT "Comment".*, "user"."id" AS "user.id", "user"."entity_id" AS "user.entityId", "user"."status" AS "user.status", "user"."permission_level" AS "user.permissionLevel", "user"."email" AS "user.email", "user"."name" AS "user.name", "user"."bio" AS "user.bio", "user"."avatar_file_name" AS "user.avatarFileName", "user"."started_at" AS "user.startedAt", "user"."phone_number" AS "user.phoneNumber", "user"."auth_id" AS "user.auth_id", "user"."company_id" AS "user.company_id" 
FROM (
            (SELECT "id", "entity_id" AS "entityId", "body", "created_at" AS "createdAt", "answer_id", "user_id", COUNT(*) OVER() AS "full_count" FROM "entity.checkin_answer_comments" AS "Comment" WHERE "Comment"."answer_id" = 4 ORDER BY "Comment"."id" ASC LIMIT 1) 
  UNION ALL (SELECT "id", "entity_id" AS "entityId", "body", "created_at" AS "createdAt", "answer_id", "user_id", COUNT(*) OVER() AS "full_count" FROM "entity.checkin_answer_comments" AS "Comment" WHERE "Comment"."answer_id" = 5 ORDER BY "Comment"."id" ASC LIMIT 1)
) AS "Comment" 
LEFT OUTER JOIN "2"."users" AS "user" ON "Comment"."user_id" = "user"."id"
```

This generates the error: 

```
"errors": [
    {
      "message": "relation \"entity.checkin_answer_comments\" does not exist",
      "locations": [
        {
          "line": 1,
          "column": 137
        }
      ]
    }
  ]
```

Notice what table it tries pulling the comment data from, `"entity.checkin_answer_comments"`. The correct query should be `"entity"."checkin_answer_comments"` with the schema and tableName separated.

Do you think this a graphql-sequilize bug? All other queries I've been running have worked like a charm. Its just when I added this `limit` did it call apart. Removing the `(first: 1)` produces a runnable query.

**Comment by mickhansen** [comment]
It's likely more of a Sequelize bug,

**Comment by ekosz** [comment]
Can you point me to the part of the code that would generate this kind of query so I can open up a bug report? I tried finding it myself, but had a bit of trouble tracing the code.

**Comment by ekosz** [comment]
@mickhansen This is still a big problem for me. I opened a pretty detailed issue in the Sequelize repo (https://github.com/sequelize/sequelize/issues/6131) but it hasn't gotten any attention. Do you have any advice on moving forward? I'm happy to try and fix it myself I just need some guidance on what to do.

**Comment by mickhansen** [comment]
@ekosz sorry about that, very busy atm, answered on the issue :)

**Comment by ekosz** [comment]
Fixed on master branch of sequelize
