### ISSUE TITLE
Automatically create Queries for Model

### ISSUE THREAD

**Issue by Glavin001** [mickhansen/graphql-sequelize#262]
Also see #263.

---

I'm still reading through the code to understand how things are working currently. I'll post back here once I know more.

### Features

- [x] Model to type, `modelType(model)`
  - Sequelize model to GraphQL type
  - [x] Uses `attributeFields`
  - [ ] Includes associations
- [x] Automatically create `findById` query
  - ~~Additional helper `findByIdQuery(model)`~~
- [x] Automatically create `findAll` query
  - ~~Additional helper `findAllQuery(model)`~~
- [x] `modelQueries` uses both `findByIdQuery` and `findAllQuery`
- [ ] Renaming queries
- [ ] Disabling queries
- [ ] Support Relay

### Usage

```javascript
import {resolver, modelQueries} from 'graphql-sequelize';

let User = sequelize.define('user', {
  name: Sequelize.STRING
});

let Task = sequelize.define('task', {
  title: Sequelize.STRING
});

User.Tasks = User.hasMany(Task, {as: 'tasks', resolver: { separate: true }});

// ==========================
// BEFORE

let taskType = new GraphQLObjectType({
  name: 'Task',
  description: 'A task',
  fields: {
    id: {
      type: new GraphQLNonNull(GraphQLInt),
      description: 'The id of the task.',
    },
    title: {
      type: GraphQLString,
      description: 'The title of the task.',
    }
  }
});

let userType = new GraphQLObjectType({
  name: 'User',
  description: 'A user',
  fields: {
    id: {
      type: new GraphQLNonNull(GraphQLInt),
      description: 'The id of the user.',
    },
    name: {
      type: GraphQLString,
      description: 'The name of the user.',
    },
    tasks: {
      type: new GraphQLList(taskType),
      resolve: resolver(User.Tasks, {
        separate: true // load seperately, disables auto including - default: false
      })
    }
  }
});

let schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'RootQueryType',
    fields: {
      user: {
        type: userType,
        // args will automatically be mapped to `where`
        args: {
          id: {
            description: 'id of the user',
            type: new GraphQLNonNull(GraphQLInt)
          }
        },
        resolve: resolver(User, {
          include: false // disable auto including of associations based on AST - default: true
        })
      },
      users: {
        // The resolver will use `findOne` or `findAll` depending on whether the field it's used in is a `GraphQLList` or not.
        type: new GraphQLList(userType),
        args: {
          // An arg with the key limit will automatically be converted to a limit on the target
          limit: {
            type: GraphQLInt
          },
          // An arg with the key order will automatically be converted to a order on the target
          order: {
            type: GraphQLString
          }
        },
        resolve: resolver(User)
      }
    }
  })
});

// ==========================
// AFTER
let UserQueries = modelQueries(User, {
  map: { // FIXME: Not sure how we want to do this part
    'findById': 'user', // Can use Model.name by default?
    'findAll': 'users'  // Pluralize Model.name by default?
  }
});

let schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'RootQueryType',
    fields: {
      ...UserQueries
    }
  })
});

```

**Comment by Glavin001** [comment]
I'm developing this locally within my project and then will bring it back into `graphql-sequelize` once I have finished.

If you have any feedback on features you want or how you expect/prefer the API to be, let me know ASAP! Thanks.

**Comment by mickhansen** [comment]
Your `after` does not seem very idiomatic to graphql, in my opinion the GraphQL API should be as focused to your frontend needs as possible and be much less generic.

**Comment by Glavin001** [comment]
> Your `after` does not seem very idiomatic to graphql, 

I agree, I don't like that much either.

> in my opinion the GraphQL API should be as focused to your frontend needs as possible and be much less generic.

My objective is at the very least be able to create GraphQL Types from the Sequelize models, including both attribute fields and association fields. I have already implemented code internally to accomplished this (hopefully something we can improve together and merge back into graphql-sequelize for others to use).
My next objective is to be able to generate Create-Read-Update-Delete queries and mutations, and allow the developer to disable or change them from within the Sequelize model's definition.
Furthermore, add additional custom queries and mutations, again to the model definition.

My biggest grievance with GraphQL to start was that I now had to keep the Model's Type in GraphQL in sync with the definition of my Model, such as Sequelize Model. The `attributeFields` function accomplished half the battle, and now I also have associations automatically generated, too. I am pleased with just this.
However, I want to investigate and discuss how we could make GraphQL queries and mutations easier, too.

---

I'm now looking at https://github.com/RisingStack/graffiti now.
They use `getSchema` to generate the final GraphQL schema.

So that would result in:

```javascript
import {getSchema} from 'graphql-sequelize';
// .... Load models into sequelize
let schema = getSchema(sequelize);
```

And instead of providing configuration of GraphQL later as some options, I think we should utilize the Sequelize model definition itself (needs much more thought):

```javascript
import {GraphQLNonNull, GraphQLString} from 'graphql';

let User = sequelize.define('user', {
  name: Sequelize.STRING
}, {
  classMethods: {
    // GraphQL Mutations
    mutations(/*...*/) {
      // Return mutations
    },
    // GraphQL Queries
    queries({User: UserType}, resolver) {
       // Add more queries that will be merged with the existing dictionary of queries
       return {
         customUserGraphQLQuery: {
           type: UserType,
           args: {
             arg1: {
               description: 'an argument to this GraphQL query',
               type: new GraphQLNonNull(GraphQLString)
             }
           },
           resolve: resolver(sequelize.models.User)
         }
       };
    }
  }
});
```

**Comment by brad-decker** [comment]
If this were to be a part of the core of graphql-sequelize it would need to be opt in not opt out. I see you have a "disable queries" checkbox above. I feel like disabled should be the default. Provide a model setup option that enables queries and perhaps provide a way to pass some parameters to customize the query output.

To be honest automatic query generation would help 0 in our current production graphql app. We need to be able to define custom arguments on most queries, and pass our own before and after. I also think that in order to be truly effective we'll need a way to define the type of a field within the field definition so that we can override the automatic generation of fields when we want to.

**Comment by Glavin001** [comment]
> If this were to be a part of the core of graphql-sequelize it would need to be opt in not opt out

Well, using the `getSchema` function would, of course, be opt in, since simply not using it would give the developer full control.
I think more to your point would be the individual queries and mutations generated, from using `getSchema`, such as generating the `findAll` and `findById` queries and create, update, delete mutations. I think it is fair to say these should all be opt in. A developer could then get started by passing their `sequelize` instance to `getSchema` and their model definitions should be needed to enable the applicable GraphQL Queries and Mutations that will be supported and generated automatically. After all, **we wouldn't want someone to have their data automatically accessible via GraphQL with a high level of control, without the developer explicitly saying so**.

> To be honest automatic query generation would help 0 in our current production graphql app.

The more I think about it the automatic queries and mutations may not be overly valuable. I believe the `viewer` query would be what is required at the very least, along with `Node` interface for Relay support, and then automatically generating the GraphQL types from the Sequelize models would be the most helpful. The difference from the current `graphql-sequelize` being that the current `attributeFields` only includes fields and not associations. I currently have GraphQL types being completely generated from Sequelize Models and this really provides the most value to me. If things change slightly it is quick to fix with changing Sequelize model definitions, however keeping GraphQL type definitions in sync with Sequelize models can become a little frustrating quickly.

I would understand if we all agree to close the automatically generated queries and mutations in favour of automatically generated GraphQL Types from Sequelize Models.

```javascript
import {getTypes} from 'graphql-sequelize';
// .... Load models into sequelize
let graphTypes = getTypes(sequelize);
let {User} = graphTypes; // Get GraphQL User type for Sequelize User Model
// User has both attribute and associations fields
```

**Comment by Glavin001** [comment]
See https://github.com/mickhansen/graphql-sequelize/issues/263#issuecomment-229730485

**Comment by Glavin001** [comment]
My repository work-in-progress: https://github.com/Glavin001/graphql-sequelize-crud

**Comment by Glavin001** [comment]
For anyone interested in this Issue, I have recently released a working version (passing tests) of the package.
GitHub: https://github.com/Glavin001/graphql-sequelize-crud
npm: https://www.npmjs.com/package/graphql-sequelize-crud
Let me know what you think!
