### ISSUE TITLE
Automatically create Mutations for Model

### ISSUE THREAD

**Issue by Glavin001** [mickhansen/graphql-sequelize#263]
Also see #262. 

I'm still reading through the code to understand how things are working currently. I'll post back here once I know more.

**Comment by brad-decker** [comment]
Again, would need to be opt in and I see these being even more niche than automatic queries. See my comment on #262

**Comment by Glavin001** [comment]
I'm going to make a separate package for this functionality. I see graphql-sequelize as providing some very useful helpers on top of Sequelize and what I want would be closer to an opinionated framework for developing GraphQL APIs with Sequelize behind the scenes. I makes sense to keep this enhanced functionality specific, especially since many users will not be using it.

I'm going to close this issue and will comment back here when I have another repository up. Thanks for your feedback!

**Comment by Glavin001** [comment]
My repository work-in-progress: https://github.com/Glavin001/graphql-sequelize-crud

**Comment by Glavin001** [comment]
For anyone interested in this Issue, I have recently released a working version (passing tests) of the package.
GitHub: https://github.com/Glavin001/graphql-sequelize-crud
npm: https://www.npmjs.com/package/graphql-sequelize-crud
Let me know what you think!
