### ISSUE TITLE
Add debug support

### ISSUE THREAD

**Issue by aweary** [mickhansen/graphql-sequelize#29]
How would you feel about adding support for https://github.com/visionmedia/debug?

I've found myself going in and ad-hoc adding `console.log` statements here and there to debug something and it'd be must easier if I could just run my app with `DEBUG=graphql:sequelize` or something and see whats happening.

**Comment by mickhansen** [comment]
All for it, i use it in a lot of personal products.

**Comment by Aweary** [comment]
:+1: I'll get a branch going. Any preference for the naming convention? Using terms like `graphql-sequelize:relay` and `graphql-sequelize:resolver` are the most clear, but pretty long.

**Comment by mickhansen** [comment]
`[packageName]:[moduleName]` is generally the convention i believe, it is a bit long but best to be predictable.

**Comment by Aweary** [comment]
:+1:
