### ISSUE TITLE
idFetcher only supports sequelize models

### ISSUE THREAD

**Issue by Aweary** [mickhansen/graphql-sequelize#30]
So looking at `idFetcher`

```js
export function idFetcher(sequelize) {
  return globalId => {
    let {type, id} = fromGlobalId(globalId);
    const models = Object.keys(sequelize.models);
    type = type.toLowerCase();
    if (models.some(model => model === type)) {
      return sequelize.models[type].findById(id);
    }
    return null;
  };
}
```

I've found that there's no way to fetch a GraphQL type that doesn't have an associated sequelize model. This is bad since Relay apps often use a pattern where a root `viewer` field points to all the other actual fields, making it a sort of virtual field that just acts as an access point.

**Comment by mickhansen** [comment]
We could provide a `ifNotModelCallback` or similar.
Wouldnt a root `viewer` be without an id? I use a root viewer in my current graphql setup and just return the current authenticated user.

**Comment by Aweary** [comment]
You just need to return an object with an `id` in the `viewer` resolve function. Currently this setup doesn't have any notion of users, so it just needs a  `viewer` field as an access point, since you can't have arrays as root nodes currently.

It totally works right now, but the issue is that Relay issues a `node` query with the ID when using `setVariables` instead of just calling `viewer` and the `idFetcher` is returning null.

I think maybe we can adjust `typeMapper` to allow for users to declare a type name and type without an associated model.

**Comment by mickhansen** [comment]
Ah hmm, can you link me to some relevant relay documentation on how they handler `viewer`?
As far as i can tell the user couldn't you just supply a full resolver to viewer instead of a partial one?
Or is it a partial resolve so it does not need to load the viewer unless specifically asked?

**Comment by Aweary** [comment]
`viewer` is non-standard and not part of the Relay spec, it's just a regular field. It's a workaround while root nodes are being worked on https://github.com/facebook/relay/issues/112

`viewer` just resolves to an object of type `viewerType` which has all main types as nullable fields.

**Comment by Aweary** [comment]
This all works well and fine, loading data is perfect. But Relay uses the `nodeInterface` when doing secondary queries (like updating a variable with `this.props.relay.setVariables`) so it passes the ID of `viewer` (which is the base64 encoding of `'viewer:1'`. `idFetcher` is invoked and it returns null because theres no `viewer` in the `models` list.

**Comment by mickhansen** [comment]
Allowing extensions to the type mapper would probably be a good idea in any case.

**Comment by mickhansen** [comment]
Will require a bit of refactoring of relay to support non-model types, but shouldn't be too tricky.

**Comment by Aweary** [comment]
We'll get on this one :+1:
