### ISSUE TITLE
attributeFields Helper Only Returns id Property

### ISSUE THREAD

**Issue by Sneagan** [mickhansen/graphql-sequelize#307]
`rawAttributes` returns the full model attributes as expected, but the `attributeFields` helper is simply returning:

```
{ id:
  {
    name: 'id',
    description: 'The ID of an object',
    type: GraphQLNonNull { ofType: [Object] },
    resolve: [Function: resolve]
  }
}
```

In case I've foolishly misconfigured something, here is the call:

```
const fields = graphqlSqlz.attributeFields(sequelizeDefinition, {
    exclude: [],
    only: [],
    globalId: true,
    map: {
      ProductId: 'productId'
    },
    allowNull: false,
    commentToDescription: false,
    cache: {}
  });
```

**Comment by Sneagan** [comment]
Appears to be the result of the unary operator `~` used in checking if the `only` and `excludes` arrays contain the current key. See [here](https://github.com/mickhansen/graphql-sequelize/blob/master/src/attributeFields.js#L10) and [here](https://github.com/mickhansen/graphql-sequelize/blob/master/src/attributeFields.js#L14). If these are changed to use the idiomatic `!== -1` instead, it appears to work as expected.

**Comment by mickhansen** [comment]
Supplying `only: []` is likely your issue here, we also don't publicly support having both exclude and only.

**Comment by Sneagan** [comment]
Both are present in the README section on `field helpers`,  as is the empty `[]` for `only`. I would recommend either updating those references to prevent this mistake or accepting #308 to prevent it. ;)

**Comment by Sneagan** [comment]
Resubmitting a fix that includes `~`

**Comment by Sneagan** [comment]
Can't seem to get around not using `~` while still allowing empty arrays. 

`!~[].indexOf(1) === true`

This is the issue and it's one of the reasons that `!== -1` is the preferred method. I highly recommend switching but will work around this bug.

**Comment by mickhansen** [comment]
@Sneagan I'll merge if you add a test case that shows a bug, promise :)
The README just shows all options, but only/exclude are definitely not meant together (i can see how you'd get to that assumption though).

**Comment by Sneagan** [comment]
I'll try to take a minute to write a test case this morning. The issue isn't even using both. It's a false positive on the presence of an element in an empty array. Although, I may also throw a warning in there if both `exclude` and `only` present.
