### ISSUE TITLE
Sequelize.VIRTUAL fields are incorrect unless dependent data is explicitly fetched 

### ISSUE THREAD

**Issue by LegNeato** [mickhansen/graphql-sequelize#32]
`Sequelize.VIRTUAL` fields don't seem to work correctly and data is undefined unless explicitly fetched.

Given a model like this:

    sequelize.define('User', {
      firstName: {
        type: Sequelize.STRING,
        allowNull: false,
      },
      lastName: {
        type: Sequelize.STRING,
        allowNull: false,
      },
      fullName: {
        type: Sequelize.VIRTUAL,
        get: function(): ?string { return `${this.firstName} ${this.lastName}`; },
      },
    }, {});

:point_right: And a row in the database with `firstName` = `Anonymous` and `lastName` = `Anonymous`.

With a GraphQL type of:

    var userType = new GraphQLObjectType({
      name: 'User',
      description: 'A person who uses the system.',
      fields: () => Object.assign(
        attributeFields(User),
        {
          id: globalIdField('User'),
        },
      ),
      interfaces: [nodeInterface],
    });

With a GraphQL query schema like this:

    users: {
      type: new GraphQLList(userType),
      resolve: resolver(User),
    },

Performing the following query:

    { users {
       id
       firstName,
       fullName,
    }}

:beetle::beetle::beetle: Incorrectly gives me: :beetle::beetle::beetle:

     {
        "data": {
          "users": [
            {
              "id": "VXNlcjox",
              "firstName": "Anonymous",
              "fullName": "Anonymous undefined"
            },
        ]
      }
    }
    
If I add `lastName` to the query fields:

    { users {
       id
       firstName,
       lastName,
       fullName,
    }}

It works correctly:

     {
        "data": {
          "users": [
            {
              "id": "VXNlcjox",
              "firstName": "Anonymous",
              "lastName": "Anonymous",
              "fullName": "Anonymous Anonymous"
            },
        ]
      }
    }

This seems like a pretty bad "bug" as you need to know the implementation of all `VIRTUAL` methods in order to make sure they return a valid value :crystal_ball: .

**Comment by mickhansen** [comment]
You need to use `new Sequelize.VIRTUAL(returnType, [dependencies ... ])`

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/blob/master/test/attributeFields.test.js#L83

**Comment by LegNeato** [comment]
Yeah, that's why I put "bug" in quotes. Is that documented anywhere? I actually just ran across it splunking in the code before reading your comment :smile:

**Comment by mickhansen** [comment]
Hmm, doesn't look like we have a test for VIRTUAL dependencies, only for VIRTUAL return type.
But tests act like documentation for the most part currently while we're still fleshing out APIs.

**Comment by LegNeato** [comment]
:+1: I'll look in there first next time!

**Comment by LegNeato** [comment]
Following up:

I replaced:

    fullName: {
      type: Sequelize.VIRTUAL,
      get: function(): ?string { return `${this.firstName} ${this.lastName}`; },
    },

With:

    fullName: {
      type: new Sequelize.VIRTUAL(Sequelize.STRING, ['firstName', 'lastName']),
      get: function(): ?string { return `${this.firstName} ${this.lastName}`; },
    },

And it worked great! :clap:

**Comment by mickhansen** [comment]
Super :) I've faced the issue myself. (I have a lot of custom boolean logic in virtuals, it was completely screwed).
