### ISSUE TITLE
Unable to use through query in connection for edge variable in sequelizeConnection

### ISSUE THREAD

**Issue by LegNeato** [mickhansen/graphql-sequelize#323]
It appears we are unable to use a through query in a connection. Perhaps I missed it? Using latest master.
## Context

In my system a `User` is associated with many`Companies` as Relay connections. One is the currently active company, specified as a flag (`isActive`) on a join/"through" table (`CompanyMembers`). 

I want clients to be able to query the `User`<->`Company` connection for all companies (for example, to show a list to switch between), only the active company, or only inactive companies via queries like:

``` js

fragment on Viewer {
  user {
    id,
    // (User fields...)
    memberships(isActive: true) {
      edges {
        cursor,
        isActive,
        node {
          ... on Company {
            id,
            name,
          }
        }
      }
    }
  }
}
```
## Issues
- The `where` option in `sequelizeConnection` is only given a key/value for the requested variable and only returns where options. The returned where options are run on the `target` given to `sequelizeConnection`. There appears to be no way to have them operate on the join/"through" table. Perhaps I missed it?
- I then tried to define a `before` option in `sequelizeConnection`, like:

``` js
before: (options, args) => {
  options.include = options.include || [];
  options.include.push({
    model: models.CompanyMember,
    through: {
      where: {
        isActive: !!args.isActive,
      },
    },
  });
  return options;
}
```

Which doesn't seem to work and throws a runtime error about the `where` option not being a function. Defining a fake `where` doesn't make it work either.

**Comment by mickhansen** [comment]
This might not be supported actually, open to an API proposal.

**Comment by LegNeato** [comment]
Ah, ok. I dug in a little bit more and think there may still be a bug?

My `target` is actually `CompanyMember` (the join/through table), so it would be reasonable to expect the `where` options to be run against `CompanyMember`'s table (what I need). But, they are in fact run on `Company`:
```js
ER_BAD_FIELD_ERROR: Unknown column 'Company.isActive' in 'where clause'
```

Which seems weird, because when I trace through parms given to `edgeFields`, it doesn't even show `Company` as the `node` or `source`:
```js
{
  cursor: 'xxxxxxxxx',
  node: {
   // CompanyMember Sequelize object
  },
  source: {
    // User Sequelize object
  }
}
```
I guess the where options are being run on the `Company` as the target of the connection, even though I specified the connection (`CompanyMember`) as the target? So something internal saw I specified a connection and automatically switched my specified target to the node at the end of the directed edge and operated on that, yet kept `node` in args given to `edgeFields` as the connection object?

If that behavior is expected perhaps a bug is that `node` in `edgeFields` args should have been switched to `Company` too? Wouldn't fix my use-case but would seem more consistent?

Keep in mind I don't really know how all these pieces fit together, so I may just be speaking jibberish 🔮 .

**Comment by mickhansen** [comment]
You might want to try targeting the relation between source and CompanyMember rather than the model directly, otherwise the results won't be scoped to the source.

**Comment by nikhildaga** [comment]
Facing the same issue @mickhansen  Can't we have options.include for join tables?

**Comment by mickhansen** [comment]
@nikhildaga As mentioned i'm not opposed to an API proposal.
