### ISSUE TITLE
Adding limit to list/connection returns empty array

### ISSUE THREAD

**Issue by chrissm79** [mickhansen/graphql-sequelize#337]
When I query a connection without any arguments I get back a full list of edges (no limit applied). However, if I query a connection that includes the first argument (i.e., `employees(first:3)`), it returns an empty array. Taking a look at the logs, I can see that the limit is being applied in the query.

Model:

```javascript
import User from '../user/user-model';

const Company = sequelize.define('company', {
  name: { type: Sequelize.STRING },
  domain: { type: Sequelize.STRING },
  createdAt: {
    type: Sequelize.DATE,
    field: 'created_at',
  },
  updatedAt: {
    type: Sequelize.DATE,
    field: 'updated_at',
  },
}, {
  tableName: 'companies',
  freezeTableName: true,
});

Company.sync();
Company.Employees = Company.hasMany(User, { as: 'employees' });

export default Company;
```

Type: 

```javascript
const fields = attributeFields(Company, {
  globalId: true,
});

const companyType = new GraphQLObjectType({
  name: 'Company',
  fields: assign(fields, {
    // Same issue here...
    // employees: {
    //   type: new GraphQLList(userType),
    //   args: {
    //     limit: { type: GraphQLInt },
    //   },
    //   resolve: resolver(Company.Employees),
    // },
    employees: {
      type: companyEmployeeConnection.connectionType,
      args: companyEmployeeConnection.connectionArgs,
      resolve: companyEmployeeConnection.resolve,
    },
  }),
  interfaces: [nodeInterface],
});

export default companyType;
```

Connection

```javascript
const { sequelizeConnection } = relay;

const companyEmployeeConnection = sequelizeConnection({
  name: 'companyEmployee',
  nodeType: userType,
  target: Company.Employees,
  connectionFields: {
    total: {
      type: GraphQLInt,
      resolve: ({source}) => {
        return source.countEmployees();
      },
    }
  },
});

export default companyEmployeeConnection;
```

```graphql
# returns empty array
{
  company {
    employees(last: 5) {
      edges {
        node {
          email
        }
      }
    }
  }
}

# returns all employees
{
  company {
    employees {
      edges {
        node {
          email
        }
      }
    }
  }
}
```

BTW, I don't usually work w/ Sequelize but this package is fantastic!

**Comment by mickhansen** [comment]
Sounds highly odd, we have quite a few tests for relay connection setups.
Can you post the SQL that you end up with? And what version of graphql-sequelize?

**Comment by chrissm79** [comment]
So I took a look at the tests and [it looks like](https://github.com/mickhansen/graphql-sequelize/blob/master/test/integration/relay.test.js#L120) it uses the `resolver` function to resolve a connection rather than using [sequelizeConnections](https://github.com/mickhansen/graphql-sequelize/blob/master/docs/relay.md#connections).

When using the resolver, it doesn't apply a `LIMIT`, it just looks for all records associated with the parent's id and (I assume) either `resolver` or `graphql` takes care of splicing the array to match the amount passed in the `first` argument (i.e., `employees(first:2)`).

When using `sequelizeConnections`, it looks like the `edges` object that's returned is always an empty array. However, it does properly apply the `LIMIT` to the fields (as well as unions nested connections).

So with the query below:

- Using the `resolver` function it gets every employee and all of their activities rather than limiting them to 2.
- Using the `sequelizeConnections` helper, it properly applies the limit, but always returns an empty array. In the case below, it won't make it down to the activities because employees returns `[]`.

```graphql
{
  company {
    name
    employees(first:2) {
      edges {
        node {
          email
          activities(first:2) {
            edges {
              node {
                createdAt
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by mickhansen** [comment]
Using relay connections via graphql-sequelize absolutely results in a query with a `LIMIT`, you can see this verified in tests - And it doesn't return an empty array if there's actually any results, also verified by tests.

I'm actually not at all sure what your issue is, a number of us are using this in production with great success.

Can you provide a copy-pasteable SSCCE or a failing integration test?

**Comment by chrissm79** [comment]
I was originally looking at the `relay.test.js` file, but the `connection.test.js` definitely cover this use case so I'm going to close the issue unless I can provide a reproducible example.

I'm using [Feathersjs](http://feathersjs.com/) and even though I'm using the sequelize models rather than the services feathers provides, I'm fairly certain that's likely the root cause for this.

Thanks @mickhansen!!

**Comment by chrissm79** [comment]
@mickhansen Found the issue... I'm working with a legacy DB which uses snake_case column names. I needed to add the `foreignKey` option when defining the `hasMany` relationship on the Company model. Either way it correctly queries the DB, however, without the `foreignKey` I was getting empty edges. 

Thanks again, love the package!

**Comment by mickhansen** [comment]
@chrissm79 Odd that you didn't get an SQL error, but yes that could cause an issue when our batching code tries to map stuff back.
