### ISSUE TITLE
Importing JSONtype is not supported

### ISSUE THREAD

**Issue by brad-decker** [mickhansen/graphql-sequelize#343]
@bringking @mickhansen 

Attempted to install https://github.com/taion/graphql-type-json to use for FormData mutation and ran into schema validation error:

```
Error: Schema must contain unique named types but contains multiple types named "JSON".
```

So did some snooping and found the JSONType that was created to support where clause, etc. I decided to just use that type but importing from graphql-sequelize/lib/types/jsonType causes the constructor to be fired again duplicating the type

I suggest you either namespace the type so that other users can use the fairly standard name "JSON" or make it exposed, but i'd almost err on the side of the first option.

**Comment by mickhansen** [comment]
PR welcome, to solve all this.
