### ISSUE TITLE
Order by multiple columns

### ISSUE THREAD

**Issue by manhhailua** [mickhansen/graphql-sequelize#356]
I have just realized that the `order` arguments which added by `defaultListArgs` can not be used for multiple columns (or I have not known how to do).

Expected syntax of variables:

```
{
  "order": [
    "createdAt",
    "reverse:updatedAt"
  ]
}
```

or as Sequelize default:

```
{
  "order": [
    ["createdAt", "ASC"],
    ["updatedAt", "DESC"]
  ]
}
```

**Comment by mickhansen** [comment]
Instead of relying on defaultListArgs i'd suggest you instead use an ENUM for defining order by.

**Comment by tobyhede** [comment]
@manhhailua I have a patch that does this if you need it https://github.com/mickhansen/graphql-sequelize/pull/438/

**Comment by iDVB** [comment]
+1 Is there a merged solution for this yet?

**Comment by cbravo** [comment]
My simple solution was to leverage the before option in the resolver as shown in the resolver tests (https://github.com/mickhansen/graphql-sequelize/blob/master/test/integration/resolver.test.js):

`import myModel from '../models/myModel';
 
 const listThings = {
   type: new ListType(thingsType),
   args: Object.assign(defaultArgs(myModel), defaultListArgs(), {
     orderBy: {
       type: new ListType(new ListType(StringType)),
     },
   }),
   description: 'Queries the things',
   resolve: resolver(myModel, {
     before: (opts, args) => {
       const options = Object.assign({ order: [] }, opts);
       if (args.orderBy) {
         options.order = options.order.concat(args.orderBy);
       }
       return options;
     },
   }),
 };
 
 export default listThings;`


and your query should look something like:

`{
  listThings(orderBy:[["field1", "DESC"], ["field2", "DESC"]]) {
    field1,
    field2,
    field3,
    field4
  }
}`

**Comment by manhhailua** [comment]
@cbravo : this can be a solution for now but I keep my opinion about improving current "order".
@mickhansen : there are current interests in this issue so I will keep myself on this. I hope another PR will be better my last one.

**Comment by pbrink231** [comment]
This would be great to improve the default order to include this.

I have a lot of tables and this would make working with tables server side easy.  I saw the reverse addition you made but really having an easy way to put asc or desc in the order field would be a much better way.  This also solves ordering by multiple columns in the way you think it should happen.

I think to make a non breaking change is to add orderBy as a default along with order.  You can either send in just the field name with order or you can do a more indepth ordering with orderBy.

Only thing I would add is to default "ASC" so you could send in 
`["field1"]`
`["field1", "field2"] `
`[["field1", "DESC"], "field2"]`
`[["field1", "ASC"],["field2", "DESC"]]`

**Comment by mickhansen** [comment]
Pretty sure `[["field1", "ASC"],["field2", "DESC"]]` is already supported @pbrink231, atleast for relay connections

**Comment by pexea12** [comment]
@mickhansen  No, it doesn't work with me. Only the first item of `order` is executed. The remaining ones are ignored.

**Comment by mickhansen** [comment]
@pexea12 Hm, that's odd, sure i have that working in my own project

**Comment by intellix** [comment]
Also suffering from this. Here's a screenshot of me trying to use multiple orderBy:
<img width="529" alt="Screenshot 2020-01-30 at 16 50 12" src="https://user-images.githubusercontent.com/1162531/73465398-a0bf7c00-4380-11ea-9254-ed16a3e00da3.png">

Generated query looks like:
```
Executing (default): SELECT ... FROM "ItemVariant" AS "ItemVariant" WHERE (("ItemVariant"."deletedAt" > '2020-01-30 15:50:41.882 +00:00' OR "ItemVariant"."deletedAt" IS NULL) AND "ItemVariant"."marketId" = 1) ORDER BY "ItemVariant"."availableAt" ASC, "ItemVariant"."id" ASC LIMIT 250;

```

**Comment by intellix** [comment]
I think this should be re-opened. Realised my patch was missing and was having this problem again. Re-applying my patch still works :)
