### ISSUE TITLE
resolver() changes association lookup behavior of findById()

### ISSUE THREAD

**Issue by csboling** [mickhansen/graphql-sequelize#358]
It appears that after calling `resolver(SomeModel)` on a model with associations, the associations are no longer present on the instance object produced by `SomeModel.findById(id, { include: [ AssociatedModel ] })`. `SomeModel.findOne({ where: { id: id }, include: [ AssociatedModel ] })` still works the same as before the `resolver()` call. That is,

``` js
SomeModel.findById(1, {
  include: [
    AssociatedModel,
  ],
})
  .then(instance => {
    chai.expect(instance.AssociatedModels).to.exist;
  });
```

succeeds before `resolver(SomeModel)` and fails afterwards when there is a `SomeModel.hasMany(AssociatedModel); AssociatedModel.belongsTo(SomeModel);` association in place.

[Here](https://github.com/csboling/graphql-sequelize-assoc-findById-issue) is a repository with a test case demonstrating the issue.

**Comment by mickhansen** [comment]
graphql-sequelize uses https://github.com/mickhansen/dataloader-sequelize

So there might be a bug in that it doesn't skip batching if there's an `include`, /cc @janmeier.

In any way you don't want to be using includes to provide nested data, are you using it as a form of ACL?

**Comment by janmeier** [comment]
Yeah, we need to skip the batching [here](https://github.com/mickhansen/dataloader-sequelize/blob/57962ae049d1b5081c3c43f058ef23e196a043af/src/index.js#L175) as well

**Comment by spathon** [comment]
Any updates on this? 

I just got the same issue which is causing the current application to fail if I use `graphql-sequelize` and `resolver`

**Comment by mickhansen** [comment]
@spathon None yet, PR welcome to address this (simple enough fix)
