### ISSUE TITLE
sequelizeConnection breaks with latest version of graphql

### ISSUE THREAD

**Issue by nikhildaga** [mickhansen/graphql-sequelize#369]
sequelizeConnection breaks with latest version of graphql (0.8) with error

```
Cannot read property '0' of undefined
```. 

Most probably due to these breaking changes:
https://github.com/graphql/graphql-js/releases/tag/v0.8.0

**Comment by nikhildaga** [comment]
Replacing `fieldASTs` with `fieldNodes` here: https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L348 fixes the issye

**Comment by mickhansen** [comment]
@nikhildaga PR welcome, we'll want to support multiple versions though.
