### ISSUE TITLE
How can we handle Date in graphql and sequelize?

### ISSUE THREAD

**Issue by jvbianchi** [mickhansen/graphql-sequelize#375]

**Comment by mickhansen** [comment]
However you like really.

**Comment by jvbianchi** [comment]
I end up using this solution https://github.com/graphql/graphql-js/issues/497

Thanks

**Comment by jedwards1211** [comment]
@mickhansen seems to me this package should be using custom scalars for dates and timestamps.  Would you accept a PR for that?  It would be a breaking change...

**Comment by jedwards1211** [comment]
At the very least I'm surprised that graphql-sequelize doesn't return dates as ISO 8601 strings.

**Comment by jedwards1211** [comment]
@mickhansen also considering that this package provides its own JSON scalar type, it's kind of odd that it doesn't provide types for all sequelize `DateType`s.

**Comment by intellix** [comment]
We have this: 
```ts
// ISO Dates for all Sequelize.Date fields
typeMapper.mapType(type => (type instanceof Sequelize.DATE ? DateType : false));
```

Don't remember where we got it, but the output is basically:
```
"user": {
  "createdAt": "2018-04-16T22:04:31.000Z"
}
```
