### ISSUE TITLE
Allow for connections on Viewer / Root node (Relay).

### ISSUE THREAD

**Issue by cdebotton** [mickhansen/graphql-sequelize#38]
First, I think the work you've done with this library is great, it's proven to be very helpful! I am, however, having an issue with the Relay portion of the code. As of right now, connections can only be made from models that have associations:

./src/resolver.js line 28
```javascript
    if (association && source.get(association.as) !== undefined) {
      if (isConnection(info.returnType)) {
        return handleConnection(source[info.fieldName], args);
      }
      return source.get(association.as);
```

and
./src/resolver.js line 71
```javascript
    if (association) {
      return source[association.accessors.get](findOptions).then(function (result) {
        if (isConnection(info.returnType)) {
          result = handleConnection(result, args);
        }
        return options.after(result, args, root, {
          ast: simpleAST,
          type: type
        });
      });
    }
```

The issue is that this constraint forces us to define the initial connection on the root viewer node as a GraphQL list (which I see done in the tests for relay.js in this library). Though this workaround works, it's inconsistent with how similar data is handled throughout the lib. Could you allow for connections to be attached directly to the root node? Thank you!

**Comment by mickhansen** [comment]
Relay does not currently have a way of solving connections on root, see: https://github.com/facebook/relay/issues/112

Viewer exists as a workaround, which we definitely support by resolving for a relation to the viewer.
For anonymous viewers we don't currently support connections (yet).

**Comment by cdebotton** [comment]
What I was hoping for was a solution to having connections on an anonymous viewer node, hoping to have some time later this week to fork and see what I can do!

**Comment by mickhansen** [comment]
I see, we don't support that at the moment but we definitely should.

**Comment by mickhansen** [comment]
There's increased support for connections in `v0.11.3`, please give it a go.

**Comment by cdebotton** [comment]
I upgraded to 0.11.4 and it doesn't seem to convert relay connectionArgs to proper Postgres queries.

Example:

types/userType:
```javascript
/* @flow */

import {
  GraphQLObjectType,
} from 'graphql';

import {
  connectionArgs,
  connectionDefinitions,
  globalIdField,
} from 'graphql-relay';

import {
  resolver,
  attributeFields,
} from 'graphql-sequelize';

import { User } from '../../models';

import type {
  ConnectionDefinition,
  RefsObject,
} from '../index';

export default (refs: RefsObject): ConnectionDefinition => {
  const type = new GraphQLObjectType({
    name: 'User',
    fields: () => ({
      ...attributeFields(User),
      id: globalIdField('User'),
      sessions: {
        type: refs.sessionConnection,
        args: connectionArgs,
        resolve: resolver(User.sessions),
      },
      stories: {
        type: refs.storyConnection,
        args: connectionArgs,
        resolve: resolver(User.stories),
      },
      storytellers: {
        type: refs.storytellerConnection,
        args: connectionArgs,
        resolve: resolver(User.storytellers),
      },
    }),
    interfaces: [refs.nodeInterface],
  });

  const defs = connectionDefinitions({
    name: 'User',
    nodeType: type,
  });

  return {
    type,
    connectionType: defs.connectionType,
    edgeType: defs.edgeType,
  };
};
```

queries/users:
```javascript
import { connectionArgs } from 'graphql-relay';
import { resolver } from 'graphql-sequelize';
import { User } from '../../models';

import type {
  RefsObject,
  QueryType,
} from '../index';

export default (refs: RefsObject): QueryType => ({
  type: refs.userConnection,
  args: connectionArgs,
  resolve: resolver(User),
});
```

GraphQL query:
```
query getStories {
	viewer {
    users(first: 9999) {
      edges { node { id } },
    }
  },
}
```

This generates the SQL query, `Executing (default): SELECT "id" FROM "Users" AS "User" LIMIT 1;`

And I get this as a return:
```
{
  "data": {
    "viewer": {
      "users": {
        "edges": null
      }
    }
  }
}
```

**Comment by mickhansen** [comment]
connectionsArgs handling does not exist yet: https://github.com/mickhansen/graphql-sequelize/issues/21
But it should definitely not be doing a LIMIT.

**Comment by mickhansen** [comment]
@cdebotton happy to fix but you'll likely have to provide a PR with a failing test.

**Comment by cdebotton** [comment]
I'll try to provide a PR with a failing test this weekend, thanks!

**Comment by mickhansen** [comment]
I've written a more full-featured connection proposal here: https://github.com/mickhansen/graphql-sequelize/blob/master/docs/relay.md

I'd love to support in-database ordering, slicing and paging - aswell as both association and model connection support.

**Comment by cdebotton** [comment]
Your proposal looks great, would be incredibly useful for a project I'm working on. I've hit a bit of a wall where I need to write a mutation that adds to a range of data (connection). I'm fine writing the server side mutation, but without connection support on the viewer node, I'm unable to really add that model to my dataset.

Do you still looking to have some tests written? Been struggling to find time but can hopefully take a crack at it later this week.

**Comment by mickhansen** [comment]
@cdebotton most of the stuff from the docs/relay proposal is now implemented.
I still need a good way to solve anonymous root nodes though, but i think we can solve it by having `target` possibly be a callback.

**Comment by mickhansen** [comment]
Implemented in the latest version, follow https://github.com/mickhansen/graphql-sequelize/blob/master/docs/relay.md

Use a model as a target and add a before method to filter
