### ISSUE TITLE
Better documentation for `defaultArgs` & `defaultListArgs`

### ISSUE THREAD

**Issue by legomind** [mickhansen/graphql-sequelize#381]
Examples:

- Order by DESC = order: 'reverse:columnName'
- Sequelize operators without dollar sign are mapped to equivalent sequelize operators (except $eq)

I will create a PR shortly.
Please comment with suggestions.

**Comment by mickhansen** [comment]
I've personally stopped using defaultArgs and defaultListArgs and i'm personally not sure it's a good idea to have them in this project.

I find that graphql should be more specific than generic, but that's just me :)
