### ISSUE TITLE
source param does not exist in sequelizeConnection.connectionFields

### ISSUE THREAD

**Issue by akaNightmare** [mickhansen/graphql-sequelize#384]
Hi All,

I have an issue with passing `source` variable to `sequelizeConnection` function (like https://github.com/mickhansen/graphql-sequelize/blob/e3ac7de1ec8180308f373b479c7332bef268228f/test/integration/relay/connection.test.js#L88) and the result.
http://screenshots.client-demo-site.net/scn-20161129-142802-mzfaz.png

Also I have found that `graphql-relay` does not exist the `source` param https://github.com/graphql/graphql-relay-js/blob/master/src/connection/connection.js#L111

So question is: what am I doing wrong?

Thanks you.

**Comment by mickhansen** [comment]
Not sure what you're doing wrong.

**Comment by akaNightmare** [comment]
@mickhansen so, another question, how I can get `totalCount`, if `source` unavailable?

**Comment by mickhansen** [comment]
That's more of a common coding/sequelize question i'd say, not strictly relevant to graphql-sequelize.
source should be available, i'd investigate why if i were you, but basically source just points to the association.

**Comment by otbe** [comment]
Sorry for asking in a closed issue, but I have the same problem.
Can source be undefined if the target is no association? 

Example code
```typescript
const usersConnection = relay.sequelizeConnection({
  name: 'users',
  nodeType: userType,
  target: User,
  connectionFields: {
    total: {
      type: GraphQLInt,
      resolve: async (e) => {
        console.log(e.source); // is undefined

        // this is the way I get the total number of users
        const s = await User.findAndCount();
        return s.count;
      }
    }
  }
});

let schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'RootQueryType',
    fields: {
      users: {
        type: usersConnection.connectionType,
        args: usersConnection.connectionArgs,
        resolve: usersConnection.resolve
      }
    }
  })
});
```
Is there a good place to start reading? Its really hard to dive into :/
