### ISSUE TITLE
Get additional attributes on belongsToMany models?

### ISSUE THREAD

**Issue by aimed** [mickhansen/graphql-sequelize#386]
I'm trying to define a belongsToMany relationship with additional attributes (e.g. customerRef) on the model (CompanyCustomer). The only way i could figure out to get the additional attribute and add it to the edge was setting 'include'. But this disables the request batching by dataloader.
Is there any way we can support this? Or is there already a way this is supported?

```javascript
const companyCustomerConnection = sequelizeConnection({
  name: 'companyCustomers',
  nodeType: companyType,
  target: Company.Customers,
  before: (options) => {
    options.include = [{association: Company.Customers, through: {attributes: ['customerRef']}}];
    return options;
  },
  edgeFields: {
    customerRef: {
      type: GraphQLString,
      resolve: (edge) => edge.node.dataValues.CompanyCustomer.customerRef
    }
  }
});
```

**Comment by juliocanares** [comment]
@mickhansen  any suggestion on this?

**Comment by yishus** [comment]
+1 i'm also trying to understand how to get additional attributes from the join table to be in the result

**Comment by MrStLouis** [comment]
+1 on this. Would love to know the best way to do this. I am currently using a separate resolver for each separate column which seems like overkill

**Comment by MrStLouis** [comment]
following the advice here https://stackoverflow.com/questions/48957191/how-do-i-orm-additional-columns-on-a-join-table-in-sequelize I refactored my schema to use this join table instead as a one-to-many with the original tables. The only difference now is that the data on my original join table is where I want it but the linked data is now nested in another object as it required one more resolver to get. Is this ideal? maybe. I believe it follows closer to 'best practices' and allows sequelize to keep doing it's magic without me intervening.

**Comment by mickhansen** [comment]
I don't currently have a great idea on how to solve this, ideas welcome.

**Comment by mickhansen** [comment]
Should `status` for `payers` of a `transaction` be an edge field, if it's not directly related to the payer but the link between them?

**Comment by RoelRoel** [comment]
This is the moment that will allways come when you try all these fancy magic tools to save time.. After a few days you see the limitations and you regret that you just don't write the queries yourself....

It is not a rare use case to get the field of a link table!
I hoped sequelize would merge it with the linked table result.
