### ISSUE TITLE
Permission on specific fields 

### ISSUE THREAD

**Issue by shakaIsReal** [mickhansen/graphql-sequelize#387]
@mickhansen 

 Hi thanks for the library!  In my case users can block each other. If a users is blocked, he can't view specific fields such as: `email` and `birthday`. And if client requested `isBlocked` field, it should return true or false. 

 I though of 2 ways to do it. 

1.  Use before function in `resolver(Model, { before: function() { ... } })` to check if the user is blocked and remove `email` and `birthday` from the query. Then somehow push `isBlocked` inside the result, so it can be used inside `UserType`'s `isBlocked` field. But I don't know if that's even possible. 

2. Check this logic in the `UserType` in resolve function of each field. However this means that I would be making 2 queries for the same permission check and 1 more for `isBlocked` field. So 3 queries overall...  

I think option 1 seems perfect. If you think it is, I would like an example for implementation. If not, should I use dataloader with option 2 instead? 

NB: before I tried join-monster, and faced the same problem. 

Thanks.

**Comment by mickhansen** [comment]
Option 1 as you mention suffer from not being cacheable or being batchable.
We've been using Option 1 for a while but slowing moving to having ACL in field specific resolvers.

**Comment by shakaIsReal** [comment]
You mean something like this https://www.npmjs.com/package/acl. Storing roles in redis for speed, and keeping `isBlocked` as a list for each user. But this still means making multiple requests, unless using dataloader for batching. Could you please give a rough idea of implementation?

**Comment by mickhansen** [comment]
I wasn't implying how you would do the ACL check, just that you would do it after loading the user.
If you have the information necessary to filter of fields before the query you'll have it after too.

**Comment by shakaIsReal** [comment]
@mickhansen So you do ACL after loading all of the data for specific user in fields' resolvers?

**Comment by mickhansen** [comment]
In the cases where we do field specific ACL, we do it in the field resolvers yeah.

**Comment by shakaIsReal** [comment]
If I put ACL logic (in my case checking if user is blocked) inside dataloader and use it in multiple fields's resolve functions of `UserType`. Will it batch these requests into one?

**Comment by mickhansen** [comment]
If your ACL can be expressed in pure SQL that might work, but sounds mighty complex

**Comment by shakaIsReal** [comment]
@mickhansen  Hahaha.. yeah. As you mentioned, you can't really do ASL that is needed for more than one field inside the actual type. I guess the most viable way is to use Option 1, and push data for ACL (`isBlocked: true`) into an array that is returned by sequelize, so it can be used in specific fields.  This seems sad, coming from REST :D

**Comment by mickhansen** [comment]
I don't have any examples, as i said i advise doing post fetch ACL so you can have very simple caching and batching for your resource lookups.

**Comment by shakaIsReal** [comment]
@mickhansen  Thanks, I decided that I'll use https://www.npmjs.com/package/graphql-rule on top.

E.g.  
```
resolve: (_, args, { session }) => resolver(User).then((data) => {   
const securedUser = new UserRule(data, session);
          return securedUser;
})
```

Yet still the data that is being fetched from the database is controlled by the client. It would be awesome if your library could handle this, so developers have control over what data is being fetched in the first place. I kind of like the modal idea in graphql-rule, so maybe we could apply something similar? 

👍

**Comment by mickhansen** [comment]
This library will not support pre-fetch ACL as post-fetch ACL fits the direction graphql is going much better (batching, etc)

**Comment by shakaIsReal** [comment]
By "post-fetch ACL" you mean after the data has been loaded from database?

**Comment by tyscorp** [comment]
@mickhansen How does post-fetch ACL work with pagination? Let's say you request the `first: 10`, but the post-fetch ACL determines the client doesn't have access to 5 of them. Do we return just the 5 the client has access to, or run another query getting another 5 and hope the client has access to them all?

**Comment by mickhansen** [comment]
@shakaIsReal Yes, what i've been commenting on the last few times :)
@tyscorp We're been talking about type-field ACL here, so it doesn't necessarily apply to connections.

For connections we're definitely still using in-query ACL, connections aren't exactly a ripe case for batching either, single node lookups is the most easy to reason about.

**Comment by shakaIsReal** [comment]
@mickhansen  #295
