### ISSUE TITLE
Can't access belongsTo/hasOne/any non connection associated off of an association

### ISSUE THREAD

**Issue by cdebotton** [mickhansen/graphql-sequelize#39]
Here is my sample query:

```
query getStories {
	viewer {
  	stories(limit: 15) {
    	title,
	storyteller {
      	firstName,
        lastName,
        stories(first: 15) {
         edges {
            node {
              title,
              user {
                id,
              },
            },
          },
        },
      },
    },
  },
}
```

Once I access the user id off of the story model, I receive the GraphQL error  "column storyteller.stories.user does not exist". I've tried several variations on this setup, and it seems that when I have a connection, related models that are not in connections off of a node in said collection is queried for incorrectly. I can see the log in my terminal as:

```mysql
Executing (default): SELECT "Story".*, "storyteller"."firstName" AS "storyteller.firstName", "storyteller"."lastName" AS "storyteller.lastName", "storyteller"."id" AS "storyteller.id", "storyteller.stories"."id" AS "storyteller.stories.id", "storyteller.stories"."title" AS "storyteller.stories.title", "storyteller.stories"."user" AS "storyteller.stories.user" FROM (SELECT "Story"."title", "Story"."id", "Story"."storytellerId" FROM "Stories" AS "Story" LIMIT 15) AS "Story" LEFT OUTER JOIN "Storytellers" AS "storyteller" ON "Story"."storytellerId" = "storyteller"."id" LEFT OUTER JOIN "Stories" AS "storyteller.stories" ON "storyteller"."id" = "storyteller.stories"."storytellerId";
```

It seems as though graphql-sequelize doesn't recognize related models off of a connection node unless it is also a connection. Strangely, I can see in lib/relay.js that associations are handled differently when not a connection, so I'm not sure what the problem actually is.

**Comment by mickhansen** [comment]
Can you add the sequelize relation, the resolver setup, etc?
It should just work but something might be buggy.

**Comment by cdebotton** [comment]
Upgrading to 0.11.4 totally fixed this issue. I can still show you the sample setup if you'd like to see though.

**Comment by mickhansen** [comment]
I just faced a similar issues and found a few things missing with connections so that might have fixed it.

**Comment by cdebotton** [comment]
Great, thanks! I found this package and it's a perfect fit for a project I'm working on. Really great work!
