### ISSUE TITLE
belongsToMany: TypeError: Cannot read property 'getTableName' of undefined

### ISSUE THREAD

**Issue by gutenye** [mickhansen/graphql-sequelize#395]
Given

```
const Post = sequelize.define('post')
const Tag = sequelize.define('tag')
const PostTag = sequelize.define('post_tag')

Post.Tags = Post.belongsToMany(Tag, {through: PostTag})
Tag.Posts = Tag.belongsToMany(Post, {through: PostTag})

resolver(Post.Tags)

Post.findOne({id: 1}).then(post => post.getTags({limit: 1}))
```

Got `TypeError: Cannot read property 'getTableName' of undefined` error

Works if you remove `resolver(Post.Tags)` patch.

**Comment by mickhansen** [comment]
Assuming you're using a newer version it's likely related to the monkey patching that https://github.com/mickhansen/dataloader-sequelize does

**Comment by gutenye** [comment]
@manhhailua Thanks for the hint, I try to make a fix at https://github.com/mickhansen/dataloader-sequelize/pull/18
