### ISSUE TITLE
Examples for sequelize operators usage in graphql

### ISSUE THREAD

**Issue by sudheerj** [mickhansen/graphql-sequelize#396]
I'am doing R&D for sequelize operators usage in graphql queries.Can you please provide any sample to workout on different kind of operators or where clause usage.This feature is not supported in graphql directly.Is it Graphql-sequelize provide these things? Any help is appreciated.

https://github.com/graphql/graphql-js/issues/640

**Comment by mickhansen** [comment]
I'm not sure what you're asking, please provide some pseudo schema code on what you want to achieve

**Comment by sudheerj** [comment]
For example how we can write graphql query for below kind of JSON requests.The filter section has lot of operators and not sure how we can send them from Graphql query.

{
"fields": [
"account_name",
"account_number",
],
"filters": {
"region": "APAC",
"ibx_presence.ibx_code": {
"$in": [ "HK1", "SG1" ]
},
"account_number": {
"$nin": [ "1" ]
}
},
"sort": [
        {
            "field": "account_number",
            "sort_type": -1
        }
    ]
"skip": 0,
"limit": "200",
"countonly": false
}

I can handle sort,skip,limit,countonly fields as below 

query RootQuery {
    accounts(skip: 0,limit: 3,sort_field: "account_number",sort_order: "descending"){
       account_number,
       account_name,
       ......
       ibxes {
         ibx_code
       },
       region
    }
}

**Comment by mickhansen** [comment]
In my opinion you should be much less generic with what you offer in your graphql queries, i think you should have a much tighter contract rather than leak the internals, so i can't really provide you with any examples on how to implement that.

**Comment by sudheerj** [comment]
Do you mean that we can't handle these kind of JSON requests from Graphql queries? If Graphql/Graphql-sequelizejs won't support these kind of operators then only the possibility i can see as passing db schema directly as key-value pair.

**Comment by mickhansen** [comment]
You can in theory, i'm saying i don't think it's a good idea so i don't have any examples of how to do it.
graphql-sequelize has the where arg: https://github.com/mickhansen/graphql-sequelize/blob/master/src/defaultArgs.js#L18 but i don't even like that much.
