### ISSUE TITLE
Support for relay global ids

### ISSUE THREAD

**Issue by idris** [mickhansen/graphql-sequelize#41]
Because `attributeFields` defines the `id` field with a non-null Int (or whatever the primary key is), I always have do this in my GraphQLObjectTypes to get it to play nice with Relay:

```js
  fields: _.assign(attributeFields(MyModel), {
    id: globalIdField('MyModel'),
    _id: {
      type: GraphQLInt,
      resolve: model => model.id,
    },
  }),
```

This is repeated code, and I'd like to get rid of it.  If there's no current way to do this, I'd be willing to make a pull request with a proposed solution.

**Comment by mickhansen** [comment]
Why would you want `_id` in this case?

**Comment by idris** [comment]
I guess the `_id` is optional.  I use it because I have some legacy code that hits REST endpoints from the front-end, which require the real id.

**Comment by mickhansen** [comment]
Alright, i would be willing to accept a PR that offers a `map` option to attributeFields that renames fields defined in a key: rename map.

**Comment by idris** [comment]
What about built-in relay support that does the globalIdField part for you?

**Comment by mickhansen** [comment]
I think i discussed this with @brad-decker but there was some argument against it.
But yeah a `globalId: true` (suggestions welcome) argument or similar that generates a globalIdField on the Model.name would be fine with me (i could use that actually).

**Comment by brad-decker** [comment]
I'm fine with providing an argument to the attributeFields function to swap out the typical id in generation in favor of globalid. Just to note that the globalIdField parameter will be the name of the model which is the typical behavior that we are all implementing anyways. Good idea. :+1:
