### ISSUE TITLE
MySQL full_count not propagated

### ISSUE THREAD

**Issue by toxsick** [mickhansen/graphql-sequelize#417]
Hi everybody,

we are using graphql-sequelize with MySQL. A while ago #255 added full_count support for relay connections with MySQL. We are using connection arguments to implement search functionality. The full_count variable represents the total number of results matching the search. This is crutial information we want to display in the frontend. However I think there is currently no way to access this information outside of the relay connection implementation here:

https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L303-L310

Is there a way to access the full_count for MySQL, without out performing another extra count query?

regards Hannes

**Comment by mickhansen** [comment]
Currently not, but no reason we couldn't add it to: https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L332

**Comment by toxsick** [comment]
@mickhansen yes that is what I thought. So we should add a `fullCount` to the object passed to the after hook?

I can create a pr for that.

regards Hannes

**Comment by mickhansen** [comment]
@toxsick that should be sufficient yeah
