### ISSUE TITLE
Reverse ordering

### ISSUE THREAD

**Issue by idris** [mickhansen/graphql-sequelize#42]
Is there currently any way to do reverse ordering using the `order` attribute?

If not, what about something like `order: "reverse_fieldname"` to order DESC?
(got that idea from [Facebook's Graph API](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.5#ordering))

**Comment by mickhansen** [comment]
Not possible currently, i would prefer `reverse:fieldname` if legal in graphql since that is less likely to a be a legal sql field name.
