### ISSUE TITLE
dataloader VS include

### ISSUE THREAD

**Issue by thifranc** [mickhansen/graphql-sequelize#424]
Hi ! First thanks for your amazing job !  
  
I have a performance issue,  
I see that 'graphql-sequelize' use dataloader for performance issues, but due to this, when I query something like :  
```
{user (login:"thibault"){id, user_accessRef{access, access_id, accessRef{id, name, parent}}}}
```
I get three successive DB calls : the logs would be :  
```
SELECT "id", "login", "firstname", "lastname", "password" FROM "users" AS "users" WHERE "users"."login" = 'thibault' LIMIT 1;
SELECT "id", "access", "users_id", "access_id" FROM "users_access" AS "users_access" WHERE "users_access"."users_id" IN (1) ORDER BY "users_access"."id" ASC;
SELECT "id", "name", "parent" FROM "access" AS "access" WHERE "access"."id" IN (1, 2, 3, 4);
```
That appears to me as counter-productive as when I execute a similar query via sequelize :  
```
userModel.findOne({
      where : {login: 'thibault'},
      include: [
              {model: user_accessModel, as: user_accessRef, include: [{model: accessModel, as: accessRef}]}
              ]
    })
```
I get only one DB call : where the log would be :  
```
SELECT "users".*, "user_accessRef"."id" AS "user_accessRef.id", "user_accessRef"."access" AS "user_accessRef.access", "user_accessRef"."users_id" AS "user_accessRef.users_id", "user_accessRef"."access_id" AS "user_accessRef.access_id", "user_accessRef.accessRef"."id" AS "user_accessRef.accessRef.id", "user_accessRef.accessRef"."name" AS "user_accessRef.accessRef.name", "user_accessRef.accessRef"."parent" AS "user_accessRef.accessRef.parent"
FROM (
	SELECT "users"."id", "users"."login", "users"."firstname", "users"."lastname", "users"."password" FROM "users" AS "users"
		WHERE "users"."login" = 'thibault' LIMIT 1
) AS "users"
	LEFT OUTER JOIN "users_access" AS "user_accessRef" ON "users"."id" = "user_accessRef"."users_id"
	LEFT OUTER JOIN "access" AS "user_accessRef.accessRef" ON "user_accessRef"."access_id" = "user_accessRef.accessRef"."id";
```

So here's my question :  
do you think that definitely dataloader is more effective and I should rely on those 3 DB calls, hoping that with the amount of DB calls coming in production, dataloader would be able to do its magic and batch efficiently ?  
Or should I stick to use sequelize and favour 1 DB call ?  
I've seen that according to you, I should favour dataloader, and that's why we get :  
```
Include support has been removed in favor of dataloader batching
```
When trying to include in options inside graphql queries, but I don't see why.

**Comment by mickhansen** [comment]
Deduplication in Sequelize is very expensive, so generally you should see speed ups with batching.
The big win is generally reasoning about your code, you can fetch data where you need it and not care about performance (especially when we implement per query caching).

**Comment by janmeier** [comment]
We actually did some pretty extensive testing on this before switching over, see https://gist.github.com/janmeier/239b764779edc51bad35f547e992a01a

The problem is that almost all includes produce some kind of cartesian product - which is _very_ heavy to deduplicate in sequelize (there's a reason they say you shouldn't do anything CPU intensive in node :) )

**Comment by thifranc** [comment]
Thanks a lot for your rapidity and clarity of answer ! I'll keep going with batching then
