### ISSUE TITLE
Use of 'this' (instead of const) for models.

### ISSUE THREAD

**Issue by Extra-lightwill** [mickhansen/graphql-sequelize#425]
I'm wondering the reason behind why this library uses:

`this.User = sequelize.define('user', {}, {timestamps: false})`;

instead of something like:

```
const User = sequelize.define('user', {etc.},);
```

This is not criticism, I'm curious because I would like to use it in my application so an explanation would really help clear things up for me.  

Thanks :)

**Comment by mickhansen** [comment]
@Extra-lightwill Can you link some specific code?

**Comment by Extra-lightwill** [comment]
@mickhansen I was looking in the test folder e.g. https://github.com/mickhansen/graphql-sequelize/blob/master/test/unit/relay/connection.test.js 

I tried using without 'this' in a mock application for testing and got this error. 
```
TypeError: (0 , _graphqlSequelize.sequelizeConnection) is not a function
    at Object.<anonymous>
```

So I'm not sure what I'm doing wrong?

**Comment by Extra-lightwill** [comment]
My models: 

```
import Sequelize from 'sequelize';
import Conn from '../connection';

const Task = Conn.define('task', {
	id: {
        type: Sequelize.BIGINT,
        primaryKey: true,
        autoIncrement: true
    },
	title: {
		type: Sequelize.TEXT, 
	},
});

export default Task;

import Sequelize from 'sequelize';
import Conn from '../connection';

const User = Conn.define('user', {
	id: {
        type: Sequelize.BIGINT,
        primaryKey: true,
        autoIncrement: true
    },
	username: {
		type: Sequelize.TEXT, 
	},
});

export default User;
```

Relationships between models:

```
import Sequelize from 'sequelize';
import { sequelizeConnection } from 'graphql-sequelize';

import User from './models/UserModel';
import Task from './models/TaskModel';

//-----RELATIONSHIPS-----//

User.Tasks = User.hasMany(Task, {
    foreignKey: 'user_id',
    as: 'tasks',
});

Task.User = Task.belongsTo(User, {
    foreignKey: 'user_id',
});


export {
    User,
    Task,
 
};



```

**Comment by mickhansen** [comment]
It doesn't really matter, you can see other tests using const aswell, it's an old habit ensuring everything is scoped to the test

**Comment by Extra-lightwill** [comment]
@mickhansen ah i see. 

However, including this: 

```
 const viewerTaskConnection = sequelizeConnection({
        name: 'viewer' + Task.name,
        nodeType: taskType,
        target: User.Tasks,
      });
```

in my schema causes the error that I mentioned above```
 TypeError: (0 , _graphqlSequelize.sequelizeConnection) is not a function
    at Object.<anonymous> 
``` - what do I need to do to fix this?

**Comment by Extra-lightwill** [comment]
@mickhansen in answer to 'In a real world it's a defunct question since you'd hardly ever create models like we do unless you're specifically testing a sequelize plugin of sorts.' 

But if you're creating tables, say, in a MySQL database, what way would you do it?

**Comment by mickhansen** [comment]
@Extra-lightwill sounds like an import error? Not related to how you define models at all.

> But if you're creating tables, say, in a MySQL database, what way would you do it?

there are a few ways express in the sequelize repository and issues, not graphql related.

**Comment by Extra-lightwill** [comment]
@mickhansen  Hm, I can't figure out what's going wrong - I've created a repo demonstrating the issue here: https://github.com/Extra-lightwill/graphql-sequelize-repo-test

npm install
npm start 
localhost:4444 (when error isn't thrown)

viewerTaskConnection is defined in the schema.js file: https://github.com/Extra-lightwill/graphql-sequelize-repo-test/blob/master/server/data/schema.js

sql db settings: https://github.com/Extra-lightwill/graphql-sequelize-repo-test/blob/master/server/data/db/connection.js 

I'd be very grateful if you could very quickly take a look at what is happening and advise how to adjust accordingly.

**Comment by Extra-lightwill** [comment]
Update: i seem to have fixed it by doing this. as you said it was a problem with the import statements.

```
import { relay } from 'graphql-sequelize';
const { sequelizeConnection } = relay;
```
