### ISSUE TITLE
relay: after hook misses context and info

### ISSUE THREAD

**Issue by majodev** [mickhansen/graphql-sequelize#426]
Hi!

See [here](https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L332). I think the outer `.after` handler should also receive the respective `context` and `info` arguments, possibly with the typical resolve function signature: `(result, args, context, info) => result`.

Cheers.

**Comment by mickhansen** [comment]
Yeah, that makes sense.

**Comment by majodev** [comment]
Perfect. Pull --> https://github.com/mickhansen/graphql-sequelize/pull/427
