### ISSUE TITLE
Nested associations don't pass includes

### ISSUE THREAD

**Issue by LoneWolfPR** [mickhansen/graphql-sequelize#428]
I have a schema with a lot of relationships defined both in the schema itself and the models. It appears though, that defined includes don't work when a nested graphql call is made. Here's an example:
```
contact(id:1234) {
  id
  firstname
  lastname
  roles {
    account__c
  }
}
```

The above works just fine. I'm calling the contact directly with a passed ID. The roles sub object populates just fine. However, if I do the following there is a problem:
```
{
  user(id:1) {
    contact {
      id
      firstname
      lastname
      roles {
        account__c
      }
    }
  }
}
```

The contact record under user loads fine and is the same contact record as in the first example. However, the roles object within the contact record comes back null. If need be can put in some of my model and resolver code. The type definitation and resolver is pretty simple. I have it defined like this:
```
const typeDefinitions = `
type Contact {
  id: Int!
  lastname: String
  firstname: String
  roles: [Role]
  user: User
}

type ContactResponse {
  contact: Contact,
  errors: [String]!
}`;

const resolvers = {
  Query: {
    contacts (root, args, context) {
      return contactRepo.findAll(args);
    },
    contact (root, args, context) {
      return contactRepo.findById(args);
    },
  },
  Contact: {
    roles (contact) {
      return contact.Roles;
    },
    user (contact) {
      return contact.User;
    },
  },
  Mutations: ...
}
```

Is there something basic I'm missing to bring the defined sequelize includes from a find into the nested associations?

**Comment by mickhansen** [comment]
Your find calls don't have any includes

**Comment by LoneWolfPR** [comment]
My findById does. Is there a different find call that is used when pulling in relationships like this?

**Comment by mickhansen** [comment]
I don't see any in your code, but i don't see your User resolver either

**Comment by LoneWolfPR** [comment]
Oh, right. I forgot to include the code. So, it's a bit convoluted. Basically I'm using a repository pattern. The contactRepo you see in my resolver is calling the findById in the parent AbstractRepository. Each child repository defines the includes it should be using.

Here's the abstract repository
```
import db from '../models';

export default class AbstractRepository {
  constructor (model, include = null) {
    if (new.target === AbstractRepository) {
      throw new TypeError('Cannot construct AbstractRepository instances directly.');
    }
    this.model = model;
    this.include = include;
  }
  findById (args) {
    return db[this.model].find({
      where: { id: args.id },
      include: this.include,
    });
  }
}
```

And here's the contact repository
```
import db from '../models';
import AbstractRepository from './AbstractRepository';

export default class ContactRepository extends AbstractRepository {
  constructor () {
    super('Contact', [db.User, db.Role, db.Classroom]);
  }
}
```
So, when a new instance of contact repository is created it passes the model and includes up to the parent. Then when findById is used it includes the array of models passed in the constructor.

Hopefully that all makes sense.

**Comment by LoneWolfPR** [comment]
Also, my user resolver just looks like this:
```
const resolvers = {
  Query: {
    users (root, args, context) {
      return userRepo.findAll(args);
    },
    user (root, args, context) {
      return userRepo.findById(args, context);
    },
  },
  User: {
    contact (user) {
      return user.Contact;
    },
    student (user) {
      return user.Student;
    },
  },
  Mutation: ...
}
```

**Comment by LoneWolfPR** [comment]
Ok. I figured it out. I just have to define my full set of nested includes in my repository.

**Comment by mickhansen** [comment]
@LoneWolfPR Unless you use something that figures out your includes based on the requested AST. But i would suggest going the dataloader route instead (which is built into graphql-sequelize)
