### ISSUE TITLE
relay.sequelizeConnection: Add a function to resolve `target` dynamically

### ISSUE THREAD

**Issue by janmeier** [mickhansen/graphql-sequelize#431]
Right now a relay connection can only resolve data from a single sequelize model. It should be able to resolve it dynamically, per request, from a function instead.

Currently we are migrating some tables, and while the migration is going on the connection should read from the old table in some cases, and from the new table in other cases. 
The current solution for us is to have two connections while are completely identical, except for the `target`, and then call `resolve` on the correct connection. It would be nice to be able to encapsulate this logic inside the connection instead

**Comment by teoboley** [comment]
Is there any way to define a connection without a target at all?  My use case is quite similar to this, except my parent graphql type is not a sequelize model, I'm simply trying to find a way to do a paginated query of my sequelize model from this non-sequelize parent type.

**Comment by mickhansen** [comment]
@teoboley Not currently, graphql-sequelize would need to know what model to query against in either case
