### ISSUE TITLE
How to query with associations? 

### ISSUE THREAD

**Issue by ivanzhaowy** [mickhansen/graphql-sequelize#432]
Hi, I have a 1:M association like this: 

```JavaScript 
const Author = sequelize.define('authors', {
  id: {
    type: Sequelize.STRING,
    primaryKey: true,
    autoIncrement: true
  },
  name: {
    type: Sequelize.STRING,
    allowNull: false
  }
};


const Book = sequelize.define('books', {
  id: {
    type: Sequelize.STRING,
    primaryKey: true,
    autoIncrement: true
  },
  title: {
    type: Sequelize.STRING,
    allowNull: false
  }
};

Author.hasMany(Book);
Book.belongsTo(Author);
```

Then I defined GraphQL types with the helpers from graphql-sequelize. How to query books with condition like this? 

```
query {
  books(where: { author: { id: 1} }) {
    title
  }
}
```

**Comment by janmeier** [comment]
Please show your graphql code as well - If you have any, or are you asking how to do this with grahpql-sequelize? In case of the latter, have a look at the relay documentation https://github.com/mickhansen/graphql-sequelize/blob/master/docs/relay.md
