### ISSUE TITLE
Why data-loader over table join?

### ISSUE THREAD

**Issue by itaied246** [mickhansen/graphql-sequelize#433]
I have looked a little in the source code of the `resolver` and found this:
`'Include support has been removed in favor of dataloader batching'`

Why did you choose to use `data-loader` instead of `sequelize` include and joins?
Wouldn't it be more efficient to use table joins?

**Comment by janmeier** [comment]
https://github.com/mickhansen/graphql-sequelize/issues/424

**Comment by janmeier** [comment]
Joins may be more efficient db wise, but processing the Cartesian product that results from the join is expensive cpu wise

**Comment by itaied246** [comment]
Thanks, I missed that issue, was looking for `joins` instead of `include`.

**Comment by tomprogers** [comment]
@itaied246 

> was looking for `joins` instead of `include`

Can you elaborate? The ubiquity of the word "joins" in relation to the word "associations" is making it hard to find documentation for this option (I assume it's an option, anyway).
