### ISSUE TITLE
attributeFields does not support DECIMAL type

### ISSUE THREAD

**Issue by valscion** [mickhansen/graphql-sequelize#44]
Thanks for your work on this library! It was a big reason on why I chose sequalize for my graphql experiments, and I look forward to using it.

I happened to stumble upon this case, don't know if it's a bug or a feature: I tried to supply a Sequelize model with a `DECIMAL` type to `attributeFields` but it doesn't support it. All I get is 

> Unable to convert DECIMAL to a GraphQL type

I'm not quite sure what type should a decimal be converted to automatically. Maybe to a string, like dates are converted?

**Comment by mickhansen** [comment]
It should likely just return a GraphQLFloat? https://github.com/mickhansen/graphql-sequelize/blob/master/src/typeMapper.js#L38

**Comment by valscion** [comment]
Thanks! That was quick :smile:. I was wondering though, isn't `GraphQLFloat` a type which does not provide exact precision and the mapping from a fixed precision `DECIMAL` might be lossy? We're using the `DECIMAL` type for currencies and I'm a bit squeezy with translating a currency to a float.

**Comment by mickhansen** [comment]
https://github.com/graphql/graphql-js/blob/master/src/type/scalars.js#L64

It might i guess, i'm not too familiar with what losses you might incur, actually unsure what type of conversion Sequelize does for the numbers, do you get a string or a number when returning from Sequelize?

**Comment by valscion** [comment]
https://github.com/sequelize/sequelize/issues/1964

I get a number from `Sequelize` when querying MySQL, but as per the issue I linked I would get a string out when queried from Postgresql database. Floating point numbers in Javascript don't support exact precisions, and JSON floating numbers don't do that either. If I am dealing with currencies, its a major deal breaker. We can't afford to lose precision, and the only way to serialize `DECIMAL` values to JSON without losing precision is mapping them to strings like the postgresql library does.

https://rietta.com/blog/2012/03/03/best-data-types-for-currencymoney-in/

It's a completely valid approach to define currencies using `DECIMAL` values in the database. It is _not_ valid to use floating point numbers (float or double) if exact precision is needed.

Clients using `DECIMAL` types should expect server JSON to contain strings and then do client-side mapping from string to the most appropriate type they want.

If the `DECIMAL` column values are really returned as floats by the `node-mysql` library, I think it is a bug in their end, too. That doesn't mean that this library should also implement the same buggy behavior which might lose precision.

**Comment by valscion** [comment]
Apparantly, `node-mysql` supports setting an option variable to convert `DECIMAL` values to strings to maintain precision: https://github.com/felixge/node-mysql/issues/660

We could also pick a default serialize strategy for this library and then make it configurable. It seems that `node-pg` defaults to a String whilst `node-mysql` defaults to a float but both libraries allow it to be configurable.

**Comment by mickhansen** [comment]
@valscion I'm leaning towards letting users overwrite type mappings. For now i'll convert DECIMAL to STRING instead, (leaving double as is).

**Comment by valscion** [comment]
User-overridable type mappings sound great! :+1: Do you guys have some channel or something to freely chat on collaboration ideas etc.? I might be able to help with some stuff and a way to chat would help tremendously. Maybe join http://www.reactiflux.com/ on Discord? I'm hanging out in there with the same @valscion nickname.

**Comment by mickhansen** [comment]
I'm on the reactiflux discord aswell as the sequelize slack. @mhansen on discord
