### ISSUE TITLE
Where condition on association

### ISSUE THREAD

**Issue by thifranc** [mickhansen/graphql-sequelize#446]
Hi !
I have two tables that are associated : 
```
const Product_lang = clientSequelize.define('product_lang', {
  description: {type: Sequelize.STRING},
  product_id: {type: Sequelize.INTEGER},
  lang_id: {type: Sequelize.INTEGER},
}, {
  underscored: true,
});

const Lang = clientSequelize.define('lang', {
  name: {type: Sequelize.STRING, unique: true},
}, {
  underscored: true,
});

Lang.Product_langMapping = Lang.hasMany(Product_lang, { as: 'product_langRef', foreignKey: 'lang_id' });
Product_lang.LangMapping = Product_lang.belongsTo(Lang, { as: 'langRef', foreignKey: 'lang_id' });
```
And I would like to be able to execute a query like this : 
```
SELECT * FROM product_lang JOIN lang ON (product_lang.lang_id=lang.id) WHERE lang.name='fr'
```
So far I've managed to execute the where clause on column from product_lang table, but I would like to execute one on the 'name' column of the table 'lang' : 
```
const products = {
  type: new List(ProductLangType),
  description: 'Return products',
  args: {
   //lang_id can be set, but how do I reference the name column from the Lang association ?
    name: {
      type: StringType,
      defaultValue: "fr"
    }
  },
  resolve: resolver(ProductLang)
};
```
This query returns me all of product_lang table.
I've tried reading through your doc but I'm struggling to understand and get example which show how to do this.

Thanks a lot !

**Comment by mickhansen** [comment]
Is that all the code you have? What have you tried so far to apply a custom where? I'd suggest taking a look at the `before` hook

**Comment by thifranc** [comment]
I can show you more code if you'd like but what would like to see ? 
I've logged all before args but I don't see what I can do with them as in the attributes I don't even have the 'lang' table columns.
```
resolve: resolver(ProductLang,{ before: (options, args, context, root) => {
   console.log('options -------', options);
   console.log('args -------', args);
   console.log('ctx -------', context);
   return options;
```
gives me : 
```
options ------- { attributes: [ 'id', 'description', 'product_id', 'lang_id' ], logging: undefined }
args ------- { name: 'fr'}
ctx ------- { lang: 'fr' }
```
My Graphql Types : 
```
const ProductLangType = new ObjectType({
  name: 'ProductLang',
  sqlTable: 'product_lang',
  fields: () => ({
    id: { type: new NonNull(ID) },
    product_id: { type: new NonNull(ID) },
    lang_id: { type: new NonNull(ID) },
    description: { type: StringType },
    langRef: {
      type: LangType,
      resolve: resolver(Product_Lang.LangMapping)
    }
  }),
});

const LangType = new ObjectType({
  name: 'Lang',
  sqlTable: 'lang',
  uniqueKey: 'id',
  fields: () => ({
    id: { type: new NonNull(ID) },
    name: { type: StringType },
    product_langRef: {
      type: new List(ProductLangType),
      resolve: resolver(Lang.Product_langMapping),
    }
  }),
});
```
My query : 
```
query {products{
                id, description, langRef { id, name }
        }}
```

**Comment by mmahalwy** [comment]
@thifranc any luck with this?

**Comment by thifranc** [comment]
No, so far we've moved to [Bookshelf](https://github.com/tgriesser/bookshelf)
But to be fair, we're now working on another side of the application, and this code has not been refactored yet, but as soon as I'll get to it, I'll let you know our solution if you're interested in it.

**Comment by mmahalwy** [comment]
Okay, for those who end up stumbling upon this, here is how I solved it. My problem was association tasks to current user.

```
options.before = (findOptions, args, context, root) => {
      findOptions.where = findOptions.where || {};
      findOptions.where.userId = context.user.id;

      return findOptions;
    };
```
and then in your type:
```
{
   ...
   resolve: resolver(model, options)
}
```

**Comment by RichAyotte** [comment]
Here's a naive solution if you only need one inner join deep.

I used forEach from lodash for convenience.
`const { forEach } = require('lodash')`

In your `before` function. 

```js

options.include = options.include || []

forEach(options.where, (value, key) => {
    const i = key.indexOf('.')
    if (i !== -1) {
        const includeTable = key.substr(0, i)
        const field = key.substr(i + 1)
        const where = {}
        where[field] = value
        options.include.push({
            model: model.sequelize.models[includeTable]
            , required: true
            , where
        })
        delete options.where[key]
    }
})

```
You can now name the keys in your where objects as "[table].[field]"
```gql
where = {
    "lang.name": 'fr'
}

```

I noticed that I lost some dataloader optimizations when I did this. Same query is repeated for every record found. Anyone know why and how to fix before I dig in?

**Comment by Alexsey** [comment]
I have made a PR that allows to use `where` on arbitrary association https://github.com/mickhansen/graphql-sequelize/pull/516 (but you should explicitly allow it before use). There are also detailed docs on how to use it. In our company we are using this solution while PR is not excepted

**Comment by RichAyotte** [comment]
@Alexsey can you post the GraphQL query for this issue with your patch applied?

**Comment by Alexsey** [comment]
@RichAyotte look at the docs in my branch https://github.com/Alexsey/graphql-sequelize/tree/upstreamInclude#include-1 - if you would have any questions after that - I would be glad to answer them and improve the docs
