### ISSUE TITLE
generateIncludes leaves non-nullable fields out

### ISSUE THREAD

**Issue by idris** [mickhansen/graphql-sequelize#45]
I plan on investigating further and submitting a pull-request for this tomorrow, but just wanted to document the issue before I sleep.

When using the new `map` option, I mapped `id` to `_id` and it said there was a null in that field when it wasn't nullable.  So I think `generateIncludes` is only including fields that are in the request, but it _also_ needs to include any fields that are required by the GraphQL schema.

**Comment by mickhansen** [comment]
Hmm, i wasn't actually aware that you would need to return fields other than those requested.
But in any case i have been considering whether we should remove attribute filtering at all or just fetch them all (since it continues to cause small subtle bugs).

**Comment by idris** [comment]
Yeah I may have misdiagnosed this. Taking a look now

**Comment by idris** [comment]
Okay the real problem is that the `map` option is only on `attributeFields`, not on the `resolver`.  So anything you map doesn't actually get resolved unless you manually specify a resolver.

I think we should either get rid of the `map` option, or somehow make `resolver` aware of mapped fields.  The problem is, I don't see a good way to get that `map` object shared between the two without having to specify it in both places, which is not great.

**Comment by idris** [comment]
Gah.. my brain wasn't working properly.. This is very simple.. just need to add a resolver in `attributeFields`.  I'll work on a pull request now.

**Comment by mickhansen** [comment]
Ah yeah, mapped attributes will need a resolver or a virtual field (but with a virtual we don't really need map).

**Comment by idris** [comment]
See this branch for the problem: https://github.com/mickhansen/graphql-sequelize/compare/master...idris:mapped-fields

Even after adding a resolver to the field, the field is never included in `findOptions.attributes`, so it never gets queried for. I can't think of a way to get the actual field name in `resolver.js` so we can automatically include mapped fields.

If we can't think of a solution for this, I think we should just get rid of the `map` functionality altogether, to avoid confusion.  It's easy enough to do it manually.

**Comment by mickhansen** [comment]
Or we disable findOptions.attributes filtering, it keeps giving me headaches.

**Comment by idris** [comment]
I think you at least want the attributes filtering in case there are large fields, like binary or JSONB fields that the user is never going to use.

`map` could also cause confusion and problems in the future.  For example, if you try to map an associated field.

**Comment by mickhansen** [comment]
Alright since you requested the feature initially i'll kill it for now.
