### ISSUE TITLE
When paired with dataloader-sequelize < 1.4.4, nested includes fail. 

### ISSUE THREAD

**Issue by patrickdbakke** [mickhansen/graphql-sequelize#455]
Change here solves it: https://github.com/mickhansen/dataloader-sequelize/commit/0ded8fe89a0a38fbfbdb40dd89558e2876a845ab

Though this is already fixed on 5.3.1, I'm filing a ticket in case others have the same problem I did 😄  #discoverability.
IMO, a 4.0.5 patch to upgrade the dataloader-sequelize dependency would be lovely.

**Comment by patrickdbakke** [comment]
As a comment - the way dataloader-sequelize is pulled in right now results in a weird side effect. https://en.wikipedia.org/wiki/Side_effect_%28computer_science%29

Every time you define a resolver on a model, that model gets polluted with dataloader-sequelize's overloads permanently through the entire sequelize instance.

This took me hours to debug, until I realized sequelize's `Model.prototype.findById` was overloaded to "batchFindById". 

@mickhansen What are your thoughts on removing `dataloader-sequelize` from this repo (or at least making it optional https://github.com/mickhansen/graphql-sequelize/issues/418)? It's pretty easy for folks to add dataloader-sequelize explicitly elsewhere (literally a one liner). IMO, this would be happier than the current setup, which introduces side effects on models.

**Comment by mickhansen** [comment]
@patrickdbakke Sorry for being so slow on this issue, lot has been going on in life. graphql-sequelize would be terrible slow without dataloader-sequelize, but i do agree we need a different strategy as not to pollute the entire sequelize object.
