### ISSUE TITLE
Resolver with context.user

### ISSUE THREAD

**Issue by mmahalwy** [mickhansen/graphql-sequelize#480]
AFAIK, and with my limited graphql knowledge, the recommended way is not to go with Facebook's `viewer` method of fetching scoped data but rather do auth and set current user to context for graphql?

My challenge is the setting the resolver method in examples has looked like this:
```
{
  ...
  resolve: resolver(model)
}
```

How can I take advantage of the resolver method but scope the query to current user? 

Example: user hasMany tasks. Only resolve tasks that belong to that user.

**Comment by janmeier** [comment]
Have a look at relay connection https://github.com/mickhansen/graphql-sequelize/blob/master/docs/relay.md#connections

A relay sequelizeConnection will automatically resolve the related model based on the source (so if user has a tasks field, which is a sequelizeConnection, that will call `user.getTasks`

**Comment by mmahalwy** [comment]
What if I am not using relay? :(

**Comment by rpavez** [comment]
This may help you
`              resolve: resolver(Models.user, {
                before: function(findOptions, args, context, info) {
                  if (!context.user || !context.user.id) {
                    throw new Error("No current user!");
                  }
                  findOptions.where = {
                    id: context.user.id
                  };
                  return findOptions;
                }
              })`

**Comment by mmahalwy** [comment]
Thanks @rpavez ended up going with this!

**Comment by timhuff** [comment]
@rpavez Any way to do this globally?
