### ISSUE TITLE
override resolver?

### ISSUE THREAD

**Issue by niranjanshukla** [mickhansen/graphql-sequelize#481]
This is not an issue but a question about graphql-sequelize support for using lt and gt operators without the provided where-clause.

Is overriding the resolver function the approach here? If so, what is the syntax to override the resolver function?

**Comment by janmeier** [comment]
The resolver and association functions have before and after hooks, which you can use to modify options:

```js
import {
  resolver
} from 'graphql-sequelize';

export default new GraphQLObjectType({
  name: 'Query',
  fields: {
    user {
      type: userType,
      resolve: resolver(models.User, {
        before: (options, args, context) => {
           // ...
           return options;
        }
      })
    }
  }
});

relay.sequelizeConnection({
  nodeType: ...,
  target: ...,
  before: async (options, args, context, {source}) => {
    ...
  }
});
```

**Comment by niranjanshukla** [comment]
Great, thanks!

A related question -- I am, separately, using the built-in where clause and in that process, I have created a concatenated object to fit in where, such as {where: {age : {lt: 50}, {city : {eq: 'stockholm'}}}}

However, when I pass this to the gql-tag query object as a JSON, it does not get parsed but rather expects a SequelizeJSON object.

Does the graphql-sequelize library support creation of a SequelizeJSON object in JS? (similar to JSON.parse(<string>)?

**Comment by janmeier** [comment]
I'm not sure I follow you - Can you give an example?

Also, this question might be better suited for slack https://sequelize-slack.herokuapp.com/

**Comment by niranjanshukla** [comment]
const query = gql`query ($whereClause : SequelizeJSON) {
  posts (where: $whereClause) {
    age
    city
  }
}`;

const observableQuery =
  client.watchQuery({ query, variables: {
  whereClause: **//{where: {age : {lt: 50}, {city : {eq: 'stockholm'}}}} (Question -- How to convert this to a SequelizeJSON object?)**
} });
observableQuery.subscribe({
  next: ({ data }) => showResult(data.posts),
});

In the above example, how should I send in the object-string "{where: {age : {lt: 50}, {city : {eq: 'stockholm'}}}}" as a SequelizeJSON?

**Comment by janmeier** [comment]
The sequelizeJSON type is meant to be used for fields that return json, not for input. I would very much recommend against allowing the user to pass in arbitrary where clauses! At the very least you are opening yourself up to data leaks, and at the worst (at least in sequelize 3) to sql injection attacks.

Have a look at [this](https://github.com/mickhansen/graphql-sequelize/blob/795ab6438c1230e9d93a85393fd3787f68a749e9/test/integration/relay/connection.test.js#L111-L176), specifically the `where` part, which allows you to map arguments to sequelize where clauses.

**Comment by niranjanshukla** [comment]
Hi @janmeier I am a bit new to graphql-sequelize - do you have one example with the where clause extended to support operators such as "in", "gt", "lt" ?
