### ISSUE TITLE
Support for Sequelize >=4

### ISSUE THREAD

**Issue by rpavez** [mickhansen/graphql-sequelize#485]
Starting from 4.0.0 Sequelize will only support Node v4 and above to use ES6 features.
Current version of graphql-sequelize won't work with 4.0.0 or above.

**Comment by louisremi** [comment]
Have a look at https://github.com/mickhansen/graphql-sequelize/pull/499

**Comment by Alexsey** [comment]
So what is the status? As I can see from the commit history you have commit the bump of sequelize and the revert it back to v3

**Comment by louisremi** [comment]
@Alexsey graphql-sequelize 5.3.3 is compatible with sequelize v4. This issue can be closed now :-)

**Comment by Alexsey** [comment]
Ok, thank you :)
