### ISSUE TITLE
Resolver overwrites defaultScope order

### ISSUE THREAD

**Issue by johngibbons** [mickhansen/graphql-sequelize#488]
Seeing an issue with the resolver overwriting a default order set in the model using `defaultScope`.  Here is an example:

```
'use strict'
module.exports = function (sequelize, DataTypes) {
  var Room = sequelize.define('room', {
    rank: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      allowNull: false
    }
  }, {
    defaultScope: {
      order: [['rank', 'ASC']]
    }
  })
  return Room
}
```
And the query:
```
rooms: {
  type: new GraphQLList(new GraphQLNonNull(roomType)),
  args: defaultListArgs(Room),
  resolve: resolver(Room)
}
```

The SQL output is `SELECT "id", "name", "description", "sensorId", "rank", "createdAt", "updatedAt", "storeId" FROM "rooms" AS "room" ORDER BY "room"."id" ASC;`

If I run a `findAll` query manually, I get it ordered by rank as expected:
`Executing (default): SELECT "id", "name", "description", "sensorId", "rank", "createdAt", "updatedAt", "storeId" FROM "rooms" AS "room" ORDER BY "room"."rank" ASC;`

I believe this is due to the following lines in the resolver:
https://github.com/mickhansen/graphql-sequelize/blob/master/src/resolver.js#L50-L52

**Comment by RichAyotte** [comment]
I think I'm experiencing another side effect from this.

```javascript
{
  CompanyType(where: {id: 2}) {
    name
    id
    Companies {
      id
      name
    }
  }
}
```

I get the Company Types here but no companies and this odd `order` error.
```javascript
{
  "data": {
    "CompanyType": {
      "name": "Branch",
      "id": 2,
      "Companies": null
    }
  },
  "errors": [
    {
      "message": "Cannot read property 'order' of undefined",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "CompanyType",
        "Companies"
      ]
    }
  ]
}
```
Also, the query that the resolver generates is:

```sql
SELECT `id`, `name` FROM `CompanyTypes` AS `CompanyTypes` WHERE `CompanyTypes`.`id` = 2;
```
And here's what Sequelize generates:
```sql
SELECT `CompanyTypes`.`id`, `CompanyTypes`.`name`, `Companies`.`id` AS `Companies.id`, `Companies`.`name` AS `Companies.name` FROM `CompanyTypes` AS `CompanyTypes` LEFT OUTER JOIN `Companies` AS `Companies` ON `CompanyTypes`.`id` = `Companies`.`type_id` WHERE `CompanyTypes`.`id` = 2;
```

**Comment by RichAyotte** [comment]
_I deleted my last comment because I was way off and didn't want to clutter this report._

I noticed that you pointed to the `before` hook as the source of your problem however you didn't implement it in your example.

Can you implement the before hook like below and report the output.

 ```javascript
rooms: {
	type: new GraphQLList(new GraphQLNonNull(roomType))
	, args: defaultListArgs(Room)
	, resolve: resolver(Room, {
		before(options, args, context) {
			console.log(options)
			return options
		}
	})
}

```

**Comment by Alexsey** [comment]
It looks like easy to fix by replacing in `resolver.js` line
```js
targetAttributes = Object.keys(model.rawAttributes);
```
with
```js
targetAttributes = _.get(model, '_scope.attributes', Object.keys(model.rawAttributes));
```
I have it already in my branch with some other improvements for scope support. Will make a PR as soon as will have a time to write some tests on it

**Comment by sbonami** [comment]
Any updates on this?

**Comment by Alexsey** [comment]
Sorry, not working with graphQL anymore and don't remember what was I doing there. But the code is really simple so you can try my fix on your own and if it works - making a PR should be really easy

**Comment by sbonami** [comment]
Thanks for the speedy response. I didn't want to assume it wasn't done if you'd shipped the fix. Will take care of this, thanks!
