### ISSUE TITLE
Mutation

### ISSUE THREAD

**Issue by Speedy1991** [mickhansen/graphql-sequelize#497]
Refer to this Issue #180 i tried it myself but got stuck. Here is some example code:
```
mutation: new GraphQLObjectType({
        name: 'MutationRoot',
        fields: {
            createRoom: {
                type: roomType,
                args: {
                    room: { type: new GraphQLNonNull(GraphQLString) }
                },
                resolve: (root, { room }, info) => {
                    return Room.create({name: room}).then((model) => {
                        return  resolver(Room)(root, { id: model.dataValues.id }, info);
                    }).catch((err)=>{
                        return Promise.reject(err)
                    })
                }
            }
        }
    })
```
Query:
```
mutation CreateRoom($name:String!){
  createRoom(room:$name){
    id
    name
    createdAt
  }
}
```

Error:
`TypeError: Cannot read property 'returnType' of undefined`

The room is created in the database, but the resolver call leads to this error. Can you help me plz figure out whats going wrong here?

**Comment by mickhansen** [comment]
What is `resolver`? A resolver from graphql-sequelize? Then you likely want to make sure the signature is matched correctly `source, args, context, info`

**Comment by Speedy1991** [comment]
yea its the `graphql-sequelize resolver`. What context do i have to pass? in the other issue there wasn't set an context either
it was just called like this:
`resolveFn(root,{uuid:post.uuid},info)`

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/blob/master/src/resolver.js#L40

the graphql context
