### ISSUE TITLE
Make v2.4.x compatible with later versions of graphql

### ISSUE THREAD

**Issue by idris** [mickhansen/graphql-sequelize#507]
I've pushed a commit that will make v2.4.x compatible with later versions of GraphQL (0.9.0, for example).

https://github.com/mickhansen/graphql-sequelize/compare/v2.4.0...idris:v2.4.0-fix-enum

@mickhansen it would be great if you could publish this as v2.4.1

**Comment by mickhansen** [comment]
Any reason you cant use the newer versions of graphql-sequelize? Dataloader?
Can you PR against a tag?

**Comment by idris** [comment]
@mickhansen I can't PR against a tag, that's why I had to create this as an issue instead 🤷‍♂️

The new version's usage of `dataloader-sequelize` breaks some things, which will take longer to fix.  Namely, mutations that update a model (using Sequelize) don't always update the DataLoader cache.  For example:
```
      Post.update({
        visible: false,
      },
      {
        where: {
          id: postId,
          user_id: user.id,
        },
      })));
```

**Comment by idris** [comment]
If you create a 2.4.x branch, I can create a PR against that branch.

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/tree/v2.4.0-fixes

**Comment by idris** [comment]
Thanks. Closing this issue in favor of the pull request: #510
