### ISSUE TITLE
How to update fields using mutation?

### ISSUE THREAD

**Issue by abimelex** [mickhansen/graphql-sequelize#512]
What would be the proper way to write an update Mutation which responds with the updated object?

```
[...]
 mutation: new GraphQLObjectType({
        name: 'Mutation',
        fields: {
            setState: {
                type: userType,
                args: {
                    input: {
                        type: userStateInputType
                    }
                },
                resolve: (root, {input}, info) => {
                    const {uuid, state} = input;

                    return db.user
                        .update(
                            {state},
                            {where: {uuid}}
                        )
                        .then(() => {
                            return resolver(db.user); // db.user contains the user model
                        }).catch((err) => {
                            return Promise.reject(err);
                        });
                }
            }
        }
    })
[...]
```

This gives me always "Cannot return null for non-nullable field User.uuid." I tried also to implement a resolver function like: `return resolveUser(root, {uuid: input.uuid}, info);`but that doesn't work either. `root` and ìnfo` seems to be undefined. 

My requests looks like this:

```
mutation {
  setState(input: {uuid: "ffcb9f75-dc17-4bb7-896a-280c1b9c2f8f", state: "newState"}) {
    uuid
    state
  }
}
```

The userStateInputType:

```
const userStateInputType = new GraphQLInputObjectType({
    name: 'userStateInput',
    fields: {
        uuid: {
            type: new GraphQLNonNull(GraphQLString)
        },
        state: {
            type: new GraphQLNonNull(GraphQLString)
        }
    }
});
```

**Comment by abimelex** [comment]
My resolver looks like this now and it works.  But it looks somehow wrong to me to perform the update in the before hook.

```
resolve: resolver(db.user, {
    before: async (findOptions, {input}) => {
        const {uuid, state} = input;

        await db.user.update(
            {state},
            {where: {uuid}}
        );

        findOptions.where = {
            uuid
        };

        return findOptions;
    }
})
```

**Comment by mickhansen** [comment]
You should definitely not be doing mutations in a regular field resolver, that should always happen inside your mutation handler

**Comment by abimelex** [comment]
ok, I'm beginner in Graphql, where can I define my mutation handler? I did't found anything in the docs yet...

**Comment by mickhansen** [comment]
That depends on how you're defining your schema in general @abimelex.
This is not related to graphql-sequelize, look at graphql-js or graphql-relay-js

**Comment by abimelex** [comment]
A I got you wrong, so I guess the mutation should still placed in the `resolve` function but not in the `resolver` function. Was confused about the names...

**Comment by mickhansen** [comment]
Yes mutations still have a `resolve` function, but usually a custom one, you would not generally use `resolver` from this library :)

**Comment by ahelord** [comment]
hello @mickhansen  @abimelex   friends could put an example of a mutation with an update of a record (Sequelize) because I do not understand how to do an implementation.

**Comment by mickhansen** [comment]
@ahelord It's really not that different from implementing an update in a REST api

**Comment by mschipperheyn** [comment]
@mickhansen example?

**Comment by mickhansen** [comment]
@mschipperheyn An example of what? :)

**Comment by prinze77** [comment]
An example of update
