### ISSUE TITLE
Support for root Relay Connections

### ISSUE THREAD

**Issue by mcurcio** [mickhansen/graphql-sequelize#514]
Is there currently a way to generate Relay-compatible connection schemas from a single Model (i.e. not an association)?

**Comment by mickhansen** [comment]
Yes, you simply use `target: Model` and scope everything in your `before`

**Comment by mcurcio** [comment]
I'm not sure what you mean by "scope everything in your before". I tried applying a model as the `target` and I am not seeing good results. My schema looks something like this:
```js
User = sequelize.define('user', {});

const Users = sequelizeConnection({
        name: 'Users',
        nodeType: User,
        target: User
});

const schema = new GraphQLSchema({
        query: new GraphQLObjectType({
                name: 'RootQueryType',
                fields: {
                        users: {
                                type: Users.connectionType,
                                args: Users.connectionArgs,
                                resolve: Users.resolve
                        }
                }
        })
});
```
And when run against this query:
```graphql
{
  users {
    pageInfo {
      hasNextPage
    }
  }
}
```
I get the following error:
```graphql
{
  "data": {
    "users": null
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field UsersConnection.pageInfo.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "users",
        "pageInfo"
      ]
    }
  ]
}
```

**Comment by mickhansen** [comment]
That's odd, target: Model should work, we use it a few places and then we filter based on source in the `before` resolver options hook

**Comment by mcurcio** [comment]
Good to know. I'll poke around some more.

**Comment by mcurcio** [comment]
It is working now. Thanks for the guidance. I didn't make any changes at all ... it simply started working.

I _think_ my issue is that I was mixing up my resolvers since I have the very similarly named objects `User` and `Users` where the former is a `GraphQLObjectType` and the latter is a graphql-sequelize Connection. For what its worth, I did also upgrade to the latest sequelize/graphql-sequelize.
