### ISSUE TITLE
Unable to pass args to association

### ISSUE THREAD

**Issue by jansselt** [mickhansen/graphql-sequelize#515]
Terribly new to graphql and sequelize (first day for both), so good chance Im missing something stupid here or misunderstanding.

I am trying to run the following query in graphiql while doing some testing and am getting an error

```
{
  users(id: 2) {
    id
    firstName
    lastName
    email
    children (id: 3) {
      id
      firstName
      lastName
      dateOfBirth
      gender
    }
  }
}
```

The error I receive is 
```
{
  "errors": [
    {
      "message": "Unknown argument \"id\" on field \"children\" of type \"User\".",
      "locations": [
        {
          "line": 7,
          "column": 15
        }
      ]
    }
  ]
}
```

It doesn't seem to care for me trying to pass args to the associated children which are of type Child

Here are my sequelize models
```
import Sequelize from 'sequelize'
import connection from './connection'

const User = connection.define('user', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        unique: true,
        allowNull: false,
        field: 'id'
    },
    firstName: {
        type: Sequelize.STRING,
        allowNull: false,
        field: 'first_name'
    },
    lastName: {
        type: Sequelize.STRING,
        allowNull: false,
        field: 'last_name'
    },
    email: {
        type: Sequelize.STRING,
        unique: true,
        allowNull: false,
        field: 'email',
        validate: {
            isEmail: true
        }
    }
}, {
        timestamps: false,
        tableName: 'user',
    });

export default User
```

```
import Sequelize from 'sequelize'
import connection from './connection'

const Child = connection.define('child', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        unique: true,
        allowNull: false,
        field: 'id'
    },
    firstName: {
        type: Sequelize.STRING,
        allowNull: false,
        field: 'first_name'
    },
    lastName: {
        type: Sequelize.STRING,
        allowNull: false,
        field: 'last_name'
    },
    dateOfBirth: {
        type: Sequelize.DATE,
        allowNull: false,
        field: 'dob'
    },
    gender: {
        type: Sequelize.STRING,
        allowNull: false,
        field: 'gender'
    }
}, {
        timestamps: false,
        tableName: 'child'
    });

export default Child
```

```
import User from './user'
import Child from './child'

const db = {};

User.Children = User.belongsToMany(Child, {
    through: 'user_child_xref',
    foreignKey: 'user_id',
    timestamps: false
});
Child.Parents = Child.belongsToMany(User, {
    through: 'user_child_xref',
    foreignKey: 'child_id',
    timestamps: false
});

db.user = User
db.child = Child

export default db
```

And here are my graphql models and schema

```
import {
  GraphQLObjectType,
  GraphQLInt,
  GraphQLString,
  GraphQLList
} from 'graphql'
import { resolver } from 'graphql-sequelize';
import db from '../database/sequelize/db'
import Child from './child'

const User = new GraphQLObjectType({
  name: 'User',
  fields: () => {
    return {
      id: {
        type: GraphQLInt
      },
      firstName: {
        type: GraphQLString
      },
      lastName: {
        type: GraphQLString
      },
      email: {
        type: GraphQLString
      },
      children: {
        type: new GraphQLList(Child),
        resolve: resolver(db.user.Children)
      }
    }
  }
});

export default User
```

```
import {
  GraphQLObjectType,
  GraphQLInt,
  GraphQLString,
  GraphQLList
} from 'graphql'
import { resolver } from 'graphql-sequelize'
import db from '../database/sequelize/db'
import User from './user'

const Child = new GraphQLObjectType({
  name: 'Child',
  fields: () => {
    return {
      id: {
        type: GraphQLInt
      },
      firstName: {
        type: GraphQLString
      },
      lastName: {
        type: GraphQLString
      },
      dateOfBirth: {
        type: GraphQLString
      },
      gender: {
        type: GraphQLString
      },
      parents: {
        type: new GraphQLList(User),
        resolve: resolver(db.child.Parents)
      }
    }
  }
});

export default Child
```

```
import {
  GraphQLObjectType,
  GraphQLInt,
  GraphQLString,
  GraphQLFloat,
  GraphQLList
} from 'graphql'
import { resolver } from 'graphql-sequelize';
import db from '../database/sequelize/db'
import User from './user'
import Child from './child'

const Query = new GraphQLObjectType({
  name: 'Query',
  description: 'This is a root query',
  fields: () => {
    return {
      users: {
        type: new GraphQLList(User),
        args: {
          id: {
            type: GraphQLInt
          },
          firstName: {
            type: GraphQLString
          },
          lastName: {
            type: GraphQLString
          },
          email: {
            type: GraphQLString
          },
          limit: {
            type: GraphQLInt
          },
          order: {
            type: GraphQLString
          }
        },
        resolve: resolver(db.user)
      },
      children: {
        type: new GraphQLList(Child),
        args: {
          id: {
            type: GraphQLInt
          },
          firstName: {
            type: GraphQLString
          },
          lastName: {
            type: GraphQLString
          },
          dateOfBirth: {
            type: GraphQLString
          },
          gender: {
            type: GraphQLString
          }
        },
        resolve: resolver(db.child)
      }
    }
  }
})

export default Query
```

```
import {
  GraphQLSchema
} from 'graphql'
import Query from './types/query'

const Schema = new GraphQLSchema({
  query: Query
});

export default Schema;
```

Can anyone tell me what Im doing wrong?  Or am I attempting to do something unsupported?  Been banging my head on this for a few hours googling and reading the issues in here.  Haven't had any luck.

**Comment by mickhansen** [comment]
Your top level childrens field has an id arg, but your nested childrens field inside `user` does not.

**Comment by jansselt** [comment]
Interesting.  I was under the assumption (must have been the incorrect assumption) that because I tell graphql that the nested children is a list of Child, that it would automatically pick up the args defined for a list of Child already defined (top level children).  I connected dots that must not exist.

I appreciate the help

**Comment by mickhansen** [comment]
Types don't have arguments, fields do, so there's no carry over when reusing a type.

**Comment by jedwards1211** [comment]
@mickhansen I take it this package doesn't provide anything to automatically generate fields for associations?

**Comment by mickhansen** [comment]
@jedwards1211 There are relay connection field helpers which work with associations

**Comment by jedwards1211** [comment]
I see, I'm using Apollo so I wrote a helper to generate association fields.

This really connection stuff sounds weird, especially if they're not doing the usual nested GraphQL queries?

**Comment by mickhansen** [comment]
Relay connections are just a spec with connections/edges/nodes, i think it's a really good spec though.

**Comment by jedwards1211** [comment]
Well I'm confused.  One of the examples sets up resolution for an association manually:
```
let userType = new GraphQLObjectType({
  name: 'User',
  description: 'A user',
  fields: {
    id: {
      type: new GraphQLNonNull(GraphQLInt),
      description: 'The id of the user.',
    },
    name: {
      type: GraphQLString,
      description: 'The name of the user.',
    },
    tasks: {
      type: new GraphQLList(taskType),
      resolve: resolver(User.Tasks)
    }
  }
});
```
But I've already automated the process of creating fields for all associations on a model, like `User.Tasks` above.
So is this kind of thing still needed when using Relay connections or not?  I'm confused what the rest of the code for Relay would look like.

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/blob/master/docs/relay.md#connections

**Comment by jedwards1211** [comment]
So the alternative to pagination with connections would basically just be to add args for `limit` and `offset` right?

**Comment by jedwards1211** [comment]
Connections seem heavily geared toward the infinite scroll use case, but I'm not making that kind of app

**Comment by mickhansen** [comment]
`limit` and `offset` perform very poorly on large data sets, using cursors is a common practice for pagination in general.

**Comment by jedwards1211** [comment]
But it looks like the relay helpers are using `limit` and `offset` under the hood anyway?
https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L221

I thought by cursor you meant a SQL cursor but I don't see any evidence in the code that it's doing that.

**Comment by mickhansen** [comment]
Hah, you're right, the code was refactored to support some more advanced usecases, initial code used cursors.

Not SQL cursors but using a identifier to identify row positioning rather than LIMIT/OFFSET.

Consider whether limit/offset is something you're chosing cause that's what SQL uses or because it's what makes sense for your app, you could also go with `page` as an argument.

**Comment by jedwards1211** [comment]
Sequelize itself doesn't provide a cursor API does it?

**Comment by mickhansen** [comment]
No, it does not, as far as i recall.

**Comment by jedwards1211** [comment]
I'm unsure of how the identifier approach would work at a low level.  Would you mind pointing me to the old code that did that if it's not too much trouble?

**Comment by jedwards1211** [comment]
(I get that one can just query for id > end of the last page, but I don't see how one would extend this approach to other sorts)

**Comment by mickhansen** [comment]
It worked by embedding the ordering value inside the cursor so it could be queried upon directly together with the id.

So if say ordering by latest poss, the cursor would be something like [id:timestamp] and it would then select posts after that timestamp.

**Comment by jedwards1211** [comment]
Oh right, duh.  I'm being dense.  Okay, well thanks for bearing with me!

**Comment by mickhansen** [comment]
No problem. Limit/offset definitely works, and this library uses that (i was thinking about the first version that got changed by an external PR eventually).

**Comment by jedwards1211** [comment]
it is weird that it got changed to limit/offset.  Does make me wonder why

**Comment by mickhansen** [comment]
IIRC it was to support cases where one would use ordering based on aggregate or otherwise calculated values.

**Comment by jedwards1211** [comment]
Ah, that makes sense.  I'm guessing if I read that code more thoroughly it uses a keyset paging strategy except when it has to fall back to using an offset.
