### ISSUE TITLE
sequelizeConnection requires clients to request for edges

### ISSUE THREAD

**Issue by marklawlor** [mickhansen/graphql-sequelize#519]
Hi, I'm trying to replicate the [official swapi-graphql API](http://graphql.org/swapi-graphql/) with an SQLite database

When trying to use the sequelizeConnection, I'm unable to create the Edge->Node alias on a connection, or get connectionFields such as totalCount to work as expected

For example

```
# Works
{
  allFilms {
    edges {
      node {
        title
      }
    }
  }
}

# Does not work
{
  allFilms {
    films { # This is an alias for edges->node https://github.com/graphql/swapi-graphql/blob/master/src/schema/connections.js#L47-L53
      title
    }
  }
}

# Works
{
  allFilms {
    edges {
      cursor
    }
    totalCount
  }
}

# Does not work
{
  allFilms {
    totalCount
  }
}
```

This is because if the sequelizeConnection will not invoke its resolver unless the query is asking for edges https://github.com/mickhansen/graphql-sequelize/blob/b8fed1b2b50b23cb004e06c37648c10207a3d95a/src/relay.js#L351-L360
While I understand Relay will always contain edges in their API queries, Server -> Server API queries or 3rd party clients who choose not to use relay will most likely be making API calls without edges and choose to use the aliases.

Is this limitation required or can it be removed to always invoke $resolver?

**Comment by marklawlor** [comment]
As an additional annoyance, the return signature of `sequelizeConnection.resolve` is different depending on your clients query. When the client does not request `edges`, the attributes `edges,  pageInfo and fullCount` will be undefined and must always be handled in each of your connectionFields.

My current work around is to monkey patch the `sequelizeConnection.resolve` function to forcefully inject  the Edge.Cursor SelectionSet if its not present in the AST (and remove it once the resolve has completed so its not returned to the client

**Comment by mickhansen** [comment]
You can still add connection fields that will be resolved even though no one asks for edges, we do this often

**Comment by mickhansen** [comment]
Although the aliasing is definitely a potential issue, could likely be fixed though.

**Comment by marklawlor** [comment]
I understand connectionFields will still resolve, however everything else $resolver does will not. For example:

* handling the before/after functions
* handling pageInfo
* all the functionality of resolver (parsing arguments to a where query)

For example a client may make this API request

```
{
  allFilms {
     pageInfo {
        startCursor 
     }
  }
}
```

While not entirely useful, I would still expect it to resolve.

Also one of the features of this library is to `automatically converts args to where if arg keys matches model attributes`

So say I'd like to perform this query:
```
{
  allFilms (title: { like: "T%"})  {
   	totalCount # totalCount === 2
  }
}
```
If sequelizeConnection didn't enforce the check for edges, this query would work.

**Comment by mickhansen** [comment]
The last query with a filter + totalCount definitely works, i use that often.
I see your point with pageInfo.startCursor, what's the usecase normally?
It's generally to avoid loading in edges which can be expensive, pageInfo could still be resolved but would require quite a few queries i suppose.

**Comment by marklawlor** [comment]
Are you able to link the unit test with the filter + totalCount? I couldn't get it working myself and was unable to find the unit test. When I walked through the debugger I never saw a code path where it would call resolver unless I provided an edge.

 pageInfo.startCursor didn't have a real life usecase, it more an example of [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). When I first implemented this project, I played around with it in graphiql and couldn't work out why some of my queries were not working. If I implement this as a commerical API, I'm imaging 3rd party developers having the same confusion but unable to use a debugger to find out whats happening

**Comment by marklawlor** [comment]
Also with the popularity of Apollo and other upcoming GraphQL tools, I would like my API to be somewhat agnostic to the clients frontend library. That would be my  primary use case for edge->node aliasing

**Comment by mickhansen** [comment]
> Are you able to link the unit test with the filter + totalCount? I couldn't get it working myself and was unable to find the unit test. When I walked through the debugger I never saw a code path where it would call resolver unless I provided an edge.

Only private code, but we use connectionFields a lot without requesting edges.

> pageInfo.startCursor didn't have a real life usecase, it more an example of Principle of least astonishment. When I first implemented this project, I played around with it in graphiql and couldn't work out why some of my queries were not working. If I implement this as a commerical API, I'm imagining 3rd party developers having the same confusion but unable to use a debugger to find out whats happening

Definitely, and i'd like to solve it but performance is always a concern

> Also with the popularity of Apollo and other upcoming GraphQL tools, I would like my API to be somewhat agnostic to the clients frontend library. That would be my primary use case for edge->node aliasing

Agree, and probably solveable easily enough.

**Comment by marklawlor** [comment]
Ok, I might address this in a PR

Its a little bit strange that for connectionFields like totalCount/fullCount (I just realised I had aliased this) I'm required to write defensive code against graphql-sequelize. The logic is there in sequelizeConnection, I'm sure we can come up with a performance friendly way to invoke it.

But just to make sure I understand 100%, your saying I should be writing the resolve function for my totalCount connectionField like this?


```
      totalCount: {
        type: GraphQLInt,
        resolve: async ({ fullCount, where }) => {
					if (!fullCount) {
						return sequelize.model.count({ where })
					}
					return fullCount					
				}
        description: `A count of the total number of objects in this connection, ignoring pagination.`
      }
```

**Comment by mickhansen** [comment]
fullCount will not be provided, that's true, but you get the `where` which should be sufficient.
