### ISSUE TITLE
$between: [Date1, Date2] does not work correcty in association's before hook

### ISSUE THREAD

**Issue by matthiasklan** [mickhansen/graphql-sequelize#524]
I have the following strange behavior, when I try to filter out associations according to an date range. The first time I run the query everything works fine. But when I change my range and run the query after the first one, it will use the old range. I logged the findOptions and the new data is present. If I run only the second query I get the expected result, but again not after multiple fetches. With other fields like IDs it works without any problems. 

```javascript
    const query = `
        query Q( $branchId: ID!, $range: [Date], $userIds: [ID] ) {
          fetchBranch(id: $branchId) {
            id,
            shifts(range: $range, userIds: $userIds) {
              id            
            }
          }
        }
      `;
```
```javascript
//resolver
Branch: {
    shifts: resolver(models.Branch.associations.Shifts, {
      before: (findOptions, args) => {
          findOptions.where = args.where || {};
          // works only for the first query correctly
          if(args.range) findOptions.where.start = { $between: args.range };
          // works anytime
          if(args.userIds) findOptions.where.userId = { $between: args.userIds };
          return findOptions;
        },
      }
    )
```

If I query directly the Shifts (not the Branch association) and use the identical before hook, everything works as expected.

Does it has something to do how dates are parsed and evaluated? thank you

**Comment by mickhansen** [comment]
What do you mean by first or second query? Do you mean first and second execution of the same query?
What does the SQL look like?

**Comment by matthiasklan** [comment]
Hi, yes I mean the first and second execution of the same query. In my test I simply execute the same query, but with different range parameters. In my scenario I have a calendar and want to get data for the next or previous month. Here is the log of my findOptions and the SQL queries. Note the exact same range in the second SQL query.

```
findOptions of first query execution:

"where": {
        "start": {
          "$between": [
            "2017-10-06T05:16:21.078Z",
            "2017-10-07T11:16:21.000Z"
          ]
        }
      }


 SELECT "id", "start" FROM "Shifts" AS "Shift" WHERE ("Shift"."shifts" IN (1) AND "Shift"."start" BETWEEN '2017-10-06 05:16:21.078 +00:00' AND '2017-10-07 11:16:21.000 +00:00') ORDER BY "Shift"."id" ASC;

```

```
findOptions of second query execution (identical query but different range value:

"where": {
        "start": {
          "$between": [
            "2017-10-06T05:16:21.104Z",
            "2017-10-06T10:16:21.104Z"
          ]
        }
      }

SELECT "id", "start" FROM "Shifts" AS "Shift" WHERE ("Shift"."shifts" IN (1) AND "Shift"."start" BETWEEN '2017-10-06 05:16:21.078 +00:00' AND '2017-10-07 11:16:21.000 +00:00') ORDER BY "Shift"."id" ASC;

```

**Comment by mickhansen** [comment]
Looks fine to me, can you be more specific about your problem?
http://sscce.org/ is always helpfull

**Comment by matthiasklan** [comment]
The second query retrieves shifts with a start date between '2017-10-06T05...' AND '2017-10-07T10...' , altough my range parameter in the findOptions is set to 2017-10-06T05.. - 2017-10-06T10... . If I execute the query separately the correct values get inserted into the SQL query.

**Comment by mickhansen** [comment]
I don't believe it's directly a cause of this library, more likely some place in your code, but it's hard for me to tell where.

graphql-sequelize wouldn't shift the date for any reason, it just passes along input.
Please provide a SSCCE, i can't really offer any additional insights based on the information you've given so far.

**Comment by matthiasklan** [comment]
Ok thank you, I will provide a SSCCE. I fork this repo and add a test case with my problem.

**Comment by mickhansen** [comment]
A PR with a failing test case is always very helpfull

**Comment by matthiasklan** [comment]
hi, so I implemented test cases to get tasks of a user by the createdAt range. The first two tests with different range parameters work fine. The third test however fails, where I simply chain the two queries of the first two tests. I hope the problem will now be more clear. You can find the tests in the following file [between.test.js](https://github.com/matthiasklan/graphql-sequelize/blob/master/test/integration/between.test.js ). 

It would be great if you could pull my fork and run the test by executing the test:between script. [https://github.com/matthiasklan/graphql-sequelize](https://github.com/matthiasklan/graphql-sequelize)

Thank you very much and keep up the great work!

**Comment by mickhansen** [comment]
@matthiasklan Open a PR, much easier.

**Comment by matthiasklan** [comment]
oh ok, will do it. I thought a PR is only if I have a solution to offer

**Comment by mickhansen** [comment]
PR for failing tests are also fine, they help uncover bugs
