### ISSUE TITLE
types definition order

### ISSUE THREAD

**Issue by mouhsinelonly** [mickhansen/graphql-sequelize#525]
in case we have a relation between two types how can we use a type before it is not even declared 

eg : 
`let taskType = new GraphQLObjectType({`
  `name: 'Task',`
  `description: 'A task',`
 ` fields: {`
   ` id: {`
      `type: new GraphQLNonNull(GraphQLInt),`
     ` description: 'The id of the task.',`
   ` },`
   ` title: {`
      `type: GraphQLString,`
      `description: 'The title of the task.',`
    `}`
  `}`
`user: {`
`type: userType, <-------------------------- user type is still undefined and it throws an error`
`resolve: resolver(Task.User)`
`}`
`});`

`let userType = new GraphQLObjectType({
  name: 'User',
  description: 'A user',
  fields: {
    id: {
      type: new GraphQLNonNull(GraphQLInt),
      description: 'The id of the user.',
    },
    name: {
      type: GraphQLString,
      description: 'The name of the user.',
    },
    tasks: {
      type: new GraphQLList(taskType),
      resolve: resolver(User.Tasks)
    }
  }
});`

**Comment by mickhansen** [comment]
Not exactly related to graphql-sequelize.
http://graphql.org/graphql-js/type/#graphqlobjecttype `fields` supposed defining a method

**Comment by mouhsinelonly** [comment]
how come it is not related .how can we achieve the example above

**Comment by mickhansen** [comment]
graphql-sequelize helps you wire together graphql-js and sequelize.
What you're having issues with is graphql-js.
Look to graphql-js docuemtation on how to use callbacks for fields, i just linked it for you.

**Comment by mouhsinelonly** [comment]
just if someone else faced the same issue and came looking for it ,wraping fields in a function solve this error like so : 
let taskType = new GraphQLObjectType({
name: 'Task',
description: 'A task',
fields: () => ({
user: {
type: userType
}
})

**Comment by mickhansen** [comment]
@mouhsinelonly Covered here: http://graphql.org/graphql-js/type/#examples
