### ISSUE TITLE
Error: Cannot find module 'graphql-relay'

### ISSUE THREAD

**Issue by tonila** [mickhansen/graphql-sequelize#532]
node version v8.7.0
npm version 5.4.2

After installing graphql-sequelize with npm, i get 

```
Error: Cannot find module 'graphql-relay'
```

Things start to work after npm i graphql-relay.

This problem has probably something to do with that graphql-sequelize has graphql-relay included as devDependency.

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/blob/master/package.json it's a peer dependency.
dev dependencies don't matter when installing in your own project.

**Comment by tonila** [comment]
Oh I didn't notice the peer dependency. 

And automatic install of peer dependencies was explicitly removed with npm 3. 
Installing graphql-relay to host makes perfect sense now. Thanks!

**Comment by mickhansen** [comment]
Yeah, this could definitely be clearer in the readme.

**Comment by jedwards1211** [comment]
@mickhansen is `graphql-relay` really required?  I'm using Apollo...

**Comment by jedwards1211** [comment]
I'm basically just using `handleConnection: false` and everything seems to be working so far with Apollo.  In this case `graphql-sequelize` isn't really going to use anything from `graphql-relay` at all, right?  Which would mean you could just conditionally require `graphql-relay`.
