### ISSUE TITLE
Pagination without relay, edges etc.

### ISSUE THREAD

**Issue by akaNightmare** [mickhansen/graphql-sequelize#533]
Hello, 

I want to make some pagination like
```js
{
  totalCount: number,
  itemPerPage: number,
  totalPage: number,
  currentPage: number,
}
```

is it possible to do that from the box?

**Comment by mickhansen** [comment]
Nothing like it built in no.

**Comment by akaNightmare** [comment]
@mickhansen theoretically is it possible? Wrap items list and make two queries for count and without count(or findAndCountAll)?

**Comment by mickhansen** [comment]
@akaNightmare graphql doesn't really impose any restrictions on how you model or resolve data, so sure, definitely possible.

**Comment by akaNightmare** [comment]
@mickhansen thanks, but with graphql-sequelize I can manipulate only with query builder or with results after finding, but I want make some `findAndCountAll()`.

**Comment by mickhansen** [comment]
@akaNightmare Is there any hard requirement on graphql-sequelize? It's just a small wrapper, you can do whatever you want pretty much

**Comment by akaNightmare** [comment]
@mickhansen it would be great if you can provide some example, right now I don't how to do that with one query, thanks a lot in adnvance

**Comment by mickhansen** [comment]
@akaNightmare I don't have any examples other than what's googleable or what's in test here.
GitHub is for issue/feature tracking, not general help.

**Comment by ShaharMynd** [comment]
@akaNightmare Did you solve it eventually? I want to use "findAndCountAll" instead of "findAll".

**Comment by mschipperheyn** [comment]
`findAndCountAll` is not supported by the `resolver`@mickhansen, would be great if this could be a setting on the resolver: `listType: findAndCountAll` or `findAll`. @ShaharMynd you could consider unwrapping the resolver. After all the resolver is called normally like so,

`user: resolver(User)`

but you could unwrap that to 
```
              users: async (source, args, context, info) =>
			const res = await resolver(models.User, {
				list: true,
			})(source, args, context, info);
                         const count = await resolver(models.User, {
                                 list: false,
                                 before: async (findOptions, args, context) => {
                                          findOptions.where = {
                                              // create a count query
                                          }
					return findOptions;
				},
                         })(source, args, context, info);

                   return {
                          users: res,
                          count
                   }
```

This is not tested, just a general idea of how this could work

**Comment by mickhansen** [comment]
@mschipperheyn No it uses findAll internally, findAndCountAll has a few caveats IIRC.
