### ISSUE TITLE
Mutations + DataLoader causes issues

### ISSUE THREAD

**Issue by idris** [mickhansen/graphql-sequelize#534]
I'm trying to upgrade `graphql-sequelize` to the latest version (using DataLoaders).  I have a problem, especially in tests (but can happen in normal cases), where the DataLoader is cached, so the result of the Mutation doesn't show up in future queries.

For example:
1. do a GraphQL query, which triggers something that gets cached in a DataLoader
2. do a mutation that affects some data in that query's results
3. in the output of the mutation, the same DataLoader from step 1 (and step 2) is used, thereby returning stale data.  The data was updated in step 2, but the DataLoader still has it cached.

I think we need to call `resetCache` on `dataloader-sequelize` each time a new Query/Mutation is issued.  But then we also need to call `resetCache` after any mutation (before it returns any output).

**Comment by mickhansen** [comment]
https://github.com/mickhansen/dataloader-sequelize/issues/39#issuecomment-341648109

**Comment by idris** [comment]
#536 would also resolve this issue

**Comment by bkoltai** [comment]
So do I understand correctly that the suggested resolution to stale versions of objects being returned from the cache after an update is to disable the `dataloader-sequelize` always in the `resolver` `options`? Or is this in conjunction with some fixes to `dataloader-sequelize`?

I'm having this same issue but want to continue to benefit from `dataload-sequelize` for `Queries`.

Thanks for these great libraries, btw!
