### ISSUE TITLE
BIGINT in Sequelize v4 gets translated to GraphQLInt

### ISSUE THREAD

**Issue by idris** [mickhansen/graphql-sequelize#539]
It should be `GraphQLString`.

This code in Sequelize makes `BIGINT` inherit from `INTEGER`:
https://github.com/sequelize/sequelize/blob/0047dca9dffe9133ae231d7e0de50bca5714634a/lib/data-types.js#L213

Which causes `graphql-sequelize` to short-circuit and return `GraphQLInt` instead of `GraphQLString`: https://github.com/mickhansen/graphql-sequelize/blob/9bb7dd36596faf4e5b4707c21ba2b92176048581/src/typeMapper.js#L71-L73

This test fails if run with Sequelize v4:
https://github.com/mickhansen/graphql-sequelize/blob/9bb7dd36596faf4e5b4707c21ba2b92176048581/test/unit/typeMapper.test.js#L45-L49

**Comment by mickhansen** [comment]
Agreed, PR welcome, will publish as major

**Comment by RichAyotte** [comment]
@idris Should be fixed in latest version.
