### ISSUE TITLE
Root values and child objects

### ISSUE THREAD

**Issue by garyrutland** [mickhansen/graphql-sequelize#540]
Hi,

I'm having troubles trying to figure out how to use root values and child queries with the extension.

I have a scenario where I already have the object and don't want to re-query the database but can't see a way of passing in a root value into the `resolver()`.
I tried doing something similar to this but it didn't work (very rough example to give you the idea):
```
resolve: (obj, args, context) => {
    if (obj instanceof Model) {
        return obj;
    }

    return resolver(Model);
},
```

The other issue I'm having is child objects and the queries selecting all objects rather than just the ones that belong to the parent.
Am I missing something here as well as I can't see a way of referencing the parent object in the child `before` call?

Thanks,
Gary

**Comment by mickhansen** [comment]
root values are only available to top level resolvers as the source object aren't they?
there shouldn't be any major difference as this is just how graphql works

**Comment by garyrutland** [comment]
Yeah, never mind.

I think I had a lack of understanding of the graphql node implementation and sequelize generally, I've actually now got it all working with just sequelize rather than this plugin.
Works like a charm.

I might come back to use this plugin once I understand better.
