### ISSUE TITLE
Example for a belongsTo is missing

### ISSUE THREAD

**Issue by intellix** [mickhansen/graphql-sequelize#543]
Was gruelling over trying to do this as a fairly new user, but managed to do it in the end. Couldn't find any example of how this should be done since there's a fair bit of magic and it's not that clear what the library has for doing it. Seems in the end it was quite simple:

Example for fetching a belongsTo like **task.user**:

```ts
let taskType = new GraphQLObjectType({
  name: 'Task',
  description: 'A task',
  fields: {
    id: {
      type: new GraphQLNonNull(GraphQLInt),
      description: 'The id of the task.',
    },
    title: {
      type: GraphQLString,
      description: 'The title of the task.',
    },
    // Example missing
    user: {
      type: UserType,
      resolve: async task => task.getUser(),
    }
  }
});
```

**Comment by mickhansen** [comment]
Or: `resolve: resolver(Task.User)` if `Task.User` is an association
