### ISSUE TITLE
Task.user field type must be Output Type but got: undefined

### ISSUE THREAD

**Issue by intellix** [mickhansen/graphql-sequelize#544]
I've added A UserTaskConnectionType as per the examples/docs and using it on it's own is fine. It all works. Now if you try to re-use UserType for somewhere else, like fetching a Task's User, the import is undefined ONLY when you have User.tasks:

```ts
// File 1
export const UserTaskConnectionType: any = sequelizeConnection({
  name: 'UserTaskConnection',
  nodeType: TaskType,
  target: User.Task || Task,
  connectionFields: {
    total: {
      type: GraphQLInt,
      resolve: ({ source }: any) => source.countTasks(),
    },
  },
});

export const UserType = new GraphQLObjectType({
  name: User.name,
  description: '',
  fields: {
    id: globalIdField(User.name),
    name: {
      type: GraphQLString,
    },
    // This causes UserType to become undefined
    tasks: {
      type: UserTaskConnectionType.connectionType,
      args: UserTaskConnectionType.connectionArgs,
      resolve: UserTaskConnectionType.resolve,      
    },
  },
  interfaces: [nodeInterface],
});

...
// File 2
import { UserType } from './user.type'; // undefined
```

I've a feeling there's some weird mutating/monkey-patching going on but am not quite sure what causes it

**Comment by mickhansen** [comment]
When imports are undefined it's usually becaue you have a circular reference

**Comment by intellix** [comment]
Ahah, you were right. I checked this repository and found a solution: https://github.com/graphql/swapi-graphql/blob/master/src/schema/types/film.js#L35

It seems that the fields property allows a function to lazily resolve to get around circular dependencies. Might be good in the set of examples as well

**Comment by mickhansen** [comment]
`fields` supporting a `thunk` is a property of graphql-js, eventually you end up writing all `fields` like that as a habit :)
