### ISSUE TITLE
GraphQLID for UUID

### ISSUE THREAD

**Issue by galki** [mickhansen/graphql-sequelize#545]
apparently graphql-sequelize treats UUID fields as `GraphQLString` but mutations dont work this way. i have to do the below hack to make it work:
```
fields: () => Object.assign(attributeFields(MyModel), {
	id: { type: GraphQLID },
}),
```
graphql-sequelize: 5.4.2
sequelize: 4.13.2

**Comment by mickhansen** [comment]
graphql-sequelize doesn't support generating `GraphQLID` at all.
commonly because you want a global id anyways.

**Comment by galki** [comment]
not too familiar with global ids, but are those for relay only?

**Comment by mickhansen** [comment]
They are used by any client with the concept of "nodes", that includes relay yes.
An argument could be made for graphql-sequelize returning GraphQLID for `primaryKey: true`.

PR welcome, can be merged & published as a major bump.

**Comment by galki** [comment]
alright. can you at least reopen this issue please?

**Comment by galki** [comment]
@mickhansen im gonna go with number 2 but if you have another preference, please let me know.
1. pass `attribute.primaryKey` to `typeMapper.toGraphQL` or
2. do all logic in attributeFields.js

**Comment by mickhansen** [comment]
Option #2, typeMapper is just supposed to look at types

**Comment by galki** [comment]
FYI `globalId: true` doesnt seem to work for InputTypes:
```
Error: ProjectUserInput.id field type has a resolve property, but Input Types cannot define resolvers.
```
and input types are the only place i find myself doing this id hack:
```
export default models => new GraphQLInputObjectType({
	name: 'ProjectUserInput',
	fields: () => Object.assign(attributeFields(
		models.ProjectUser, { exclude: ['projectId'] }
	), {
		id: { type: GraphQLID },
	}),
})
```
