### ISSUE TITLE
Feature request: disable use of include in resolver

### ISSUE THREAD

**Issue by LoicMahieu** [mickhansen/graphql-sequelize#547]
In a collection resolver, I need to deal with complex includes. The resulted query does not provide correct values for the nested associated objects.

At this time, the `resolver()` will [use the nested association if it is defined](https://github.com/mickhansen/graphql-sequelize/blob/master/src/resolver.js#L72-L80). I would like to disable this behavior by option so it will always fallback to the association getter.

I propose to create a new option `associationInclude` (idea for better name?) (default: true).

My corrent workarround, remove object from parent values before going to the resolve 😔
```js
partner: {
  type: types.partnerType,
  resolve: (() => {
    const resolve = resolver(Litter.Partner)
    return async (source, ...args) => {
      source.dataValues.partner = undefined
      return resolve(source, ...args)
    }
  })()
}
```

**Comment by mickhansen** [comment]
Just use `resolver(Partner)`, you're using the syntax specifically for association.

**Comment by LoicMahieu** [comment]
Thanks for your response.
Hm... I think i didn't well explain ;)

I need to pass an association to the resolver because I want to resolve an association from the parent. I still need [`source[association.accessors.get](findOptions)`](https://github.com/mickhansen/graphql-sequelize/blob/master/src/resolver.js#L81-L86).

The problem appear because I manually add some `include` with `where` in the parent resolver and so the nested objects from the include are not a correct picture of the association.
So on I want to always fallback to the association getter.

**Comment by mickhansen** [comment]
I understand your issue, but it's very specific and not something i'll look to introduce a fix for in the codebase.
Wrapping is the best solution for custom user-land stuff like this.

**Comment by LoicMahieu** [comment]
Ok if you consider that is too specific.
Thanks for taking time to answer me and obviously thank you for this library, sequelize and all other of your open source projects we love!
