### ISSUE TITLE
Redis PubSub, serialised instances and source.get is not a function 

### ISSUE THREAD

**Issue by intellix** [mickhansen/graphql-sequelize#550]
So, this one was an interesting one to debug tonight but I managed to work out the cause, reason and some ideas :)

Following on from your advice here about using `resolver(Task.User)`: https://github.com/mickhansen/graphql-sequelize/issues/543#issuecomment-346547957

I'm using subscriptions and originally used the following happily: 

```ts
import { PubSub } from 'graphql-subscriptions';

...

export const TaskType = new GraphQLObjectType({
  name: Task.name,
  fields: () => ({
    ...attributeFields(Task, { globalId: true }),
    user: {
      type: UserType,
      resolve: resolver(Task.User),
    },
  }),
  interfaces: [nodeInterface],
});

...

const Subscription = new GraphQLObjectType({
  name: 'Subscription',
  fields: () => ({
    createTask: {
      type: TaskType,
      subscribe: pubsub.asyncIterator('createTask'),
    },
  })
});

...

return Task.create({
  userId: context.user.id,
  ...args.input,
}).then(task => {
  pubsub.publish('createTask', { createTask: task });
  return { task };
});
```

`PubSub` from `graphql-subscriptions` worked perfectly as you push data within memory and it pops out at the other side to be reacted to.

Today I swapped that out for `RedisPubSub` from `graphql-redis-subscriptions` and started encountering the `source.get is not a function` error.

I learnt that the reason it's failing is that now data is being pushed through **redis** serialised as a JSON object and losing all of the association metadata, along with the source.get function.

My workaround for now is to replace the resolver(Task.User) with something a little more primitive that I know will work in all situations:

```ts
resolve: async task => User.findById(task.userId),
```

**Is it possible to re-hydrate after an object is serialised?** if not, I think there are 3 possible solutions:

1) Create a way to rehydrate from POJO
2) Change resolver to work a little even on POJO
3) Change documentation to recommend the above usage because of things like redis which people eventually scale to

Potentially related: https://github.com/mickhansen/graphql-sequelize/issues/429

**Comment by mickhansen** [comment]
sequelize has `build`/`new ()`
can wrap the resolver to hydrate potentially

**Comment by intellix** [comment]
I originally worked around this using the above `User.findById` but had the same issue again when I needed to go a little deeper in a query. Using new I figured you can also rehydrate as it comes out of redis like so:

```ts
const Subscription = new GraphQLObjectType({
  name: 'Subscription',
  fields: () => ({
    createTask: {
      type: TaskType,
      resolve: (payload) => new Task(payload.createTask),
      subscribe: () => pubsub.asyncIterator('createTask'),
    },
  }),
});
```

Hope it helps someone else
