### ISSUE TITLE
Didn't load only attributes in the query?

### ISSUE THREAD

**Issue by lxcid** [mickhansen/graphql-sequelize#556]
In the readme, it stated that…

> Only loads the attributes defined in the query (automatically adds primary key and foreign keys)

But when I tried out, I noticed that it didn't do as stated.

https://github.com/mickhansen/graphql-sequelize/blob/081d2a9686a869926eb6cdb7ee91457de6cca7c5/src/resolver.js#L57

I read the code a bit and it seems that `targetAttributes` is just a collection of all the attributes from the model.

https://github.com/mickhansen/graphql-sequelize/blob/081d2a9686a869926eb6cdb7ee91457de6cca7c5/src/resolver.js#L31

No attempt to only query the necessary field though.

**Comment by lxcid** [comment]
To give a concrete example say I have a `User` model with field, `id`, `name`, `password`, `email`…

If my query is something like this

```graphql
{
  getUserByID(id: 1) {
    name
  }
}
```

The SQL query generated is 

```sql
SELECT "id", "name", "password", "email" FROM "users" WHERE "id" = 1;
```

I was hoping something along the line…

```sql
SELECT "id", "name" FROM "users" WHERE "id" = 1;
```

**Comment by lxcid** [comment]
Might be of use to someone in the future, you figure out the attributes though this is a way to simplistic approach, worth expanding from here…

```js
import { simplifyAST } from 'graphql-sequelize';

const { fieldNodes } = info;
const ast = simplifyAST(fieldNodes[0], info);
const attributes = Object.keys(ast.fields);
```

**Comment by joewoodhouse** [comment]
Answered my own question, I think `info` is passed as the 4th argument (undocumented??) in the before handler.

**Comment by erijonhson** [comment]
Any help?

**Comment by mickhansen** [comment]
Attributes filtering was removed a while back, what help are you looking for specifically @erijonhson?

**Comment by erijonhson** [comment]
Thanks for the clarification @mickhansen 

If it was removed, you certainly judged the performance trade-off and, overall, it is irrelevant to worry about it. So I'll follow according to your decisions and, in specific cases, I'll solve it myself.

Lastly, thank you very much for [graphql-sequelize](https://github.com/mickhansen/graphql-sequelize), really come in handy.

**Comment by mickhansen** [comment]
Unless you have large `TEXT` fields it's not really worth worrying about, and it added complexity in that you couldn't have custom resolvers that depended on certain fields without the frontend also requesting those fields and other odd stuff.
