### ISSUE TITLE
Exposing toCursor and fromCursor

### ISSUE THREAD

**Issue by intellix** [mickhansen/graphql-sequelize#561]
I'm currently creating a leaderboard of users based on a field that I order by: points.
I can get a user's rank by exposing an index field for the rank:

```ts
edgeFields: {
  index: {
    type: GraphQLInt,
    resolve: edge => (new Buffer(edge.cursor, 'base64')).toString('ascii').split('$').pop(),
  },
},
```

Now, I can create a leaderboard or top 10 of points by creating a query like so:

**Query:**
```gql
{
  users(last: 10, orderBy: POINTS) {
    edges {
      index
      node {
        name
        points
      }
    }
  }
}
```

**Result:**
```
{
  "data": {
    "users": {
      "edges": [
        {
          "index": 0,
          "node": {
            "name": "Bob"
            "points": 100
          }
        },
        {
          "index": 1,
          "node": {
            "name": "Bill",
            "points": 90
          }
        },
        ...
      ]
    }
  }
}
```

Right now I'm duplicating the work of fromCursor to get ahold of the index. It'd be cool to expose those 2 methods:
https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L168
https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L178

**Comment by mickhansen** [comment]
Another solution might be to add `index` to the edge here: https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L210
