### ISSUE TITLE
Support for connections in top-level query?

### ISSUE THREAD

**Issue by mikefowler** [mickhansen/graphql-sequelize#563]
@mickhansen, first off, thank you for such a complete, easy to setup bridge between Sequelize and GraphQL. After trying out both Sequelize and Objection/Knex in the past few months, this package became the deciding factor in moving forward with Sequelize.

I've hooked up Relay connections without issue for several of my entities' associations. However, I'd greatly prefer to stick with a single pagination method across queries, including in my top-level queries. What is your recommendation for implementing cursor-based pagination for top-level queries? It seems like a setup like the one below does not automatically work:

### Resolvers
```javascript
{
  users: resolver(models.User),
}
```

### Schema

```gql
type Query {
  users(
    first: Int,
    after: String,
    last: Int,
    before: String  
  ): UsersConnection
}

type UsersConnection {
  pageInfo: PageInfo!
  cursor: String
  edges: [UsersEdge]
}

type UsersEdge {
  cursor: String!
  node: User
}

type User {
  id: Int
  firstName: String
}
```

### Query

```gql
{
  users(first: 10) {
    edges {
      cursor
      node {
        firstName
      }
    }
  }
}
```

I see that `resolver` only runs `handleConnection` for associations ([here](https://github.com/mickhansen/graphql-sequelize/blob/master/src/resolver.js#L71)), but I'm curious as to why that is.

Thanks again!

**Comment by intellix** [comment]
For connections in root query I'm doing:
```ts
export const UserConnectionType = sequelizeConnection({
  name: 'UserConnection',
  nodeType: UserType,
  target: User,
  connectionFields: {
    total: {
      type: GraphQLInt,
      resolve: ({ fullCount }: { fullCount: number }) => (fullCount ? fullCount : User.count()),
    },
  },
  where: (key: string, value: any, currentWhere: any) => ({ [key]: value }),
});

users: {
  type: UserConnectionType.connectionType,
  args: UserConnectionType.connectionArgs,
  resolve: UserConnectionType.resolve,
},
```

**Comment by mickhansen** [comment]
So react-relay generally doesnt support multi-arg root items, so i never have root connections.
What usually use are generic target: Model connections that change their query based on source in before.
I'm not sure handleConnection actually matters, atleast we use target: Modle quite a bit in our codebase - it's been a while since i wrote the code for graphql-sequelize

**Comment by mikefowler** [comment]
@intellix @mickhansen, maybe I shouldn't have used the word "connection" since it has specific connotations in Relay. What I'm really asking is how I'd handle cursor pagination for a root query. The `handleConnection` method handles cursors automatically, but is there an easy way to do so for root queries?

**Comment by mickhansen** [comment]
`handleConnection` is built specifically for relay type connections that use relay type pagination.
I guess it might be possible to use it for root queries but i haven't given it much thought.

**Comment by mikefowler** [comment]
@intellix in https://github.com/mickhansen/graphql-sequelize/issues/561 you have an example of cursor pagination in your root `users` query. Can you share how you're handling that? I'm trying to get a better sense of how folks in the community are handling that.

**Comment by intellix** [comment]
For my root many fields I'm creating connections. Here's my most complex one with the indexes and multiple orderBy:

```ts
export const UserConnectionType = sequelizeConnection({
  name: 'UserConnection',
  nodeType: UserType,
  target: User,
  connectionFields: {
    total: {
      type: GraphQLInt,
      resolve: ({ fullCount }) => (fullCount ? fullCount : User.count()),
    },
  },
  edgeFields: {
    index: {
      type: GraphQLInt,
      resolve: (edge: any) => {
        return new Buffer(edge.cursor, 'base64')
          .toString('ascii')
          .split('$')
          .pop();
      },
    },
  },
  orderBy: new GraphQLEnumType({
    name: 'UserOrderBy',
    values: {
      ID: { value: ['id', 'ASC'] },
      XP: { value: ['xp', 'ASC'] },
    },
  }),
  where: (key: string, value: any, currentWhere: any) => {
    if (key === 'name') {
      return {
        name: { $like: `%${value}%` },
      };
    }

    return { [key]: value };
  },
});
```

```ts
users: {
  type: UserConnectionType.connectionType,
  args: {
    ...UserConnectionType.connectionArgs,
    name: {
      description: 'Fuzzy-matched name of user',
      type: GraphQLString,
    },
  },
  resolve: UserConnectionType.resolve,
},
```

Query:
```gql
fragment User on User {
  id
  name
  xp
  createdAt
}

query UserList($name: String, $first: Int, $last: Int, $orderBy: [UserOrderBy]) {
  users(name: $name, first: $first, last: $last, orderBy: $orderBy) {
    edges {
      node {
        ...User
      }
    }
  }
}
```

**Comment by mikefowler** [comment]
Awesome, thanks!
