### ISSUE TITLE
Optionally passing a model resolving function instead of a model 

### ISSUE THREAD

**Issue by hendrul** [mickhansen/graphql-sequelize#566]
The resolver function assumes the sequelize instance and models already exists, in this [pad](https://launchpad.graphql.com/379q9pqzwv) I tried to make a barebones graphql  + graphql-sequelize example, but I need to wrap the resolvers to get access to the sequelize instance comming from the context. 
```js
// ... Except
// Wrap the resolvers to defer access to sequelize when coming from context
const resolvers = {
  Query: {
    product: (_, args, ctx, info) => resolver(ctx.sequelize.models.Product)(_, args, ctx, info),
    allProducts: (_, args, ctx, info) => resolver(ctx.sequelize.models.Product)(_, args, ctx, info),
  },
}
// ...
```
If I could pass a function that receive the context and returns the model this would have turn into 
```js
// ... Except
const resolvers = {
  Query: {
    product: resolver(({sequelize}) => sequelize.models.Product),
    allProducts: resolver(({sequelize}) => sequelize.models.Product),
  },
}
// ...
```
By the way consider appending the pad some where in the docs.

**Comment by mickhansen** [comment]
:+1:

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/pull/568
