### ISSUE TITLE
Support for Sequelize >=4

### ISSUE THREAD

**Issue by flybluewolf** [mickhansen/graphql-sequelize#569]
upgrade to version 7.0.0, this version don't support Sequelize >=4.

` let toCursor = function toCursor(item, index) {

    let id = item.get(item.Model.primaryKeyAttribute);

    return (0, _base.base64)(PREFIX + id + SEPERATOR + index);
  };
`
it seem to change 

` let toCursor = function toCursor(item, index) {

        let id = item.get(targetMaybeThunk.primaryKeyAttribute);

        return (0, _base.base64)(PREFIX + id + SEPERATOR + index);
  };
`

**Comment by mickhansen** [comment]
That fix wouldn't work as it doesnn't take into account the part that says `maybeThunk'.
Maybe `item.constructor` works, PR welcome (you can test locally against v4)

**Comment by intellix** [comment]
item.constructor worked for me locally with v4. I'll submit a PR shortly
