### ISSUE TITLE
Pagination for one object

### ISSUE THREAD

**Issue by moseleyi** [mickhansen/graphql-sequelize#581]
I saw in the relay documentation that Sequelize Connection can take care of pagination but the example given is only when you want to paginate through children records (tasks of users). What if I only want to paginate through list of users, how to set it up?

**Comment by intellix** [comment]
I think you mean this? https://github.com/mickhansen/graphql-sequelize/issues/563#issuecomment-363579946

**Comment by moseleyi** [comment]
It's actually helpful, thank you, but where do I specify the pages. Do I use "first" and "last" Is that where "items per page" is calculated?

**Comment by intellix** [comment]
first: 50 = you want the first 50 (ordered by ASC)
last: 50 = you want the last 50 (ordered by DESC)

You've got cursors, so if you do pageInfo { endCursor } you can use it for something like: { first: 50 after: "cursor123==" }

Sounds like you wanna read up a bit more on Relay :) Your example of the orderBy is correct

**Comment by moseleyi** [comment]
Thanks, with the help of your link I figured it out. OrderBy is still a mystery because the connector I have wants to connect as order:"username", but in the relay we can only use order:[username].. 

Do you know if there's a list of how to implement things like filter, search etc. ?

**Comment by intellix** [comment]
for search, you can specify a where function in the sequelizeConnection like so:

```ts
export const UserConnectionType = sequelizeConnection({
  ...
  where: (key: string, value: any, currentWhere: any) => {
    if (key === 'name') {
      return {
        name: { $like: `%${value}%` },
      };
    }

    return { [key]: value };
  },
});
```

in your root query:
```ts
users: {
  type: UserConnectionType.connectionType,
  args: {
    ...UserConnectionType.connectionArgs,
    name: {
      description: 'Fuzzy-matched name of user',
      type: GraphQLString,
    },
  },
  resolve: UserConnectionType.resolve,
},
```

**Comment by mickhansen** [comment]
> but in the relay we can only use order:[username]

You can use `order: USERNAME` too.
It's an ENUM yes, since you should use types whenever you can.

**Comment by moseleyi** [comment]
But I can't use` order:"username"` anymore, can I? (I'm trying to connect CrudlIO with GraphQL Sequelize, and the way they compile the query is that you assign "sortable"  attribute to a field and they use it as order:"<field>")

Also I'm trying to find a list of all those arguments we can attach to sequelizeConnection? I would like to implement custom arguments like "search". Where can I find it?
