### ISSUE TITLE
Type Query must define one or more fields.

### ISSUE THREAD

**Issue by clenondavis** [mickhansen/graphql-sequelize#588]
### Hi @mickhansen, how you doing man?, i hope well,

Thanks for reading my issue description, i appreciate your time.

I'm trying with a mutation to add a record, but i have been having this issue

> ` Query must define one or more fields.`

This is [the link of my code] https://gist.github.com/clenondavis/28841cda0177160134451b723726da61)

This is a link to the [screenshoot with the body request i'm sending to graphql](http://prntscr.com/jbmbwk)

I do not know what i'm doing wrong, but I'll appreciate your help

Thanks,

Best regards,

**Comment by mickhansen** [comment]
Doesn't sound related to graphql-sequelize?
Regardless your code doesnt show the file that sets up the schema root which should have a mutation and query type.
