### ISSUE TITLE
sequelizeConnection will break on any string primary keys containing $

### ISSUE THREAD

**Issue by jedwards1211** [mickhansen/graphql-sequelize#596]
Imagine that the primary keys of a table are strings and the row at index 30 of the results has the primary key `FU$BAR`.

The cursor comes out to `base64('arrayconnection$FU$BAR$30')`.
`fromCursor` will then split at the wrong `$` and return `{id: 'FU', index: 'BAR'}` instead of `{id: 'FU$BAR', index: 30}`.
### Oops! 💩 
I don't understand why anyone would use an arbitrary (hence more error-prone) delimiting scheme when they could just `JSON.stringify([id, index])` and `JSON.parse` it back out.  JSON is hard to improve upon.

### Problem source code in `relay.js`
```
  let toCursor = function (item, index) {
    let id = item.get(item.constructor ? item.constructor.primaryKeyAttribute : item.Model.primaryKeyAttribute);
    return base64(PREFIX + id + SEPERATOR + index);
  };

  let fromCursor = function (cursor) {
    cursor = unbase64(cursor);
    cursor = cursor.substring(PREFIX.length, cursor.length);
    let [id, index] = cursor.split(SEPERATOR);
     ...
  };
```

**Comment by mickhansen** [comment]
> I don't understand why anyone would use an arbitrary (hence more error-prone) delimiting scheme

Code mostly lifted from https://github.com/graphql/graphql-relay-js/blob/master/src/connection/arrayconnection.js

**Comment by mickhansen** [comment]
As for not using `JSON`, i imagine that size was considered in relation to mobile.

**Comment by intellix** [comment]
While you're on the subject of size savings, why not shorten "arrayconnection"?

**Comment by jedwards1211** [comment]
@intellix my PR gets rid of it entirely
