### ISSUE TITLE
MSMQL Support?

### ISSUE THREAD

**Issue by jon64digital** [mickhansen/graphql-sequelize#611]
I've been looking for a way to use MS SQl Serverwith Node/GraphQL for a while avoiding the N+1 query problem and thought I'd hit the jackpot here. I see that it's not currently supported though. Is this because it's not possible to support it or is there something planned?

**Comment by mickhansen** [comment]
It's mostly because none of the people involved work with MSSQL

**Comment by jon64digital** [comment]
Ah, OK, so it is possible then. Would be great to add it as Sql Server is one of the most used databases in the world, especially in enterprise.

**Comment by UmerIftikhar** [comment]
Is MS SQL support still to be added?

**Comment by mickhansen** [comment]
@UmerIftikhar Not by me.

**Comment by jon64digital** [comment]
I'm still hoping that somebody watching this does have the knowledge to implement this. MSSQL is only behind Oracle and MySql in terms of being the most popular database in the world looking at recent stats so I'm sure there must be way more people out there that need this compared to something like Postgresql support.

**Comment by mickhansen** [comment]
@jon64digital it might be very popular globally but it doesn't seem to have gained much traction in Nodeland.

**Comment by gvbkr** [comment]
@mickhansen  Quick question - what does it take to add support for MS SQL Server? Since we are using sequelize shouldn't the actual database be abstracted? I can help make the changes if you can help give us an overview of what needs to be done?

@jon64digital  @UmerIftikhar  may be we can work together to add this support once we have clarity on what needs to be done.

**Comment by mickhansen** [comment]
@gvbkr Sequelize doesn't always have the exact same support for all dialects. But this "fix" sort of relies on a bug. Sequelize needs full cross dialect support for `offset` in `groupedLimit`, then we can rely on that here.

**Comment by mickhansen** [comment]
@gvbkr I don't know, for the most part it should just work but there can be subtle differences.
If a few people are willing to help maintain mssql support i'm open to that.

**Comment by mubaidr** [comment]
Looks like this does work fine with MSSQL except that it does not seems to support some data types. It emits error when encounter `NCHAR` or `SMALLDATETIME` data type. I did modify the code to treat these as string and it started working. 

I suggest all non-existence dataTypes should be treated as string by default.

**Comment by mickhansen** [comment]
> I suggest all non-existence dataTypes should be treated as string by default.

I'd rather throw, defaulting to string means breaking that when we fix it (if string is incorrect). Users can ignore certain fields and provide their own types or submit a PR :)

**Comment by mubaidr** [comment]
Hmm 

BTW there is error at line: https://github.com/mickhansen/graphql-sequelize/blob/master/src/typeMapper.js#L121

that
```bash
Type Error: sequelizeType.toSql is not a function. 
```

because there is no sequel type (of `NCHAR` in this case) therefore toSql is not defined for it.
