### ISSUE TITLE
Where Invalid value like

### ISSUE THREAD

**Issue by pbrink231** [mickhansen/graphql-sequelize#614]
I am pulled to the latest version as of today which had a Sequelize V4 pull 8 days ago.

I am using Sequelize version 4

I can run this query and be fine but the other ones do not work and return
`"Invalid value { '$iLike': '%dfs%' }"`
```
        Op = Sequelize.Op
        before: (findOptions, args) => {
          if (args.query) {
            findOptions.where = {
		name: { [Op.iLike]: '%' + args.query + '%' } // -> Works fine
		// name: { $iLike: '%' + args.query + '%' } // -> Does not work
                // name: { iLike: '%' + args.query + '%' }  // -> Does not work
            }
          }
          return findOptions;
        }
```

I was trying to understand the new scrubbing method but dont fully understand what is happening yet but wanted to bring this up.

**Comment by mickhansen** [comment]
AFAIR the old operators are removed in Sequelize v4?
You should verify if the query works in Sequelize standalone.

**Comment by pbrink231** [comment]
Yes from the docs the old $ are removed.  I saw this file which is suppose to convert them so they will work with v3 or v4 but doesn't seem to be working.
[https://github.com/mickhansen/graphql-sequelize/blob/master/src/sequelizeOps.js](url)

I confirm that this setup using Op.iLike does work directly with sequelize directly.

**Comment by mickhansen** [comment]
@pbrink231 That file is not used for compability, it's used for if you use the `where` argument that this library can proide.

**Comment by pbrink231** [comment]
O I understand.  It doesnt check all wheres.  just if a where is sent into graphql as an argument which I could use in this case instead?

**Comment by mickhansen** [comment]
You could, i wouldn't recommend it.
