### ISSUE TITLE
feature request: infoToAttributes (only include attributes in the GraphQL selectionSet)

### ISSUE THREAD

**Issue by jedwards1211** [mickhansen/graphql-sequelize#619]
I will be happy to make a PR.  Currently `resolver` wastefully requests all attributes from the underlying model.  I was surprised to find that this is still the case.

**Comment by mickhansen** [comment]
We previously had filtering of attributes but it turns out it's really counter productive since a child field might need a foreign key etc.

It's more trouble than it's worth, but you could apply the logic in `before` hooks.

**Comment by jedwards1211** [comment]
Shouldn't it at least be an optional feature?  I'd rather turn it on and make my child field resolvers throw a helpful error message about which fields need to be explicitly included for them to work.

**Comment by jedwards1211** [comment]
Also I don't know if we can get access to the type's field defs in the resolver, but if we can, and we discover that none of them have custom resolvers, then at least in that case we could safely filter the attributes.

**Comment by mickhansen** [comment]
It could be @jedwards1211, i'd definitely consider a feature request for it as a pluggable feature (perhaps allow before to take an array of hooks, and then have a hook that filters options.attributes)

**Comment by jedwards1211** [comment]
Okay, hopefully I'll find time to make a PR soon, making before take an array of hooks is a neat idea.

**Comment by joewoodhouse** [comment]
@mickhansen how would you go about filtering in the `before` hook? I can't see there's any way to access which attributes are present in the query?
