### ISSUE TITLE
Automapping Sequelize.Ops helper mutates GraphQL' argument object

### ISSUE THREAD

**Issue by zandroid** [mickhansen/graphql-sequelize#624]
Hello.

We are implementing Relay Connection with "where" argument as a filter and trying to handle it in connection definition code. But it's passed to `where` function of `createConnection` helper with some mutations (object keys partially replaced with Sequelize.Op symbols). See PR for more details.

**Comment by Aukhan** [comment]
@zandroid seems like this has been merged, can we close this ? Thanks
