### ISSUE TITLE
Add support for graphql@14.0.0

### ISSUE THREAD

**Issue by polco** [mickhansen/graphql-sequelize#626]

**Comment by Aukhan** [comment]
@polco the package.json suggests that it will work with graphql 14. We are running graphql 14 and haven't run into any issues yet. If you could help out with the features that aren't supported that could be a good starting point, Thanks.

**Comment by polco** [comment]
So sorry I didn't put any description. I mostly meant the package peer dependencies that were missing the 14 version, I don't have any problem with it either. It has been updated since! Thanks for the awesome work:)

**Comment by Aukhan** [comment]
thanks @polco appreciate it !
