### ISSUE TITLE
Question: How to make relations work? (Example project with sqlite DB inside)

### ISSUE THREAD

**Issue by ArturBaybulatov** [mickhansen/graphql-sequelize#629]
I got an example project, where I've set up a simple schema:

https://github.com/ArturBaybulatov/_nodejs-playground/tree/master/graphql-sequelize-basic-example (sample sqlite DB included; clone the repo, `cd graphql-sequelize-basic-example`, run `npm install`, then `npm start` to start the project)

So, when I query:

```
{
  categories(Id: 8) {
    Id
    CategoryName
    
    products {
      ProductName
      CategoryId
    }
  }
}
```

I expect to get only products from that category (with ID 8), but I get everything from a table:

![image](https://user-images.githubusercontent.com/3109399/46365017-1aa5ff00-c680-11e8-9b00-0f06eae92e5a.png)

Is there a way to fix this? Have I defined the schema the wrong way? Thanks

**Comment by Aukhan** [comment]
https://github.com/ArturBaybulatov/_nodejs-playground/blob/c32bbf5fa8031b7194eb9ec6d041895b0d66b3a9/graphql-sequelize-basic-example/schema.js#L47

This line is incorrect it needs to be defined as an association rather than I direct model, that's why you are getting all Products

this will change to
`            resolve: graphqlSequelize.resolver(models.Category.associations.Product),`

**Comment by mickhansen** [comment]
@ArturBaybulatov Was looking for the code for the specific resolver. However @Aukhan provided the answer

**Comment by Aukhan** [comment]
@mickhansen I would like to play my part in keeping this repo moving, we are using this repo in two major products now, keeping all opinions aside, I feel like this and Sequelize are great libraries and must be kept alive.
Please let me know if i could help out with triaging, setting up release goals and contribute code.
There's a bunch of issues that can be closed, some need more information while a few are real.
Thanks !

**Comment by mickhansen** [comment]
@Aukhan That sounds great, can always use help.

**Comment by Aukhan** [comment]
thanks @mickhansen, I guess this particular issue can be closed

**Comment by ArturBaybulatov** [comment]
@Aukhan Thanks for the response. Unfortunately this doesn't work. It geves me an error:

```
{
  "errors": [
    {
      "message": "Cannot read property 'getTableName' of undefined",
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ],
      "path": [
        "categories",
        0,
        "products"
      ]
    }
  ],
  "data": {
    "categories": [
      {
        "Id": 8,
        "CategoryName": "Seafood",
        "products": null
      }
    ]
  }
}
```
