### ISSUE TITLE
review function sanitizeEnumValue()

### ISSUE THREAD

**Issue by wwmoraes** [mickhansen/graphql-sequelize#640]
As per PR #637, the `function sanitizeEnumValue()` does not comply with the GraphQL documentation:

- Expects string-only values (GraphQL API declares `value?: any`)
  - GraphQL accepts (and states as "often") number values, which causes a TypeError on `value.trim()`
- sanitization of numeric-started strings result in underscore-prefixed values (`'1'` is sanitized to `'_1'`)
  - sequelize simply casts to string on schema, thus making those underscored values invalid

I didn't found any references on the docs for why number/numeric-started string values need an underscore prefix.

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/pull/502

**Comment by wwmoraes** [comment]
> #502

Great! Now I can play again with numeric enum values 🥇

**Comment by mickhansen** [comment]
@wwmoraes Huh? I was mostly referring to the PR that introduced this issue.

**Comment by wwmoraes** [comment]
> @wwmoraes Huh? I was mostly referring to the PR that introduced this issue.

Oh, my bad. The PR's title is misleading.

**Comment by wwmoraes** [comment]
Ok so just documenting here before any coding: the PR #502 does state that GraphQL enum types "only support ASCII alphanumeric characters, digits and underscores with leading non-digit" which is right, but it doesn't mention that, in GraphQL, there's no enum value: the name is the value itself.

Naming convention ([first](https://facebook.github.io/graphql/July2015/#sec-Tokens)/[second](https://facebook.github.io/graphql/October2015/#sec-Names)/[latest](https://facebook.github.io/graphql/June2018/#sec-Names) spec [and all in between]):
> _Name_ **:**
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**/[_A-Za-z][_0-9A-Za-z]*/**

Enum values ([first](https://facebook.github.io/graphql/July2015/#EnumValue)/[second](https://facebook.github.io/graphql/October2015/#EnumValue)/[latest](https://facebook.github.io/graphql/June2018/#EnumValue) spec):
* [First](https://facebook.github.io/graphql/July2015/#EnumValue) spec
> _EnumValue_ **:**
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Name_
* [Second](https://facebook.github.io/graphql/October2015/#EnumValue) and [latest](https://facebook.github.io/graphql/June2018/#EnumValue) spec [and all in between]:
> _EnumValue_ **:**
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Name_ but not **true** or **false** or **null**

Even though JS doesn't have an enum type, solutions like `Object.freeze()`'ing a key-value objects (being the values strings, numbers or even better, `Symbol()`) simulate the same enums saw in most languages. Thus, graphql-sequelize should transcript only the enum "name" to GraphQL, making the bridge between the name and value in sequelize queries.

**Comment by mickhansen** [comment]
@wwmoraes Mind working on a PR? Then we can discuss the changes and cut it as a major

**Comment by wwmoraes** [comment]
@mickhansen sure thing!
