### ISSUE TITLE
Cache enum types in attributeFields doesn't work as expected

### ISSUE THREAD

**Issue by alirizwan** [mickhansen/graphql-sequelize#646]
When calling attribute fields multiple times on same model, duplicate enumtypes gets created with an error:
`Error: Schema must contain unique named types but contains multiple types named "UserroleEnumType".`

**Comment by mcouthon** [comment]
Why was this closed? This still seems like an existing bug.

**Comment by mcouthon** [comment]
Actually, I solved it by doing this:
```javascript
const options = {
    cache: {},
    commentToDescription: true
  };
const fullModel = attributeFields(model, options);
options.allowNull = true;
const looseModel = attributeFields(model, options);
}
```

Seems to work well
