### ISSUE TITLE
Question about fields with default value

### ISSUE THREAD

**Issue by Yehonal** [mickhansen/graphql-sequelize#649]
Hi

I've a mysql database with hundreds of tables and i'm trying to bulk create graphql schemas and resolvers automatically. I'm trying to configure graphql-sequelize to help me with this job but i've found an issue:

when graphql-sequelize converts the Sequelize model in graphql schema it doesn't take care about fields with non-null fields with default values and wrap them with GraphQLNonNull, Shouldn't be it avoided or configurable?

Is it possible to avoid GraphQLNonNull when default value exist for that field?

**Comment by mickhansen** [comment]
Why would you not want GraphQLNonNull in that case?
In an case, no it's not possible, but you can skip the attribute and define it manually.

**Comment by Yehonal** [comment]
As i said i've hundreds of tables with thousands of attributes defined as "non-null" with default value, so i cannot do it manually.
Using non-null with default value means that you can avoid to specify field value in your insert query but you cannot assign a NULL. It's a normal behaviour for databases and would be nice that graphql-sequelize can be configured to allow null values in such case, so the responsibility of data consistency is assigned to the database.

I'm currently using allowNull for now but it includes also the case where there is no default value in sequelize/mysql.

**Comment by mickhansen** [comment]
If the database has a non null constraint i don't see a generic reason to ever not have the graphql field be non null as well, the validation would never fail.

You could simply copy the attribute fields method from this library and make your own if it's a productivity issue for you.

**Comment by Yehonal** [comment]
I'm using graphql-sequelize to generate input types so if you wrap that field with GraphQLNonNull, the database/sequelize default value is really useless because you cannot omit that field in graphql mutation query.

You should implement the default value for graphql instead of GraphQLNonNull wrapping (here is an example: https://graphql.org/graphql-js/type/#example-5)

Or maybe i'm missing something?

**Comment by mickhansen** [comment]
I see, you're the first one i've heard about that uses it for input types, i assumed we were talking about field types as that's what it's commonly used for.

I'd suggest writing your own input fields generator.

**Comment by Yehonal** [comment]
> I see, you're the first one i've heard about that uses it for input types, i assumed we were talking about field types as that's what it's commonly used for.
> 
> I'd suggest writing your own input fields generator.

ok thank you. I've copied your attributeFields file using this conditon:

```
            if (typeof attribute.defaultValue == "undefined" && (attribute.allowNull === false || attribute.primaryKey === true)) {
                memo[key].type = new graphql_1.GraphQLNonNull(memo[key].type);
            }
```

it's very useful for input types but maybe for schema type is not suggested. I'm not very skilled with GraphQL so i would ask you: in your opinion, what kind of implications are there if you have a schema without non-null graphql wrapper in front of a non-null database field with default value? (I don't know if I made this clear)

**Comment by Yehonal** [comment]
I've created a pull request with option to enable such feature, if anyone would use it for input type generation:

https://github.com/mickhansen/graphql-sequelize/pull/650

for example i've modified graphql-sequelize-crud utility to use it and now i'm able to create even crud methods automatically: https://github.com/Yehonal/graphql-sequelize-crud

thanks for support

**Comment by mickhansen** [comment]
Well i agree that it makes little sense to have a NonNull input field infront of a field with a default value.
However in general i haven't recommended that anyone use auto generated schemas in a long while as it to me goes against the benefits and nature of graphql

**Comment by Schlesiger** [comment]
I am interested in using this myself. What is the best way to apply the above code?
