### ISSUE TITLE
Remove relay peer dependency

### ISSUE THREAD

**Issue by mschipperheyn** [mickhansen/graphql-sequelize#655]
This library has a peer dependency on `relay`, which doesn't make a lot of sense if you use Apollo. Is it possible to remove it?

**Comment by mickhansen** [comment]
It has a peer dependency on `graphql-relay` as we use methods from that helper library: https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L1

**Comment by mschipperheyn** [comment]
Ok, yeah, makes sense I guess. Are there any limitations to be considered in relation to Apollo v2?

**Comment by mickhansen** [comment]
Apollo is just the client/server interface right? relay in this instance refers primarily to the relay graphql specification (nodes and connections), there's nothing specific to how your client is setup.
