### ISSUE TITLE
Literals in Relay createConnectionResolver({...}) where param stopped working

### ISSUE THREAD

**Issue by intellix** [mickhansen/graphql-sequelize#668]
**Sequelize 4.44**

Got something like this:
```ts
relay.createConnectionResolver({
  target: () => BoxItem,
  ignoreArgs: { ...connectionArgs, orderBy: true },
  where: () => {
    return {
      boxId: {
        [Op.eq]: sequelize.literal(`(SELECT "id" FROM "Box" WHERE "slug" = 'abc' and "marketId" = 1)`),
      },
    };
  },
});
```

Caused by this commit with **replaceWhereOperators**: https://github.com/mickhansen/graphql-sequelize/commit/3cb923f0799092df15cccd033363be7ef7730e97

When stepping through the debugger it seems like the type is lost:

**Before:**

<img width="315" alt="Screenshot 2019-06-07 19 58 28" src="https://user-images.githubusercontent.com/1162531/59102628-370ce080-895f-11e9-9ebd-5197c2ea6dc0.png">

**After:**

<img width="312" alt="Screenshot 2019-06-07 20 00 00" src="https://user-images.githubusercontent.com/1162531/59102631-383e0d80-895f-11e9-89a0-8ae23fff5ad6.png">

**Comment by intellix** [comment]
I'm not sure if this should work really. I can shove all of my logic into the before hook instead the where param. I don't know why I put it there in the first place.

**Comment by mickhansen** [comment]
Since we still support `where` it probably should work, not exactly sure how it broke, perhaps @Azerothian can lend some assistance.

**Comment by mickhansen** [comment]
the property symbols do appear to be turned into a regular key, probably the reason.

**Comment by mickhansen** [comment]
I personally only use `before`, i just find it easier when you have args that might influence eachother etc.

**Comment by intellix** [comment]
Thanks :) I've moved all logic from where to before. Not sure why I used it before

**Comment by mickhansen** [comment]
`where` was what i thought would be a clever idea, but in practice it sees little effective use.
