### ISSUE TITLE
null belongsTo lookup results in empty sequelize instance

### ISSUE THREAD

**Issue by mschipperheyn** [mickhansen/graphql-sequelize#679]
I'm not sure why this occurs and whether this is expected behavior.

I have implemented resolver to load associations in combination with dataloader.

I have an object with the following association:
```
Account.belongsTo(models.Photo, {
    foreignKey: 'photoId',
    constraints: false,
    onDelete: 'cascade',
    as: 'photo',
});
```

The resolver type for Account looks like this:
```
photo: resolver(() => models.Account.associations.photo),
```

When photoId is null, I get an empty sequelize instance (no dataValues) instead of null, resulting in errors.
I ended up resolving this overwriting the resolver, but I'm still trying to get it. Doesn't seem to happen on other associations without `constraints: false`

```
import { resolver as coreResolver } from 'graphql-sequelize';
import getDataloader from './sequelize/middleware/dataloader';

const createNullAfter = result => {
	if (!Array.isArray(result)) {
		if (
			!result ||
			Object.entries(
				result.get({
					plain: true,
				}),
			).length === 0
		)
			return null;
		return result;
	}
	return result;
};

export const resolver = (Model, options) =>
	coreResolver(Model, {
		after: createNullAfter,
		...options,
	});

```

**Comment by mickhansen** [comment]
A null value should simply result in a null result. I'm not sure if the issue here is in graphql-sequelize, dataloader-sequelize (if you use that) or in sequelize itself.

**Comment by mschipperheyn** [comment]
I do use `dataloader-sequelize`. So, it's weird. I thought so. I'll try to do some logging and try to figure it out.
