### ISSUE TITLE
Make an example with sequelize-typescript

### ISSUE THREAD

**Issue by canhkieu** [mickhansen/graphql-sequelize#681]
Hi @mickhansen 

I'm using graphql-sequelize with typescript by [sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript#readme)
Could you make and example with this project. Another way, I dont see any document about how to get records has many relations ship. In this case I can not get user with all posts.
```
User: id, name
Post: id, name, user_id
```

**Comment by mickhansen** [comment]
I don't use typescript, so i can't be of much help, as far as i understand all javascript is valid typescript right?
