### ISSUE TITLE
Enum Types cause duplicate type

### ISSUE THREAD

**Issue by coolhand79** [mickhansen/graphql-sequelize#684]
When using attributeFields on a model with an `enum` type, I consistently get

` "Error: Schema must contain uniquely named types but contains multiple types named "ComplianceNotenoteTypeEnumType"."`

I see references to using `cache` as a config, but it seems to have no affect.

```javascript
var cache = {};
module.exports = new GraphQLObjectType({
  name: ComplianceNote.name,
  description: 'A ComplianceNote',
  fields: () => ({
    ...attributeFields(ComplianceNote, {
      cache,
    }),
  }),
});
````

FWIW, my model looks like this:
```javascript
module.exports = (sequelize, DataTypes) => {
  const ComplianceNote = sequelize.define(
    'ComplianceNote',
    {
      notes: DataTypes.TEXT,
      noteType: {
        type: DataTypes.ENUM,
        values: [
          'Live Support',
          'Mailed Letter',
          'Need Demographics',
        ],
      },
    },
    { ...require('./utils/modelCommons') }
  );
  ComplianceNote.associate = function associate(models) {

  };
  return ComplianceNote;
};

```

**Comment by mickhansen** [comment]
You must be calling `attributeFields` multiple places, are you using the same cache object each place you do that?

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/blob/master/src/attributeFields.js#L39

**Comment by coolhand79** [comment]
You are absolutely right. I had to place a breakpoint to find it. Once I did, adding the cache object solved it. Thanks!
