### ISSUE TITLE
Support latest  Sequelize

### ISSUE THREAD

**Issue by mybottt** [mickhansen/graphql-sequelize#687]
Sequelize.js renamed Model.findById(id) to Model.findByPk(id).

Its causing issues when I use nodeField.resolve. graphql gives error "sequelize.models[model].findById is not a function". Right now I am using following code to fix this

db["users"].constructor.prototype.findById = (id) => db["users"].findByPk(id);

**Comment by mickhansen** [comment]
> Support latest graphgl-js

You mean support latest sequelize?

PR welcome, will need to support both methods depending on whats available.

**Comment by mybottt** [comment]
> 
> 
> > Support latest graphgl-js
> 
> You mean support latest sequelize?
> 
> PR welcome, will need to support both methods depending on whats available.

Yes I mean "Support latest Sequelize", changed title.
