### ISSUE TITLE
Can we use `attributeFields` with graphql SDL?

### ISSUE THREAD

**Issue by dnafication** [mickhansen/graphql-sequelize#697]
Can we use `attributeFields` with graphql SDL? If yes, how? are there any examples.

To clarify my question further. How to use features of `attributeFields` like mapping and type transformation without using a syntax like 

```
let trainerType = new GraphQLObjectType({
  name: 'User',
  description: 'A user',
  fields: _.assign(attributeFields(models.User), {
    pokemon: {
      type: new GraphQLList(pokemonType),
      resolve: resolver(models.User.Pokemon)
    }
  })
});
```

And use following instead

```
const schema = gql`
  id: String
  pokemon: [Pokemon]
`
```

**Comment by mickhansen** [comment]
No, it returns an object. For it to work with `gql` the template literal would have to accept that format.

**Comment by dnafication** [comment]
Thanks @mickhansen
