### ISSUE TITLE
How to express two way relationship

### ISSUE THREAD

**Issue by MaximilianLloyd** [mickhansen/graphql-sequelize#700]
Hi! First off thank youy for creating this library.

I was wondering how one would express a two way relationship like this. I want it to be possible to list the Stocks for each market. But also get the associated market, like you can do in sequelize. Seeing as one needs to be defined before the other, how would you go about implementing it in the example I posted?

![image](https://user-images.githubusercontent.com/10583205/111907077-0b83b900-8a54-11eb-94a8-9441c5ce2a6d.png)

I found this solution, but I'm not sure it's the best approach.
```js
const baseStockType = new GraphQLObjectType({
  name: 'MarketStocks',
  description: 'A stock',
  fields: attributeFields(Stock),
});

const marketType = new GraphQLObjectType({
  name: 'Market',
  description: 'Markets',
  fields: {
    ...attributeFields(Market),
    stocks: {
      type: new GraphQLList(baseStockType),
      resolve: resolver(Market.Stock),
    },
  },
});
```

Thank you if you take the time to read this.

**Comment by mickhansen** [comment]
`fields` can be a function, letting you use `require` inside to avoid cyclical dependency issues.

**Comment by MaximilianLloyd** [comment]
Makes sense. Thanks a lot!
