### ISSUE TITLE
Relay Connections with Dataloader

### ISSUE THREAD

**Issue by intellix** [mickhansen/graphql-sequelize#702]
So today I found that we're deeply nesting connections and causing havok:
```gql
users {
  edge {
    node {
      id
      posts {
        edges {
          node {
            ...Post
          }
        }
      }
    }
  }
}
```

In our API we create relay connections using the helper library provided here like:
```ts
export const UserConnection = relay.createConnectionResolver({
  orderBy: 'UserOrderBy',
  target: () => User,
});

export const PostConnection = relay.createConnectionResolver({
  orderBy: 'PostOrderBy',
  target: () => Post,
  before: (findOptions, args, context, info) => {
    if (info.source) {
      switch (info.source.constructor) {
        case User:
          findOptions.where.userId = info.source.id;
          break;
      }
    }
  },
});
```

And we use them like so:
```ts
export const UserResolver = {
  User: {
    id: globalIdField(User.name),
    posts: PostConnection.resolveConnection,
  }
  Query: {
    users: UserConnection.resolverConnection,
  }
},
```

We create our dataloader on a request basis like so:
```ts
const { resolver } = require('graphql-sequelize');

return new ApolloServer({
  context({ req, connection }) {
    // Magic swap for request-based dataloader
    resolver.contextToOptions = {
      dataloaderContext: [EXPECTED_OPTIONS_KEY],
    };
  }
})
```

The dataloader works fine, but we can't seem to get it to work for Relay connections and we end up with an insane amount of queries. 

Should we be doing something different or providing the dataloader context somehow? I can see inside the relay.js lib that it just uses `require('./resolver')` but when logging that, the `contextToOptions` is an empty object. I've even tried manually attaching the context before using the required resolver but still had no luck.

I can do a PR afterwards when I figure it out to add it to the Relay README.md but right now I'm completely bamboozled.

**Comment by mickhansen** [comment]
The dataloader might only work for actual relation calls, i don't believe it's smart enough to merge similar `where` queries at this time. 

It's been a while since i've used that specific code, but IIRC you want to modify the `target` callback to return the proper relationship based on the input:

https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L203
https://github.com/mickhansen/graphql-sequelize/blob/master/src/resolver.js#L46

`targetMaybeThunk` should be receiving `(source, args, context, info)` which should let you apply almost the same logic you currently do in `before`

**Comment by mickhansen** [comment]
As a general debug technique for batching i generally write some unit/integration tests and add `context.logging = console.log` and roughly count the number of queries.

**Comment by intellix** [comment]
Awesome, it actually works:
```ts
target: (findOptions, args, context, info) => {
  switch (info.parentType.name) {
    case User.name:
      return User.associations.posts;
    default:
      return Post;
  }
},
```

Thanks for that, I'll send a PR with an example of it in after I verify it working 100% and my above code is robust
