### ISSUE TITLE
sequelize model comment => graphql field description

### ISSUE THREAD

**Issue by floydspace** [mickhansen/graphql-sequelize#704]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `graphql-sequelize@9.4.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/graphql-sequelize/lib/attributeFields.js b/node_modules/graphql-sequelize/lib/attributeFields.js
index 8a2a1c9..b86dc37 100644
--- a/node_modules/graphql-sequelize/lib/attributeFields.js
+++ b/node_modules/graphql-sequelize/lib/attributeFields.js
@@ -36,7 +36,8 @@ module.exports = function (Model) {
     }
 
     memo[key] = {
-      type: typeMapper.toGraphQL(type, Model.sequelize.constructor)
+      type: typeMapper.toGraphQL(type, Model.sequelize.constructor),
+      description: attribute.comment
     };
 
     if (memo[key].type instanceof _graphql.GraphQLEnumType || memo[key].type instanceof _graphql.GraphQLList && memo[key].type.ofType instanceof _graphql.GraphQLEnumType) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by floydspace** [comment]
Hi @mickhansen, does it make sense to map sequelize model `comment` property to graphql field description?

**Comment by mickhansen** [comment]
Hi @floydspace. There's an option to do it: `options.commentToDescription` https://github.com/mickhansen/graphql-sequelize/blob/master/src/attributeFields.js#L63

**Comment by floydspace** [comment]
Thank you @mickhansen , my bad to not read the documentation. 🤦‍♂️
Good job.

**Comment by mickhansen** [comment]
No worries, not even sure it's documented anywhere hah
