### ISSUE TITLE
Unable to convert geometry to graphql type

### ISSUE THREAD

**Issue by mahady-manana** [mickhansen/graphql-sequelize#706]
graphql-sequelize v9.4.3
``` prop : {type: DataTypes.GEOMETRY, allowNull: true} ```
using  attributeFields(models.<Model>),

Can anyone help for this. I try to browse answer  but i didn't find.

**Comment by mickhansen** [comment]
You can exclude the field when calling `attributeFields`. `attributeFields(model, {exclude: ['prop'])`
