### ISSUE TITLE
Help with n-to-m through association schema mapping

### ISSUE THREAD

**Issue by moret** [mickhansen/graphql-sequelize#71]
Hi. I'm trying to build a schema over a model with an n-to-m relation through an association model. Basically, `Person` travels in sequence to many `Destinations`. I condensed [an example of it at a gist](https://gist.github.com/moret/fca0ccaf9fd16908131f).

When I query through the associated object, I'm able to get the `Destinations` in sequence, but that means I have an extra level on the query, and the relation with `hasMany` and `belongsTo` in `Sequelize` has to be mapped instead of the [n:m](http://docs.sequelizejs.com/en/latest/docs/associations/#nm) association:
```graphql
{
  travel {
    people(name: "Jane") {
      name
      personDestinations(order: "sequence") {
        destination {
          id
          name
        }
      }
    }
  }
}
```
```javascript
PersonModel.PersonDestinations = PersonModel.hasMany(PersonDestinationModel, {
  foreignKey: 'personId', as: 'Destinations'
});
PersonDestinationModel.Destination = PersonDestinationModel.belongsTo(DestinationModel, {
  foreignKey: 'destinationId', as: 'Destination'
});
```
When using n:m directly the query has one less level, I can mappings the relation with `belongsToMany`, but I couldn't figure out a way to use the association attributes to order it:
```graphql
{
  travel {
    people(name: "Jane") {
      name
      destinations {
        id
        name
      }
    }
  }
}
```
```javascript
PersonModel.Destinations = PersonModel.belongsToMany(DestinationModel, {
  through: PersonDestinationModel, foreignKey: 'personId', as: 'Destinations'
});
```

Would you suggest a more elegant way to build the schema for this relation? Thank you in advance. Bye!

**Comment by mickhansen** [comment]
`sequence` is on the join model i assume?
Hmm, `argsToFindOptions` (which handles `order`) is called before `before`.

You could use `destinations` as a target with `order` and then add a before filter to the resolver that moves the order from the main options to the through options. (Should then work both for prefetching and not).

You'll probably have to tinker with it a bit :)

**Comment by moret** [comment]
Thanks a lot for the quick reply @mickhansen . Yes, `sequence` is on the join model. I hadn't considering a `before` yet, I'll try tinkering with [the gist](https://gist.github.com/moret/fca0ccaf9fd16908131f) a little more then. If I get something working in these lines I'll post it here for reference!

**Comment by moret** [comment]
Updating, yes, I made it work with a `before` filter like you suggested. If I keep using it this way I will try to make a helper out of it. I updated the [example gist](https://gist.github.com/moret/fca0ccaf9fd16908131f#file-n-to-m-js-L101-L111). Thanks!
