### ISSUE TITLE
Fix order type in defaultListArgs

### ISSUE THREAD

**Issue by maheraldous** [mickhansen/graphql-sequelize#712]
Hello

The order type in defaultListArgs should be array not string so how to change that.
https://github.com/mickhansen/graphql-sequelize#defaultlistargs

Here they use array
http://docs.sequelizejs.com/en/latest/docs/querying/#ordering

Here I also get an error tells me to use array but since the type is string the GraphQL types validator dose not allows me to pass the array.
![image](https://user-images.githubusercontent.com/41970874/177631049-313ca2d5-b101-4f34-b00e-90553c854485.png)

**Comment by mickhansen** [comment]
Have you tried `reverse:id`?

**Comment by maheraldous** [comment]
Hello I tried something like this

`reverse:username`

and this

`username`

But none worked

Also `where` filter is work but when I add conditions like `like` or something like that as in the Sequelize docs and your example it dose not work because also the format validation block me as in `order` filter but it's ok for me because it's enough to just use `where` without conditions

**Comment by mickhansen** [comment]
You're welcome to submit a PR but I would simply recommend against relying on `defaultListArgs`

**Comment by maheraldous** [comment]
I will appreciate if you just change the type input of `order` to array this is the only issue of this case. But if you aren't able to do that it's bot a problem.
