### ISSUE TITLE
<table>.get<childtable>() not working

### ISSUE THREAD

**Issue by spyalert01** [mickhansen/graphql-sequelize#91]
I have the following code. 
Person can have many Post
I have already freeze my postgres table name

RwPost ->arPerson:->return arRec.getTbPerson();  [Is working well]
RwPerson->ArPost-> new GraphQLList(RwPost),->arRec.getTbPost();  [it says arRec.getTbPost is undefined]

what is wrong here?

import {
    GraphQLObjectType,
    GraphQLInt, 
    GraphQLString,
    GraphQLList,
    GraphQLSchema,
    GraphQLNonNull,
} from 'graphql';

import Db from './db';

const RwPerson = new GraphQLObjectType({
    name: 'RwPerson',
    description: 'This represent a person',
    fields: () => {
        return {
            id: {
                type: GraphQLInt,
                resolve(arRec) {
                    return arRec.id;
                }
            },
            vcFirstName: {
                type: GraphQLString,
                resolve(arRec) {
                    return arRec.vcFirstName;
                }
            },
            ArPost: {
                type: new GraphQLList(RwPost),
                resolve(arRec){
                    return arRec.getTbPost();
                }
            },
        }
    }
});

const RwPost = new GraphQLObjectType({
    name: 'RwPost',
    description: 'This represent a Post related to a person',
    fields: () => {
        return {
            id: {
                type: GraphQLInt,
                resolve(arRec) {
                    return arRec.id;
                }
            },
            vcTitle: {
                type: GraphQLString,
                resolve(arRec) {
                    return arRec.vcTitle;
                }
            },
            arPerson:{
                type: RwPerson,
                resolve(arRec){
                    return arRec.getTbPerson();
                },
            },
        }
    }
});

const Query = new GraphQLObjectType({
    name: 'Query',
    description: 'this is a root query',
    fields: () => {
        return {
            qrPerson: {
                type: new GraphQLList(RwPerson),
                args: {
                    id: {
                        type: GraphQLInt,
                    },
                    vcEmail: {
                        type: GraphQLString,
                    },
                },
                resolve(root, args){
                    return Db.models.TbPerson.findAll({where: args});
                },
            },
            qrPost: {
                type: new GraphQLList(RwPost),
                resolve(root, args){
                    return Db.models.TbPost.findAll({where: args});
                }
            },
        }
    },
});

const Schema = new GraphQLSchema({
    query: Query,
});

**Comment by mickhansen** [comment]
Doesn't look you are using graphql-sequelize at all.

**Comment by spyalert01** [comment]
what do you mean?
I have the sequelize define in my db.js

**Comment by mickhansen** [comment]
Take a look at the project page, look at what this project does, you are not using this project, you are using custom resolvers and Sequelize.

**Comment by spyalert01** [comment]
import Sequelize from 'sequelize';
I am using this

**Comment by mickhansen** [comment]
Yes, and this is `graphql-sequelize`, a helper library for using graphql and sequelize, not a support forum for graphql questions generally.
