### ISSUE TITLE
ACL on node fetches

### ISSUE THREAD

**Issue by mickhansen** [mickhansen/graphql-sequelize#92]
We support the relay node lookup ala:

``` js
{
  node(id: "someGlobalId") {
    ... on Object {
      fields
   }
  }
}
```

This internally goes through our node type mapper and does a `findById`. We currently have no way of hooking ACL into this process other than wrapping around findById or using a beforeFind hook, but that might interfer with other systems that might not necessarily have the same ACL constraints.

Anyone have any good way of solving this? Personally i need to only allow certain node lookups to certain people.

/cc @brad-decker @Aweary @idris

**Comment by idris** [comment]
For this reason, I'm using a custom solution for the nodeDefinitions.. looks something like:
```
models[type].findOne({ where: { [models[type].primaryKeyAttribute]: id, user_id: user.id } });
```

I also have some special case types where I just `findById` (public models).

Maybe a `beforeFind` hook for each type in `mapTypes` would work?  Something like:
```js
nodeTypeMapper.mapTypes({
  [Post.name]: {
    type: postType,
    beforeFind: (options, info) => { options.where.user_id = info.rootValue.id; return options; }
  }
});
```

In my case, that `beforeFind` function could be re-used for almost all models with the same ACL constraints, like so:
```js
function addUserConstraint(options, info) {
  options.where.user_id = info.rootValue.id;
  return options;
}
nodeTypeMapper.mapTypes({
  [Post.name]: {
    type: postType,
    beforeFind: addUserConstraint
  },
  [Project.name]: {
    type: projectType,
    beforeFind: addUserConstraint
  }
});
```

**Comment by brad-decker** [comment]
I like extending the before/after methodology from the resolver to the nodeTypeMapper. Good idea.

**Comment by mickhansen** [comment]
That could work. I hate having to remove findById since it's very trivial to cache, but maybe we can do something smart.

**Comment by mickhansen** [comment]
Agreed, i like atleast having the `after` hook for common ACL. With the direction i see graphql/sequelize going in anyways we want more batching and more post processing and less ad-hoc ACL queries.

**Comment by idris** [comment]
If by "batching" you mean something like DataLoader, the ACL stuff sort of moves into the DataLoader anyway.  For us, at least, we instantiate DataLoaders with every request so that it's tied to the user, and then all queries within that loader add `user_id` to the query.

**Comment by justinpincar** [comment]
Hey folks, just starting to write a classroom management tool using graphql-sequelize and was hoping to get some guidance around this ACL issue.

- Any more recent info on how to do an authorization check on node lookups? E.g. teachers can only view students with matching student.teacher_id

Thanks!

**Comment by intellix** [comment]
Was just implementing this myself and looking into a variety of different things which needed ACL applying and how to do them concerning their different method signatures. From reading through old issues and comments from Mick.

Users have Wallets:
- Users should not be able to view other user's wallets
- Admins are users with `user.permissions > 1` and can see everything
- I don't want non-admins to make a query for lists of wallets

**user-access-acl.js**
```ts
export function userHasAccess(result, context) {
  return context.user && (context.user.permissions > 1 || context.user.id === result.userId);
}

export function userOwnedBefore(findOptions, args, context) {
  findOptions.where = { userId: context.user.id };
  return findOptions;
}

export function userOwnedAfter(result, args, context) {
  return userCanView(result, context) ? result : null;
}
```
**ACL for Node querying directly**
```ts
nodeTypeMapper.mapTypes({
  [User.name]: UserType,
  [Wallet.name]: {
    type: WalletType,
    async resolve(globalId: string, context: Context) {
      const { id } = fromGlobalId(globalId);
      const wallet = await Wallet.findById(id);
      return userHasAccess(wallet, context) ? wallet : null;
    },
  },
});
```

**Blocking a wallets root query**
```ts
wallets: {
  type: WalletConnectionType.connectionType,
  args: WalletConnectionType.connectionArgs,
  resolve: (source: any, args: any, context: Context, info: any) => {
    if (!context.user || context.user.permissions < 2) {
      throw new Error('You lack the permissions to make this query');
    }

    return WalletConnectionType.resolve(source, args, context, info);
  },
},
```

**Block querying a wallet by ID**
```ts
wallet: {
  type: WalletType,
  args: {
    id: {
      type: new GraphQLNonNull(GraphQLID),
    },
  },
  resolve: async (source: any, args: any, context: Context, info: any) => {
    args.id = fromGlobalId(args.id).id;
    return await resolver(Wallet, {
      after: userOwnedAfter,
    })(source, args, context, info);
  },
},
```

The above should cover all vectors of fetching something without access to. Let me know if there's any way this can be improved and I hope it helps someone else looking for a complete list

**Comment by justinpincar** [comment]
@intellix Really helpful to see your implementation of the different approaches, thank you for sharing.

**Comment by intellix** [comment]
No problem :) was looking into providing a custom resolver but it looks like different things use different ways. Some need before hooks, others need after hooks. Relay seems to hardcode the locally provided resolver: https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L216
